/*
Dex Aggregator API

Testing BlockchainAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package chainstream_test

import (
	"context"
	openapi "github.com/chainstream-io/github.com/chainstream-io/chainstream-go-sdk/openapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_chainstream_BlockchainAPIService(t *testing.T) {

	configuration := openapi.NewConfiguration()
	apiClient := openapi.NewAPIClient(configuration)

	t.Run("Test BlockchainAPIService GetLatestBlock", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var chain openapi.ChainSymbol

		resp, httpRes, err := apiClient.BlockchainAPI.GetLatestBlock(context.Background(), chain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlockchainAPIService GetSupportedBlockchains", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BlockchainAPI.GetSupportedBlockchains(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
