/*
Dex Aggregator API

Testing DefiSolanaPumpfunAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package chainstream_test

import (
	"context"
	openapi "github.com/chainstream-io/github.com/chainstream-io/chainstream-go-sdk/openapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_chainstream_DefiSolanaPumpfunAPIService(t *testing.T) {

	configuration := openapi.NewConfiguration()
	apiClient := openapi.NewAPIClient(configuration)

	t.Run("Test DefiSolanaPumpfunAPIService PumpfunCreateToken", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefiSolanaPumpfunAPI.PumpfunCreateToken(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
