/*
Dex Aggregator API

Testing TransactionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package chainstream_test

import (
	"context"
	openapi "github.com/chainstream-io/chainstream-go-sdk/openapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_chainstream_TransactionAPIService(t *testing.T) {

	configuration := openapi.NewConfiguration()
	apiClient := openapi.NewAPIClient(configuration)

	t.Run("Test TransactionAPIService EstimateGasLimit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var chain string

		resp, httpRes, err := apiClient.TransactionAPI.EstimateGasLimit(context.Background(), chain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionAPIService GetGasPrice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var chain string

		resp, httpRes, err := apiClient.TransactionAPI.GetGasPrice(context.Background(), chain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionAPIService Send", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var chain string

		resp, httpRes, err := apiClient.TransactionAPI.Send(context.Background(), chain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
