// Package redpacket provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package redpacket

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for Chain.
const (
	ChainBsc Chain = "bsc"
	ChainEth Chain = "eth"
	ChainSol Chain = "sol"
)

// Defines values for ChainSymbol.
const (
	ChainSymbolBsc ChainSymbol = "bsc"
	ChainSymbolEth ChainSymbol = "eth"
	ChainSymbolSol ChainSymbol = "sol"
)

// Defines values for ClaimRedPacketInputChain.
const (
	ClaimRedPacketInputChainBsc ClaimRedPacketInputChain = "bsc"
	ClaimRedPacketInputChainEth ClaimRedPacketInputChain = "eth"
	ClaimRedPacketInputChainSol ClaimRedPacketInputChain = "sol"
)

// Defines values for CreateRedPacketInputChain.
const (
	CreateRedPacketInputChainBsc CreateRedPacketInputChain = "bsc"
	CreateRedPacketInputChainEth CreateRedPacketInputChain = "eth"
	CreateRedPacketInputChainSol CreateRedPacketInputChain = "sol"
)

// Defines values for GetRedpacketsParamsChain.
const (
	Bsc GetRedpacketsParamsChain = "bsc"
	Eth GetRedpacketsParamsChain = "eth"
	Sol GetRedpacketsParamsChain = "sol"
)

// Chain defines model for Chain.
type Chain string

// ChainSymbol defines model for ChainSymbol.
type ChainSymbol string

// ClaimRedPacketInput defines model for ClaimRedPacketInput.
type ClaimRedPacketInput struct {
	// Chain DTO.RED_PACKET.CHAIN
	Chain ClaimRedPacketInputChain `json:"chain"`

	// Claimer DTO.RED_PACKET.CLAIMER
	Claimer string `json:"claimer"`

	// PacketId DTO.RED_PACKET.PACKET_ID
	PacketId *string `json:"packetId,omitempty"`

	// Password DTO.RED_PACKET.PASSWORD
	Password *string `json:"password,omitempty"`

	// ShareId DTO.RED_PACKET.SHARE_ID
	ShareId *string `json:"shareId,omitempty"`
}

// ClaimRedPacketInputChain DTO.RED_PACKET.CHAIN
type ClaimRedPacketInputChain string

// CreateRedPacketInput defines model for CreateRedPacketInput.
type CreateRedPacketInput struct {
	// Chain DTO.RED_PACKET.CHAIN
	Chain CreateRedPacketInputChain `json:"chain"`

	// ClaimAuthority DTO.RED_PACKET.CLAIM_AUTHORITY
	ClaimAuthority *string `json:"claimAuthority,omitempty"`

	// Creator DTO.RED_PACKET.CREATOR
	Creator string `json:"creator"`

	// FixedAmount DTO.RED_PACKET.FIXED_AMOUNT
	FixedAmount *string `json:"fixedAmount,omitempty"`

	// MaxClaims DTO.RED_PACKET.MAX_CLAIMS
	MaxClaims int64 `json:"maxClaims"`

	// Memo DTO.RED_PACKET.MEMO
	Memo *string `json:"memo,omitempty"`

	// Mint DTO.RED_PACKET.MINT
	Mint string `json:"mint"`

	// Password DTO.RED_PACKET.PASSWORD
	Password *string `json:"password,omitempty"`

	// TotalAmount DTO.RED_PACKET.TOTAL_AMOUNT
	TotalAmount *string `json:"totalAmount,omitempty"`
}

// CreateRedPacketInputChain DTO.RED_PACKET.CHAIN
type CreateRedPacketInputChain string

// CreateRedPacketReply defines model for CreateRedPacketReply.
type CreateRedPacketReply struct {
	// ShareId DTO.RED_PACKET.SHARE_ID
	ShareId string `json:"shareId"`

	// TxSerialize DTO.RED_PACKET.SERIALIZED_TX
	TxSerialize string `json:"txSerialize"`
}

// RedPacketClaimDTO defines model for RedPacketClaimDTO.
type RedPacketClaimDTO struct {
	// Amount DTO.RED_PACKET.AMOUNT
	Amount string `json:"amount"`

	// Chain DTO.RED_PACKET.CHAIN
	Chain Chain `json:"chain"`

	// ClaimedAt DTO.RED_PACKET.CLAIMED_AT
	ClaimedAt int64 `json:"claimedAt"`

	// Claimer DTO.RED_PACKET.CLAIMER
	Claimer string `json:"claimer"`

	// Creator DTO.RED_PACKET.CREATOR
	Creator string `json:"creator"`

	// Mint DTO.RED_PACKET.MINT
	Mint string `json:"mint"`

	// PacketId DTO.RED_PACKET.PACKET_ID
	PacketId string `json:"packetId"`

	// TxHash DTO.RED_PACKET.TX_HASH
	TxHash string `json:"txHash"`
}

// RedPacketClaimsPage defines model for RedPacketClaimsPage.
type RedPacketClaimsPage struct {
	// EndCursor DTO.PAGE.END_CURSOR
	EndCursor string `json:"endCursor"`

	// HasNextPage DTO.PAGE.HAS_NEXT
	HasNextPage bool `json:"hasNextPage"`

	// Records Array of claim records
	Records []RedPacketClaimDTO `json:"records"`

	// StartCursor DTO.PAGE.START_CURSOR
	StartCursor string `json:"startCursor"`

	// Total DTO.PAGE.TOTAL
	Total int64 `json:"total"`
}

// RedPacketDTO defines model for RedPacketDTO.
type RedPacketDTO struct {
	// Chain GLOBAL.CHAIN.DESCRIPTION
	Chain Chain `json:"chain"`

	// ClaimAuthority DTO.RED_PACKET.CLAIM_AUTHORITY
	ClaimAuthority string `json:"claimAuthority"`

	// ClaimedAmount DTO.RED_PACKET.CLAIMED_AMOUNT
	ClaimedAmount string `json:"claimedAmount"`

	// ClaimedCount DTO.RED_PACKET.CLAIMED_COUNT
	ClaimedCount int64 `json:"claimedCount"`

	// CreatedAt DTO.RED_PACKET.CREATED_AT
	CreatedAt int64 `json:"createdAt"`

	// Creator DTO.RED_PACKET.CREATOR
	Creator string `json:"creator"`

	// Expiration DTO.RED_PACKET.EXPIRATION
	Expiration int64 `json:"expiration"`

	// Expired DTO.RED_PACKET.WITHDRAWED
	Expired bool `json:"expired"`

	// ExpiredAt DTO.RED_PACKET.EXPIRES_AT
	ExpiredAt int64 `json:"expiredAt"`

	// Id DTO.RED_PACKET.ID
	Id string `json:"id"`

	// MaxClaims DTO.RED_PACKET.MAX_CLAIMS
	MaxClaims int64 `json:"maxClaims"`

	// Memo DTO.RED_PACKET.MEMO
	Memo string `json:"memo"`

	// Mint DTO.RED_PACKET.MINT
	Mint string `json:"mint"`

	// RefundedAmount DTO.RED_PACKET.REFUND_AMOUNT
	RefundedAmount string `json:"refundedAmount"`

	// ShareId DTO.RED_PACKET.SHARE_ID
	ShareId string `json:"shareId"`

	// TotalAmount DTO.RED_PACKET.TOTAL_AMOUNT
	TotalAmount string `json:"totalAmount"`

	// TxHash DTO.RED_PACKET.TX_HASH
	TxHash string `json:"txHash"`
}

// RedPacketReply defines model for RedPacketReply.
type RedPacketReply struct {
	// TxSerialize DTO.RED_PACKET.SERIALIZED_TX
	TxSerialize string `json:"txSerialize"`
}

// RedPacketSendTxInput defines model for RedPacketSendTxInput.
type RedPacketSendTxInput struct {
	// SignedTx DTO.RED_PACKET.SIGNED_TX
	SignedTx string `json:"signedTx"`
}

// RedPacketSendTxResponse defines model for RedPacketSendTxResponse.
type RedPacketSendTxResponse struct {
	// Signature DTO.RED_PACKET.SIGNATURE
	Signature string `json:"signature"`
}

// RedPacketsPage defines model for RedPacketsPage.
type RedPacketsPage struct {
	// EndCursor DTO.PAGE.END_CURSOR
	EndCursor string `json:"endCursor"`

	// HasNextPage DTO.PAGE.HAS_NEXT
	HasNextPage bool `json:"hasNextPage"`

	// Records Array of red packets
	Records []RedPacketDTO `json:"records"`

	// StartCursor DTO.PAGE.START_CURSOR
	StartCursor string `json:"startCursor"`

	// Total DTO.PAGE.TOTAL
	Total int64 `json:"total"`
}

// GetRedpacketsParams defines parameters for GetRedpackets.
type GetRedpacketsParams struct {
	// Cursor DTO.RED_PACKET.CURSOR
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit DTO.RED_PACKET.LIMIT
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Direction DTO.RED_PACKET.DIRECTION
	Direction *string `form:"direction,omitempty" json:"direction,omitempty"`

	// Creator DTO.RED_PACKET.CREATOR
	Creator *string `form:"creator,omitempty" json:"creator,omitempty"`

	// Chain DTO.RED_PACKET.CHAIN
	Chain *GetRedpacketsParamsChain `form:"chain,omitempty" json:"chain,omitempty"`
}

// GetRedpacketsParamsChain defines parameters for GetRedpackets.
type GetRedpacketsParamsChain string

// GetClaimsByAddressParams defines parameters for GetClaimsByAddress.
type GetClaimsByAddressParams struct {
	// Cursor DTO.RED_PACKET.CURSOR
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit DTO.RED_PACKET.LIMIT
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Direction DTO.RED_PACKET.DIRECTION
	Direction *string `form:"direction,omitempty" json:"direction,omitempty"`
}

// GetRedpacketsByAddressParams defines parameters for GetRedpacketsByAddress.
type GetRedpacketsByAddressParams struct {
	// Cursor DTO.RED_PACKET.CURSOR
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit DTO.RED_PACKET.LIMIT
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Direction DTO.RED_PACKET.DIRECTION
	Direction *string `form:"direction,omitempty" json:"direction,omitempty"`
}

// GetClaimsParams defines parameters for GetClaims.
type GetClaimsParams struct {
	// Cursor DTO.RED_PACKET.CURSOR
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit DTO.RED_PACKET.LIMIT
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Direction DTO.RED_PACKET.DIRECTION
	Direction *string `form:"direction,omitempty" json:"direction,omitempty"`
}

// ClaimRedpacketJSONRequestBody defines body for ClaimRedpacket for application/json ContentType.
type ClaimRedpacketJSONRequestBody = ClaimRedPacketInput

// CreateRedpacketJSONRequestBody defines body for CreateRedpacket for application/json ContentType.
type CreateRedpacketJSONRequestBody = CreateRedPacketInput

// RedpacketSendJSONRequestBody defines body for RedpacketSend for application/json ContentType.
type RedpacketSendJSONRequestBody = RedPacketSendTxInput

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetRedpackets request
	GetRedpackets(ctx context.Context, params *GetRedpacketsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClaimsByAddress request
	GetClaimsByAddress(ctx context.Context, address string, params *GetClaimsByAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRedpacketsByAddress request
	GetRedpacketsByAddress(ctx context.Context, address string, params *GetRedpacketsByAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClaimRedpacketWithBody request with any body
	ClaimRedpacketWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ClaimRedpacket(ctx context.Context, chain ChainSymbol, body ClaimRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRedpacketWithBody request with any body
	CreateRedpacketWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRedpacket(ctx context.Context, chain ChainSymbol, body CreateRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RedpacketSendWithBody request with any body
	RedpacketSendWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RedpacketSend(ctx context.Context, chain ChainSymbol, body RedpacketSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRedpacket request
	GetRedpacket(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClaims request
	GetClaims(ctx context.Context, id string, params *GetClaimsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetRedpackets(ctx context.Context, params *GetRedpacketsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRedpacketsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClaimsByAddress(ctx context.Context, address string, params *GetClaimsByAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClaimsByAddressRequest(c.Server, address, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRedpacketsByAddress(ctx context.Context, address string, params *GetRedpacketsByAddressParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRedpacketsByAddressRequest(c.Server, address, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClaimRedpacketWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClaimRedpacketRequestWithBody(c.Server, chain, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClaimRedpacket(ctx context.Context, chain ChainSymbol, body ClaimRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClaimRedpacketRequest(c.Server, chain, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRedpacketWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRedpacketRequestWithBody(c.Server, chain, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRedpacket(ctx context.Context, chain ChainSymbol, body CreateRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRedpacketRequest(c.Server, chain, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RedpacketSendWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRedpacketSendRequestWithBody(c.Server, chain, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RedpacketSend(ctx context.Context, chain ChainSymbol, body RedpacketSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRedpacketSendRequest(c.Server, chain, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRedpacket(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRedpacketRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClaims(ctx context.Context, id string, params *GetClaimsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClaimsRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRedpacketsRequest generates requests for GetRedpackets
func NewGetRedpacketsRequest(server string, params *GetRedpacketsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Creator != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "creator", runtime.ParamLocationQuery, *params.Creator); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Chain != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "chain", runtime.ParamLocationQuery, *params.Chain); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClaimsByAddressRequest generates requests for GetClaimsByAddress
func NewGetClaimsByAddressRequest(server string, address string, params *GetClaimsByAddressParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "address", runtime.ParamLocationPath, address)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket/wallet/%s/claims", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRedpacketsByAddressRequest generates requests for GetRedpacketsByAddress
func NewGetRedpacketsByAddressRequest(server string, address string, params *GetRedpacketsByAddressParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "address", runtime.ParamLocationPath, address)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket/wallet/%s/redpackets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewClaimRedpacketRequest calls the generic ClaimRedpacket builder with application/json body
func NewClaimRedpacketRequest(server string, chain ChainSymbol, body ClaimRedpacketJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewClaimRedpacketRequestWithBody(server, chain, "application/json", bodyReader)
}

// NewClaimRedpacketRequestWithBody generates requests for ClaimRedpacket with any type of body
func NewClaimRedpacketRequestWithBody(server string, chain ChainSymbol, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chain", runtime.ParamLocationPath, chain)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket/%s/claim", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateRedpacketRequest calls the generic CreateRedpacket builder with application/json body
func NewCreateRedpacketRequest(server string, chain ChainSymbol, body CreateRedpacketJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRedpacketRequestWithBody(server, chain, "application/json", bodyReader)
}

// NewCreateRedpacketRequestWithBody generates requests for CreateRedpacket with any type of body
func NewCreateRedpacketRequestWithBody(server string, chain ChainSymbol, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chain", runtime.ParamLocationPath, chain)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket/%s/create", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRedpacketSendRequest calls the generic RedpacketSend builder with application/json body
func NewRedpacketSendRequest(server string, chain ChainSymbol, body RedpacketSendJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRedpacketSendRequestWithBody(server, chain, "application/json", bodyReader)
}

// NewRedpacketSendRequestWithBody generates requests for RedpacketSend with any type of body
func NewRedpacketSendRequestWithBody(server string, chain ChainSymbol, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chain", runtime.ParamLocationPath, chain)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket/%s/send", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRedpacketRequest generates requests for GetRedpacket
func NewGetRedpacketRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClaimsRequest generates requests for GetClaims
func NewGetClaimsRequest(server string, id string, params *GetClaimsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/redpacket/%s/claims", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetRedpacketsWithResponse request
	GetRedpacketsWithResponse(ctx context.Context, params *GetRedpacketsParams, reqEditors ...RequestEditorFn) (*GetRedpacketsResponse, error)

	// GetClaimsByAddressWithResponse request
	GetClaimsByAddressWithResponse(ctx context.Context, address string, params *GetClaimsByAddressParams, reqEditors ...RequestEditorFn) (*GetClaimsByAddressResponse, error)

	// GetRedpacketsByAddressWithResponse request
	GetRedpacketsByAddressWithResponse(ctx context.Context, address string, params *GetRedpacketsByAddressParams, reqEditors ...RequestEditorFn) (*GetRedpacketsByAddressResponse, error)

	// ClaimRedpacketWithBodyWithResponse request with any body
	ClaimRedpacketWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClaimRedpacketResponse, error)

	ClaimRedpacketWithResponse(ctx context.Context, chain ChainSymbol, body ClaimRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*ClaimRedpacketResponse, error)

	// CreateRedpacketWithBodyWithResponse request with any body
	CreateRedpacketWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRedpacketResponse, error)

	CreateRedpacketWithResponse(ctx context.Context, chain ChainSymbol, body CreateRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRedpacketResponse, error)

	// RedpacketSendWithBodyWithResponse request with any body
	RedpacketSendWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RedpacketSendResponse, error)

	RedpacketSendWithResponse(ctx context.Context, chain ChainSymbol, body RedpacketSendJSONRequestBody, reqEditors ...RequestEditorFn) (*RedpacketSendResponse, error)

	// GetRedpacketWithResponse request
	GetRedpacketWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetRedpacketResponse, error)

	// GetClaimsWithResponse request
	GetClaimsWithResponse(ctx context.Context, id string, params *GetClaimsParams, reqEditors ...RequestEditorFn) (*GetClaimsResponse, error)
}

type GetRedpacketsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RedPacketsPage
}

// Status returns HTTPResponse.Status
func (r GetRedpacketsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRedpacketsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClaimsByAddressResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RedPacketClaimsPage
}

// Status returns HTTPResponse.Status
func (r GetClaimsByAddressResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClaimsByAddressResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRedpacketsByAddressResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RedPacketsPage
}

// Status returns HTTPResponse.Status
func (r GetRedpacketsByAddressResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRedpacketsByAddressResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ClaimRedpacketResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RedPacketReply
}

// Status returns HTTPResponse.Status
func (r ClaimRedpacketResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClaimRedpacketResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateRedpacketResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateRedPacketReply
}

// Status returns HTTPResponse.Status
func (r CreateRedpacketResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRedpacketResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RedpacketSendResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RedPacketSendTxResponse
}

// Status returns HTTPResponse.Status
func (r RedpacketSendResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RedpacketSendResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRedpacketResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RedPacketDTO
}

// Status returns HTTPResponse.Status
func (r GetRedpacketResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRedpacketResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClaimsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RedPacketClaimsPage
}

// Status returns HTTPResponse.Status
func (r GetClaimsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClaimsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetRedpacketsWithResponse request returning *GetRedpacketsResponse
func (c *ClientWithResponses) GetRedpacketsWithResponse(ctx context.Context, params *GetRedpacketsParams, reqEditors ...RequestEditorFn) (*GetRedpacketsResponse, error) {
	rsp, err := c.GetRedpackets(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRedpacketsResponse(rsp)
}

// GetClaimsByAddressWithResponse request returning *GetClaimsByAddressResponse
func (c *ClientWithResponses) GetClaimsByAddressWithResponse(ctx context.Context, address string, params *GetClaimsByAddressParams, reqEditors ...RequestEditorFn) (*GetClaimsByAddressResponse, error) {
	rsp, err := c.GetClaimsByAddress(ctx, address, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClaimsByAddressResponse(rsp)
}

// GetRedpacketsByAddressWithResponse request returning *GetRedpacketsByAddressResponse
func (c *ClientWithResponses) GetRedpacketsByAddressWithResponse(ctx context.Context, address string, params *GetRedpacketsByAddressParams, reqEditors ...RequestEditorFn) (*GetRedpacketsByAddressResponse, error) {
	rsp, err := c.GetRedpacketsByAddress(ctx, address, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRedpacketsByAddressResponse(rsp)
}

// ClaimRedpacketWithBodyWithResponse request with arbitrary body returning *ClaimRedpacketResponse
func (c *ClientWithResponses) ClaimRedpacketWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClaimRedpacketResponse, error) {
	rsp, err := c.ClaimRedpacketWithBody(ctx, chain, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClaimRedpacketResponse(rsp)
}

func (c *ClientWithResponses) ClaimRedpacketWithResponse(ctx context.Context, chain ChainSymbol, body ClaimRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*ClaimRedpacketResponse, error) {
	rsp, err := c.ClaimRedpacket(ctx, chain, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClaimRedpacketResponse(rsp)
}

// CreateRedpacketWithBodyWithResponse request with arbitrary body returning *CreateRedpacketResponse
func (c *ClientWithResponses) CreateRedpacketWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRedpacketResponse, error) {
	rsp, err := c.CreateRedpacketWithBody(ctx, chain, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRedpacketResponse(rsp)
}

func (c *ClientWithResponses) CreateRedpacketWithResponse(ctx context.Context, chain ChainSymbol, body CreateRedpacketJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRedpacketResponse, error) {
	rsp, err := c.CreateRedpacket(ctx, chain, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRedpacketResponse(rsp)
}

// RedpacketSendWithBodyWithResponse request with arbitrary body returning *RedpacketSendResponse
func (c *ClientWithResponses) RedpacketSendWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RedpacketSendResponse, error) {
	rsp, err := c.RedpacketSendWithBody(ctx, chain, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRedpacketSendResponse(rsp)
}

func (c *ClientWithResponses) RedpacketSendWithResponse(ctx context.Context, chain ChainSymbol, body RedpacketSendJSONRequestBody, reqEditors ...RequestEditorFn) (*RedpacketSendResponse, error) {
	rsp, err := c.RedpacketSend(ctx, chain, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRedpacketSendResponse(rsp)
}

// GetRedpacketWithResponse request returning *GetRedpacketResponse
func (c *ClientWithResponses) GetRedpacketWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetRedpacketResponse, error) {
	rsp, err := c.GetRedpacket(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRedpacketResponse(rsp)
}

// GetClaimsWithResponse request returning *GetClaimsResponse
func (c *ClientWithResponses) GetClaimsWithResponse(ctx context.Context, id string, params *GetClaimsParams, reqEditors ...RequestEditorFn) (*GetClaimsResponse, error) {
	rsp, err := c.GetClaims(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClaimsResponse(rsp)
}

// ParseGetRedpacketsResponse parses an HTTP response from a GetRedpacketsWithResponse call
func ParseGetRedpacketsResponse(rsp *http.Response) (*GetRedpacketsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRedpacketsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RedPacketsPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetClaimsByAddressResponse parses an HTTP response from a GetClaimsByAddressWithResponse call
func ParseGetClaimsByAddressResponse(rsp *http.Response) (*GetClaimsByAddressResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClaimsByAddressResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RedPacketClaimsPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRedpacketsByAddressResponse parses an HTTP response from a GetRedpacketsByAddressWithResponse call
func ParseGetRedpacketsByAddressResponse(rsp *http.Response) (*GetRedpacketsByAddressResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRedpacketsByAddressResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RedPacketsPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseClaimRedpacketResponse parses an HTTP response from a ClaimRedpacketWithResponse call
func ParseClaimRedpacketResponse(rsp *http.Response) (*ClaimRedpacketResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClaimRedpacketResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RedPacketReply
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateRedpacketResponse parses an HTTP response from a CreateRedpacketWithResponse call
func ParseCreateRedpacketResponse(rsp *http.Response) (*CreateRedpacketResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRedpacketResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateRedPacketReply
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRedpacketSendResponse parses an HTTP response from a RedpacketSendWithResponse call
func ParseRedpacketSendResponse(rsp *http.Response) (*RedpacketSendResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RedpacketSendResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RedPacketSendTxResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRedpacketResponse parses an HTTP response from a GetRedpacketWithResponse call
func ParseGetRedpacketResponse(rsp *http.Response) (*GetRedpacketResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRedpacketResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RedPacketDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetClaimsResponse parses an HTTP response from a GetClaimsWithResponse call
func ParseGetClaimsResponse(rsp *http.Response) (*GetClaimsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClaimsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RedPacketClaimsPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
