
// Package trade provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package trade

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)




// Defines values for ActivitySortBy.
const (

  TimestampAsc ActivitySortBy = "timestampAsc"
  TimestampDesc ActivitySortBy = "timestampDesc"
  TotalUsdAsc ActivitySortBy = "totalUsdAsc"
  TotalUsdDesc ActivitySortBy = "totalUsdDesc"
)

// Valid indicates whether the value is a known member of the ActivitySortBy enum.
func (e ActivitySortBy) Valid() bool {
    switch e {
    case TimestampAsc:
        return true
    case TimestampDesc:
        return true
    case TotalUsdAsc:
        return true
    case TotalUsdDesc:
        return true
    default:
        return false
    }
}


// Defines values for ActivityType.
const (

  ActivityTypeBUY ActivityType = "BUY"
  ActivityTypeLIQUIDITYADD ActivityType = "LIQUIDITY_ADD"
  ActivityTypeLIQUIDITYINITIALIZE ActivityType = "LIQUIDITY_INITIALIZE"
  ActivityTypeLIQUIDITYREMOVE ActivityType = "LIQUIDITY_REMOVE"
  ActivityTypeREDPACKETCLAIM ActivityType = "RED_PACKET_CLAIM"
  ActivityTypeREDPACKETCOMPLETE ActivityType = "RED_PACKET_COMPLETE"
  ActivityTypeREDPACKETCREATE ActivityType = "RED_PACKET_CREATE"
  ActivityTypeREDPACKETREFUND ActivityType = "RED_PACKET_REFUND"
  ActivityTypeSELL ActivityType = "SELL"
)

// Valid indicates whether the value is a known member of the ActivityType enum.
func (e ActivityType) Valid() bool {
    switch e {
    case ActivityTypeBUY:
        return true
    case ActivityTypeLIQUIDITYADD:
        return true
    case ActivityTypeLIQUIDITYINITIALIZE:
        return true
    case ActivityTypeLIQUIDITYREMOVE:
        return true
    case ActivityTypeREDPACKETCLAIM:
        return true
    case ActivityTypeREDPACKETCOMPLETE:
        return true
    case ActivityTypeREDPACKETCREATE:
        return true
    case ActivityTypeREDPACKETREFUND:
        return true
    case ActivityTypeSELL:
        return true
    default:
        return false
    }
}


// Defines values for ChainSymbol.
const (

  Bsc ChainSymbol = "bsc"
  Eth ChainSymbol = "eth"
  Sol ChainSymbol = "sol"
)

// Valid indicates whether the value is a known member of the ChainSymbol enum.
func (e ChainSymbol) Valid() bool {
    switch e {
    case Bsc:
        return true
    case Eth:
        return true
    case Sol:
        return true
    default:
        return false
    }
}


// Defines values for PageDirection.
const (

  Next PageDirection = "next"
  Prev PageDirection = "prev"
)

// Valid indicates whether the value is a known member of the PageDirection enum.
func (e PageDirection) Valid() bool {
    switch e {
    case Next:
        return true
    case Prev:
        return true
    default:
        return false
    }
}


// Defines values for SortDirection.
const (

  Asc SortDirection = "asc"
  Desc SortDirection = "desc"
)

// Valid indicates whether the value is a known member of the SortDirection enum.
func (e SortDirection) Valid() bool {
    switch e {
    case Asc:
        return true
    case Desc:
        return true
    default:
        return false
    }
}


// Defines values for TimeFrame.
const (

  N12h TimeFrame = "12h"
  N1h TimeFrame = "1h"
  N24h TimeFrame = "24h"
  N2h TimeFrame = "2h"
  N30m TimeFrame = "30m"
  N4h TimeFrame = "4h"
  N6h TimeFrame = "6h"
  N8h TimeFrame = "8h"
)

// Valid indicates whether the value is a known member of the TimeFrame enum.
func (e TimeFrame) Valid() bool {
    switch e {
    case N12h:
        return true
    case N1h:
        return true
    case N24h:
        return true
    case N2h:
        return true
    case N30m:
        return true
    case N4h:
        return true
    case N6h:
        return true
    case N8h:
        return true
    default:
        return false
    }
}


// Defines values for TopTraderSortBy.
const (

  TradeAmount TopTraderSortBy = "tradeAmount"
  TradeCount TopTraderSortBy = "tradeCount"
)

// Valid indicates whether the value is a known member of the TopTraderSortBy enum.
func (e TopTraderSortBy) Valid() bool {
    switch e {
    case TradeAmount:
        return true
    case TradeCount:
        return true
    default:
        return false
    }
}


// Defines values for TradeType.
const (

  TradeTypeBUY TradeType = "BUY"
  TradeTypeSELL TradeType = "SELL"
)

// Valid indicates whether the value is a known member of the TradeType enum.
func (e TradeType) Valid() bool {
    switch e {
    case TradeTypeBUY:
        return true
    case TradeTypeSELL:
        return true
    default:
        return false
    }
}


// Defines values for TraderPnlResolution.
const (

  N1d TraderPnlResolution = "1d"
  N30d TraderPnlResolution = "30d"
  N7d TraderPnlResolution = "7d"
)

// Valid indicates whether the value is a known member of the TraderPnlResolution enum.
func (e TraderPnlResolution) Valid() bool {
    switch e {
    case N1d:
        return true
    case N30d:
        return true
    case N7d:
        return true
    default:
        return false
    }
}



// ActivitySortBy Sort field and direction for activities query
type ActivitySortBy  string

// ActivityType Activity type (extends TradeType)
type ActivityType  string

// ChainSymbol Supported blockchain chains
type ChainSymbol  string

// PageDirection Pagination direction
type PageDirection  string

// PageResponseTopTrader Generic pagination response
type PageResponseTopTrader  struct {
// Data Page data
    Data []struct {
// BuyAmount ENTITY.TOP_TRADER.BUY_AMOUNT
    BuyAmount string`json:"buyAmount"`

// BuyAmountInNative ENTITY.TOP_TRADER.BUY_AMOUNT_IN_NATIVE
    BuyAmountInNative string`json:"buyAmountInNative"`

// BuyAmountInUsd ENTITY.TOP_TRADER.BUY_AMOUNT_IN_USD
    BuyAmountInUsd string`json:"buyAmountInUsd"`

// BuyCount ENTITY.TOP_TRADER.BUY_COUNT
    BuyCount int64`json:"buyCount"`

// SellAmount ENTITY.TOP_TRADER.SELL_AMOUNT
    SellAmount string`json:"sellAmount"`

// SellAmountInNative ENTITY.TOP_TRADER.SELL_AMOUNT_IN_NATIVE
    SellAmountInNative string`json:"sellAmountInNative"`

// SellAmountInUsd ENTITY.TOP_TRADER.SELL_AMOUNT_IN_USD
    SellAmountInUsd string`json:"sellAmountInUsd"`

// SellCount ENTITY.TOP_TRADER.SELL_COUNT
    SellCount int64`json:"sellCount"`

// TokenAddress ENTITY.TOP_TRADER.TOKEN_ADDRESS
    TokenAddress string`json:"tokenAddress"`

// TradeAmount ENTITY.TOP_TRADER.TRADE_AMOUNT
    TradeAmount string`json:"tradeAmount"`

// TradeCount ENTITY.TOP_TRADER.TRADE_COUNT
    TradeCount int64`json:"tradeCount"`

// WalletAddress ENTITY.TOP_TRADER.WALLET_ADDRESS
    WalletAddress string`json:"walletAddress"`
}`json:"data"`

// EndCursor Cursor for the end of current page
    EndCursor *string`json:"endCursor,omitempty"`

// HasNext Whether there is a next page
    HasNext *bool`json:"hasNext,omitempty"`

// HasPrev Whether there is a previous page
    HasPrev *bool`json:"hasPrev,omitempty"`

// StartCursor Cursor for the start of current page
    StartCursor *string`json:"startCursor,omitempty"`
}

// PageResponseTradeDetail Generic pagination response
type PageResponseTradeDetail  struct {
// Data Page data
    Data []struct {
// AccountAddress Solana token account address (ATA), distinct from accountOwnerAddress (wallet owner).
    AccountAddress *string`json:"accountAddress,omitempty"`

// AccountOwnerAddress Account owner address (trader wallet)
    AccountOwnerAddress string`json:"accountOwnerAddress"`

// AddrType Address type from dexes_dwd.address_labels.
// 1=CEX, 2=Market Maker, 3=VC, 4=KOL, 5=DeFi, 6=Treasury, 7=Bridge, 8=Hacker.
// Matches GMGN `addr_type`.
    AddrType *int64`json:"addrType,omitempty"`

// BlockHeight Block height
    BlockHeight int64`json:"blockHeight"`

// BlockTimestamp Block timestamp (milliseconds)
    BlockTimestamp int64`json:"blockTimestamp"`

// Chain Chain identifier
    Chain string`json:"chain"`

// DexFeeInNative DEX protocol fee in native currency.
// Aggregated from fees_processed[PROTOCOL] entries (trade-processing-pipeline Bug A fix required).
// Null when no PROTOCOL fee data is available (e.g. SOL — ETL not yet populated).
    DexFeeInNative *string`json:"dexFeeInNative,omitempty"`

// DexFeeInUsd DEX protocol fee in USD.
// Uses the same native-price snapshot as dex_fee_in_native; satisfies same-snapshot constraint.
// Null when no PROTOCOL fee data is available.
    DexFeeInUsd *string`json:"dexFeeInUsd,omitempty"`

// DexImage DEX image
    DexImage *string`json:"dexImage,omitempty"`

// DexProgramAddress DEX program address
    DexProgramAddress *string`json:"dexProgramAddress,omitempty"`

// DexProtocolFamily DEX protocol family
    DexProtocolFamily *string`json:"dexProtocolFamily,omitempty"`

// GasFee Gas fee (raw: lamports for SOL, Gwei for BSC)
    GasFee *int64`json:"gasFee,omitempty"`

// GasFeeInNative Gas fee in native currency (SOL / BNB / ETH)
    GasFeeInNative *string`json:"gasFeeInNative,omitempty"`

// GasFeeInUsd Gas fee in USD
    GasFeeInUsd *string`json:"gasFeeInUsd,omitempty"`

// HistoryBoughtAmount Cumulative token quantity bought by this wallet (up to and including this trade).
// Matches GMGN `history_bought_amount`.
    HistoryBoughtAmount *string`json:"historyBoughtAmount,omitempty"`

// HistorySoldAmount Cumulative token quantity sold by this wallet (up to and including this trade).
// Matches GMGN `history_sold_amount`.
    HistorySoldAmount *string`json:"historySoldAmount,omitempty"`

// HistorySoldIncome Cumulative sell income (USD) for this wallet on this token (up to and including this trade).
// Matches GMGN `history_sold_income`.
    HistorySoldIncome *string`json:"historySoldIncome,omitempty"`

// IsOpenOrClose Position lifecycle: 0=normal, 1=open_position, 2=close_position
// Matches GMGN `is_open_or_close` field.
    IsOpenOrClose *int32`json:"isOpenOrClose,omitempty"`

// MakerEventTags Trade behaviour tags for this event (e.g. "open_position", "dip_buy",
// "take_profit", "stop_loss", "close_position", "accumulate",
// "transfer_in", "transfer_out").
// Matches GMGN `maker_token_tags` on the activity level.
    MakerEventTags *[]string`json:"makerEventTags,omitempty"`

// MakerExchange Entity / exchange name (e.g. "Binance"). Matches GMGN `exchange`.
    MakerExchange *string`json:"makerExchange,omitempty"`

// MakerName Specific address label (e.g. "Binance Hot Wallet 1"). Matches GMGN `maker_name`.
    MakerName *string`json:"makerName,omitempty"`

// MarketCapInUsd Market cap in USD at trade time
    MarketCapInUsd *string`json:"marketCapInUsd,omitempty"`

// PoolAddress Pool address
    PoolAddress string`json:"poolAddress"`

// PostBalance Token balance after this trade (token quantity).
// Matches GMGN `balance` in activity feed.
    PostBalance *string`json:"postBalance,omitempty"`

// PriorityFeeInNative EVM priority fee (fee_miner_reward ÷ 1e18) in native currency (ETH/BNB).
// Null on SOL (ETL does not yet provide compute-budget priority fee).
// Equals (effectiveGasPrice − baseFeePerGas) × gasUsed converted to native units.
    PriorityFeeInNative *string`json:"priorityFeeInNative,omitempty"`

// RealizedProfitInUsd Realized PnL for this specific trade in USD (non-zero only on Sell events).
// Matches GMGN `realized_profit`.
    RealizedProfitInUsd *string`json:"realizedProfitInUsd,omitempty"`

// SideTokenAddress Side token address
    SideTokenAddress string`json:"sideTokenAddress"`

// SideTokenAmount Side token amount
    SideTokenAmount string`json:"sideTokenAmount"`

// SideTokenAmountInNative Side token amount in native currency
    SideTokenAmountInNative string`json:"sideTokenAmountInNative"`

// SideTokenAmountInUsd Side token amount in USD
    SideTokenAmountInUsd string`json:"sideTokenAmountInUsd"`

// SideTokenImageUrl Side token image URL
    SideTokenImageUrl *string`json:"sideTokenImageUrl,omitempty"`

// SideTokenName Side token name
    SideTokenName string`json:"sideTokenName"`

// SideTokenPriceInNative Side token price in native currency
    SideTokenPriceInNative string`json:"sideTokenPriceInNative"`

// SideTokenPriceInUsd Side token price in USD
    SideTokenPriceInUsd string`json:"sideTokenPriceInUsd"`

// SideTokenSymbol Side token symbol
    SideTokenSymbol string`json:"sideTokenSymbol"`

// Status Transaction status
    Status string`json:"status"`

// TokenAddress Token address
    TokenAddress string`json:"tokenAddress"`

// TokenAmount Token amount
    TokenAmount string`json:"tokenAmount"`

// TokenAmountInNative Token amount in native currency
    TokenAmountInNative string`json:"tokenAmountInNative"`

// TokenAmountInUsd Token amount in USD
    TokenAmountInUsd string`json:"tokenAmountInUsd"`

// TokenImageUrl Token image URL
    TokenImageUrl *string`json:"tokenImageUrl,omitempty"`

// TokenName Token name
    TokenName string`json:"tokenName"`

// TokenPriceInNative Token price in native currency
    TokenPriceInNative string`json:"tokenPriceInNative"`

// TokenPriceInUsd Token price in USD
    TokenPriceInUsd string`json:"tokenPriceInUsd"`

// TokenSymbol Token symbol
    TokenSymbol string`json:"tokenSymbol"`

// TotalTrade Total historical trade count for this wallet on this token (buy + sell, up to and including this trade).
// Matches GMGN `total_trade`.
    TotalTrade *int64`json:"totalTrade,omitempty"`

// TraderTags Trader classification tags (e.g. "kol", "smart", "sniper", "dev", "fresh", "bundle", "bluechip", "insider")
    TraderTags *[]string`json:"traderTags,omitempty"`

// TransactionSignature Transaction signature
    TransactionSignature string`json:"transactionSignature"`

// Type Trade type (BUY/SELL)
    Type string`json:"type"`

// UnrealizedProfitInUsd Unrealized profit in USD at the moment of this trade:
// post_balance × token_price_in_usd − position_cost_in_usd.
// Only populated when PnL pipeline has processed the row and cost basis > 0.
// Matches GMGN `unrealized_profit`.
    UnrealizedProfitInUsd *string`json:"unrealizedProfitInUsd,omitempty"`
}`json:"data"`

// EndCursor Cursor for the end of current page
    EndCursor *string`json:"endCursor,omitempty"`

// HasNext Whether there is a next page
    HasNext *bool`json:"hasNext,omitempty"`

// HasPrev Whether there is a previous page
    HasPrev *bool`json:"hasPrev,omitempty"`

// StartCursor Cursor for the start of current page
    StartCursor *string`json:"startCursor,omitempty"`
}

// PageResponseTraderGainersLosersItem Generic pagination response
type PageResponseTraderGainersLosersItem  struct {
// Data Page data
    Data []struct {
// Address ENTITY.TRADER_GAINERS_LOSERS_ITEM.ADDRESS
    Address string`json:"address"`

// Chain ENTITY.TRADER_GAINERS_LOSERS_ITEM.CHAIN
    Chain string`json:"chain"`

// Pnl ENTITY.TRADER_GAINERS_LOSERS_ITEM.PNL
    Pnl string`json:"pnl"`

// TradeCount ENTITY.TRADER_GAINERS_LOSERS_ITEM.TRADE_COUNT
    TradeCount string`json:"tradeCount"`

// Volume ENTITY.TRADER_GAINERS_LOSERS_ITEM.VOLUME
    Volume string`json:"volume"`
}`json:"data"`

// EndCursor Cursor for the end of current page
    EndCursor *string`json:"endCursor,omitempty"`

// HasNext Whether there is a next page
    HasNext *bool`json:"hasNext,omitempty"`

// HasPrev Whether there is a previous page
    HasPrev *bool`json:"hasPrev,omitempty"`

// StartCursor Cursor for the start of current page
    StartCursor *string`json:"startCursor,omitempty"`
}

// SortDirection Sort direction (case-insensitive: accepts "asc"/"ASC"/"Asc" etc.)
type SortDirection  string

// TimeFrame Time frame for statistics
type TimeFrame  string

// TopTraderSortBy Sort field for top traders query
type TopTraderSortBy  string

// TradeType Trade type
type TradeType  string

// TraderPnlResolution Trader PnL resolution period
type TraderPnlResolution  string

// apiKeyAuthContextKey is the context key for api_key_auth security scheme
type apiKeyAuthContextKey  string

// bearerContextKey is the context key for bearer security scheme
type bearerContextKey  string

// bearerAuthContextKey is the context key for bearer_auth security scheme
type bearerAuthContextKey  string



// GetTradesParams defines parameters for GetTrades.
type GetTradesParams  struct {
// Cursor DTO.PAGE.CURSOR.DESCRIPTION
    Cursor *string`form:"cursor,omitempty" json:"cursor,omitempty"`

// Limit DTO.PAGE.LIMIT
    Limit *int64`form:"limit,omitempty" json:"limit,omitempty"`

// Direction DTO.PAGE.DIRECTION
    Direction *struct {
union json.RawMessage
}`form:"direction,omitempty" json:"direction,omitempty"`

// TokenAddress GLOBAL.TOKENADDRESS.DESCRIPTION
    TokenAddress *string`form:"tokenAddress,omitempty" json:"tokenAddress,omitempty"`

// WalletAddress GLOBAL.WALLETADDRESS.DESCRIPTION
    WalletAddress *string`form:"walletAddress,omitempty" json:"walletAddress,omitempty"`

// PoolAddress GLOBAL.POOLADDRESS.DESCRIPTION
    PoolAddress *string`form:"poolAddress,omitempty" json:"poolAddress,omitempty"`

// BeforeTimestamp DTO.TRADE.BEFORE_TIMESTAMP
    BeforeTimestamp *int64`form:"beforeTimestamp,omitempty" json:"beforeTimestamp,omitempty"`

// AfterTimestamp DTO.TRADE.AFTER_TIMESTAMP
    AfterTimestamp *int64`form:"afterTimestamp,omitempty" json:"afterTimestamp,omitempty"`

// BeforeBlockHeight DTO.TRADE.BEFORE_BLOCK_HEIGHT
    BeforeBlockHeight *int64`form:"beforeBlockHeight,omitempty" json:"beforeBlockHeight,omitempty"`

// AfterBlockHeight DTO.TRADE.AFTER_BLOCK_HEIGHT
    AfterBlockHeight *int64`form:"afterBlockHeight,omitempty" json:"afterBlockHeight,omitempty"`

// TransactionsSignature DTO.TRADE.TRANSACTIONS_SIGNATURE
    TransactionsSignature *string`form:"transactionsSignature,omitempty" json:"transactionsSignature,omitempty"`

// Type DTO.TRADE.TYPE
    Type *TradeType`form:"type,omitempty" json:"type,omitempty"`
}



// GetActivitiesParams defines parameters for GetActivities.
type GetActivitiesParams  struct {
// Cursor DTO.PAGE.CURSOR.DESCRIPTION
    Cursor *string`form:"cursor,omitempty" json:"cursor,omitempty"`

// Limit DTO.PAGE.LIMIT
    Limit *int64`form:"limit,omitempty" json:"limit,omitempty"`

// Direction DTO.PAGE.DIRECTION
    Direction *struct {
union json.RawMessage
}`form:"direction,omitempty" json:"direction,omitempty"`

// TokenAddress GLOBAL.TOKENADDRESS.DESCRIPTION
    TokenAddress *string`form:"tokenAddress,omitempty" json:"tokenAddress,omitempty"`

// WalletAddress GLOBAL.WALLETADDRESS.DESCRIPTION
    WalletAddress *string`form:"walletAddress,omitempty" json:"walletAddress,omitempty"`

// PoolAddress GLOBAL.POOLADDRESS.DESCRIPTION
    PoolAddress *string`form:"poolAddress,omitempty" json:"poolAddress,omitempty"`

// BeforeTimestamp DTO.TRADE.BEFORE_TIMESTAMP
    BeforeTimestamp *int64`form:"beforeTimestamp,omitempty" json:"beforeTimestamp,omitempty"`

// AfterTimestamp DTO.TRADE.AFTER_TIMESTAMP
    AfterTimestamp *int64`form:"afterTimestamp,omitempty" json:"afterTimestamp,omitempty"`

// BeforeBlockHeight DTO.TRADE.BEFORE_BLOCK_HEIGHT
    BeforeBlockHeight *int64`form:"beforeBlockHeight,omitempty" json:"beforeBlockHeight,omitempty"`

// AfterBlockHeight DTO.TRADE.AFTER_BLOCK_HEIGHT
    AfterBlockHeight *int64`form:"afterBlockHeight,omitempty" json:"afterBlockHeight,omitempty"`

// TransactionsSignature DTO.TRADE.TRANSACTIONS_SIGNATURE
    TransactionsSignature *string`form:"transactionsSignature,omitempty" json:"transactionsSignature,omitempty"`

// Type DTO.TRADE.ACTIVITY_TYPE
    Type *ActivityType`form:"type,omitempty" json:"type,omitempty"`

// SortBy DTO.TRADE.SORT_BY Sort by: timestampDesc (default) | timestampAsc | totalUsdDesc | totalUsdAsc.
// Legacy aliases: timestamp -> timestampDesc, totalUsd -> totalUsdDesc.
    SortBy *struct {
union json.RawMessage
}`form:"sortBy,omitempty" json:"sortBy,omitempty"`

// TraderTags Filter by trader tag(s). Comma-separated list from: kol, smart, sniper, dev, fresh, bundle, bluechip, insider.
// GMGN tags without existing activities data are unsupported: whale, top_holder, rat_trader, bot_degen, following, remarks.
// Returns activities where the trader has ANY of the specified tags.
    TraderTags *string`form:"traderTags,omitempty" json:"traderTags,omitempty"`

// MinAmountUsd Minimum trade value in USD (inclusive). Filters out small trades.
    MinAmountUsd *string`form:"minAmountUsd,omitempty" json:"minAmountUsd,omitempty"`

// MaxAmountUsd Maximum trade value in USD (inclusive).
    MaxAmountUsd *string`form:"maxAmountUsd,omitempty" json:"maxAmountUsd,omitempty"`

// Maker Filter by one maker (trader) wallet address. Equivalent to filtering by accountOwnerAddress.
    Maker *string`form:"maker,omitempty" json:"maker,omitempty"`
}



// GetTopTradersParams defines parameters for GetTopTraders.
type GetTopTradersParams  struct {
// Cursor DTO.PAGE.CURSOR.DESCRIPTION
    Cursor *string`form:"cursor,omitempty" json:"cursor,omitempty"`

// Limit DTO.PAGE.LIMIT
    Limit *int64`form:"limit,omitempty" json:"limit,omitempty"`

// Direction DTO.PAGE.DIRECTION
    Direction *struct {
union json.RawMessage
}`form:"direction,omitempty" json:"direction,omitempty"`

// TokenAddress GLOBAL.TOKENADDRESS.DESCRIPTION
    TokenAddress string`form:"tokenAddress" json:"tokenAddress"`

// TimeFrame DTO.TRADE.TIME_FRAME
    TimeFrame *TimeFrame`form:"timeFrame,omitempty" json:"timeFrame,omitempty"`

// SortType DTO.TRADE.SORT_TYPE
    SortType *struct {
union json.RawMessage
}`form:"sortType,omitempty" json:"sortType,omitempty"`

// SortBy DTO.TRADE.SORT_BY
    SortBy *struct {
union json.RawMessage
}`form:"sortBy,omitempty" json:"sortBy,omitempty"`
}



// GetTraderGainersLosersParams defines parameters for GetTraderGainersLosers.
type GetTraderGainersLosersParams  struct {
// Cursor DTO.PAGE.CURSOR.DESCRIPTION
    Cursor *string`form:"cursor,omitempty" json:"cursor,omitempty"`

// Limit DTO.PAGE.LIMIT
    Limit *int64`form:"limit,omitempty" json:"limit,omitempty"`

// Direction DTO.PAGE.DIRECTION
    Direction *struct {
union json.RawMessage
}`form:"direction,omitempty" json:"direction,omitempty"`

// Resolution DTO.TRADER.GAINERS_LOSERS.QUERY.RESOLUTION
    Resolution *struct {
union json.RawMessage
}`form:"resolution,omitempty" json:"resolution,omitempty"`

// SortType DTO.TRADER.GAINERS_LOSERS.QUERY.SORT_TYPE
    SortType *struct {
union json.RawMessage
}`form:"sortType,omitempty" json:"sortType,omitempty"`
}












// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
    // create a client with sane default values
    client := Client{
        Server: server,
    }
    // mutate client and add all optional params
    for _, o := range opts {
        if err := o(&client); err != nil {
            return nil, err
        }
    }
    // ensure the server URL always has a trailing slash
    if !strings.HasSuffix(client.Server, "/") {
        client.Server += "/"
    }
    // create httpClient, if not already present
    if client.Client == nil {
        client.Client = &http.Client{}
    }
    return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
// GetTrades request
    GetTrades(ctx context.Context, chain ChainSymbol, params *GetTradesParams, reqEditors... RequestEditorFn) (*http.Response, error)

// GetActivities request
    GetActivities(ctx context.Context, chain ChainSymbol, params *GetActivitiesParams, reqEditors... RequestEditorFn) (*http.Response, error)

// GetTopTraders request
    GetTopTraders(ctx context.Context, chain ChainSymbol, params *GetTopTradersParams, reqEditors... RequestEditorFn) (*http.Response, error)

// GetTraderGainersLosers request
    GetTraderGainersLosers(ctx context.Context, chain ChainSymbol, params *GetTraderGainersLosersParams, reqEditors... RequestEditorFn) (*http.Response, error)


}



func (c *Client) GetTrades(ctx context.Context, chain ChainSymbol, params *GetTradesParams, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewGetTradesRequest(c.Server, chain, params)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) GetActivities(ctx context.Context, chain ChainSymbol, params *GetActivitiesParams, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewGetActivitiesRequest(c.Server, chain, params)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) GetTopTraders(ctx context.Context, chain ChainSymbol, params *GetTopTradersParams, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewGetTopTradersRequest(c.Server, chain, params)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) GetTraderGainersLosers(ctx context.Context, chain ChainSymbol, params *GetTraderGainersLosersParams, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewGetTraderGainersLosersRequest(c.Server, chain, params)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}








// NewGetTradesRequest generates requests for GetTrades
func NewGetTradesRequest(server string, chain ChainSymbol, params *GetTradesParams) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/trade/%s", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    if params != nil {
        // queryValues collects non-styled parameters (passthrough, JSON)
        // that are safe to round-trip through url.Values.Encode().
        queryValues := queryURL.Query()
        // rawQueryFragments collects pre-encoded query fragments from
        // styled parameters, preserving literal commas as delimiters
        // per the OpenAPI spec (e.g. "color=blue,black,brown").
        var rawQueryFragments []string
            
             if params.Cursor != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Limit != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Direction != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "direction", *params.Direction, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.TokenAddress != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tokenAddress", *params.TokenAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.WalletAddress != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "walletAddress", *params.WalletAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.PoolAddress != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "poolAddress", *params.PoolAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.BeforeTimestamp != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "beforeTimestamp", *params.BeforeTimestamp, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.AfterTimestamp != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "afterTimestamp", *params.AfterTimestamp, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.BeforeBlockHeight != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "beforeBlockHeight", *params.BeforeBlockHeight, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.AfterBlockHeight != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "afterBlockHeight", *params.AfterBlockHeight, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.TransactionsSignature != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "transactionsSignature", *params.TransactionsSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Type != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
        if encoded := queryValues.Encode(); encoded != "" {
            rawQueryFragments = append(rawQueryFragments, encoded)
        }
        queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
    }

    req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
    if err != nil {
        return nil, err
    }

    



    return req, nil
}




// NewGetActivitiesRequest generates requests for GetActivities
func NewGetActivitiesRequest(server string, chain ChainSymbol, params *GetActivitiesParams) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/trade/%s/activities", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    if params != nil {
        // queryValues collects non-styled parameters (passthrough, JSON)
        // that are safe to round-trip through url.Values.Encode().
        queryValues := queryURL.Query()
        // rawQueryFragments collects pre-encoded query fragments from
        // styled parameters, preserving literal commas as delimiters
        // per the OpenAPI spec (e.g. "color=blue,black,brown").
        var rawQueryFragments []string
            
             if params.Cursor != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Limit != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Direction != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "direction", *params.Direction, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.TokenAddress != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tokenAddress", *params.TokenAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.WalletAddress != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "walletAddress", *params.WalletAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.PoolAddress != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "poolAddress", *params.PoolAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.BeforeTimestamp != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "beforeTimestamp", *params.BeforeTimestamp, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.AfterTimestamp != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "afterTimestamp", *params.AfterTimestamp, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.BeforeBlockHeight != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "beforeBlockHeight", *params.BeforeBlockHeight, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.AfterBlockHeight != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "afterBlockHeight", *params.AfterBlockHeight, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.TransactionsSignature != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "transactionsSignature", *params.TransactionsSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Type != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.SortBy != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sortBy", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.TraderTags != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "traderTags", *params.TraderTags, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.MinAmountUsd != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "minAmountUsd", *params.MinAmountUsd, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.MaxAmountUsd != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "maxAmountUsd", *params.MaxAmountUsd, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Maker != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "maker", *params.Maker, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
        if encoded := queryValues.Encode(); encoded != "" {
            rawQueryFragments = append(rawQueryFragments, encoded)
        }
        queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
    }

    req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
    if err != nil {
        return nil, err
    }

    



    return req, nil
}




// NewGetTopTradersRequest generates requests for GetTopTraders
func NewGetTopTradersRequest(server string, chain ChainSymbol, params *GetTopTradersParams) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/trade/%s/top-traders", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    if params != nil {
        // queryValues collects non-styled parameters (passthrough, JSON)
        // that are safe to round-trip through url.Values.Encode().
        queryValues := queryURL.Query()
        // rawQueryFragments collects pre-encoded query fragments from
        // styled parameters, preserving literal commas as delimiters
        // per the OpenAPI spec (e.g. "color=blue,black,brown").
        var rawQueryFragments []string
            
             if params.Cursor != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Limit != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Direction != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "direction", *params.Direction, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
            
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tokenAddress", params.TokenAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            
        
             if params.TimeFrame != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "timeFrame", *params.TimeFrame, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.SortType != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sortType", *params.SortType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.SortBy != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sortBy", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
        if encoded := queryValues.Encode(); encoded != "" {
            rawQueryFragments = append(rawQueryFragments, encoded)
        }
        queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
    }

    req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
    if err != nil {
        return nil, err
    }

    



    return req, nil
}




// NewGetTraderGainersLosersRequest generates requests for GetTraderGainersLosers
func NewGetTraderGainersLosersRequest(server string, chain ChainSymbol, params *GetTraderGainersLosersParams) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/trade/%s/trader-gainers-losers", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    if params != nil {
        // queryValues collects non-styled parameters (passthrough, JSON)
        // that are safe to round-trip through url.Values.Encode().
        queryValues := queryURL.Query()
        // rawQueryFragments collects pre-encoded query fragments from
        // styled parameters, preserving literal commas as delimiters
        // per the OpenAPI spec (e.g. "color=blue,black,brown").
        var rawQueryFragments []string
            
             if params.Cursor != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Limit != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Direction != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "direction", *params.Direction, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Resolution != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "resolution", *params.Resolution, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.SortType != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sortType", *params.SortType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
        if encoded := queryValues.Encode(); encoded != "" {
            rawQueryFragments = append(rawQueryFragments, encoded)
        }
        queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
    }

    req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
    if err != nil {
        return nil, err
    }

    



    return req, nil
}



func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
    for _, r := range c.RequestEditors {
        if err := r(ctx, req); err != nil {
            return err
        }
    }
    for _, r := range additionalEditors {
        if err := r(ctx, req); err != nil {
            return err
        }
    }
    return nil
}
// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
    ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
    client, err := NewClient(server, opts...)
    if err != nil {
        return nil, err
    }
    return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
// GetTradesWithResponse request
    GetTradesWithResponse(ctx context.Context, chain ChainSymbol, params *GetTradesParams, reqEditors... RequestEditorFn) (*GetTradesResponse, error)

// GetActivitiesWithResponse request
    GetActivitiesWithResponse(ctx context.Context, chain ChainSymbol, params *GetActivitiesParams, reqEditors... RequestEditorFn) (*GetActivitiesResponse, error)

// GetTopTradersWithResponse request
    GetTopTradersWithResponse(ctx context.Context, chain ChainSymbol, params *GetTopTradersParams, reqEditors... RequestEditorFn) (*GetTopTradersResponse, error)

// GetTraderGainersLosersWithResponse request
    GetTraderGainersLosersWithResponse(ctx context.Context, chain ChainSymbol, params *GetTraderGainersLosersParams, reqEditors... RequestEditorFn) (*GetTraderGainersLosersResponse, error)


}



type GetTradesResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *PageResponseTradeDetail
}

// Status returns HTTPResponse.Status
func (r GetTradesResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTradesResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTradesResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}




type GetActivitiesResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *PageResponseTradeDetail
}

// Status returns HTTPResponse.Status
func (r GetActivitiesResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetActivitiesResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetActivitiesResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}




type GetTopTradersResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *PageResponseTopTrader
}

// Status returns HTTPResponse.Status
func (r GetTopTradersResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTopTradersResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTopTradersResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}




type GetTraderGainersLosersResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *PageResponseTraderGainersLosersItem
}

// Status returns HTTPResponse.Status
func (r GetTraderGainersLosersResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTraderGainersLosersResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTraderGainersLosersResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}








// GetTradesWithResponse request returning *GetTradesResponse
func (c *ClientWithResponses) GetTradesWithResponse(ctx context.Context, chain ChainSymbol, params *GetTradesParams, reqEditors... RequestEditorFn) (*GetTradesResponse, error){
    rsp, err := c.GetTrades(ctx, chain, params, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseGetTradesResponse(rsp)
}






// GetActivitiesWithResponse request returning *GetActivitiesResponse
func (c *ClientWithResponses) GetActivitiesWithResponse(ctx context.Context, chain ChainSymbol, params *GetActivitiesParams, reqEditors... RequestEditorFn) (*GetActivitiesResponse, error){
    rsp, err := c.GetActivities(ctx, chain, params, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseGetActivitiesResponse(rsp)
}






// GetTopTradersWithResponse request returning *GetTopTradersResponse
func (c *ClientWithResponses) GetTopTradersWithResponse(ctx context.Context, chain ChainSymbol, params *GetTopTradersParams, reqEditors... RequestEditorFn) (*GetTopTradersResponse, error){
    rsp, err := c.GetTopTraders(ctx, chain, params, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseGetTopTradersResponse(rsp)
}






// GetTraderGainersLosersWithResponse request returning *GetTraderGainersLosersResponse
func (c *ClientWithResponses) GetTraderGainersLosersWithResponse(ctx context.Context, chain ChainSymbol, params *GetTraderGainersLosersParams, reqEditors... RequestEditorFn) (*GetTraderGainersLosersResponse, error){
    rsp, err := c.GetTraderGainersLosers(ctx, chain, params, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseGetTraderGainersLosersResponse(rsp)
}








// ParseGetTradesResponse parses an HTTP response from a GetTradesWithResponse call
func ParseGetTradesResponse(rsp *http.Response) (*GetTradesResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &GetTradesResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest PageResponseTradeDetail
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}


// ParseGetActivitiesResponse parses an HTTP response from a GetActivitiesWithResponse call
func ParseGetActivitiesResponse(rsp *http.Response) (*GetActivitiesResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &GetActivitiesResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest PageResponseTradeDetail
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}


// ParseGetTopTradersResponse parses an HTTP response from a GetTopTradersWithResponse call
func ParseGetTopTradersResponse(rsp *http.Response) (*GetTopTradersResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &GetTopTradersResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest PageResponseTopTrader
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}


// ParseGetTraderGainersLosersResponse parses an HTTP response from a GetTraderGainersLosersWithResponse call
func ParseGetTraderGainersLosersResponse(rsp *http.Response) (*GetTraderGainersLosersResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &GetTraderGainersLosersResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest PageResponseTraderGainersLosersItem
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}

