/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KYTRegisterWithdrawalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KYTRegisterWithdrawalRequest{}

// KYTRegisterWithdrawalRequest struct for KYTRegisterWithdrawalRequest
type KYTRegisterWithdrawalRequest struct {
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.NETWORK
	Network string `json:"network"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.ASSET
	Asset string `json:"asset"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.ADDRESS
	Address string `json:"address"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.ASSET_AMOUNT
	AssetAmount string `json:"assetAmount"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.ATTEMPT_TIMESTAMP
	AttemptTimestamp string `json:"attemptTimestamp"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.ASSET_PRICE
	AssetPrice *string `json:"assetPrice,omitempty"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.ASSET_DENOMINATION
	AssetDenomination *string `json:"assetDenomination,omitempty"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.ASSET_ID
	AssetId *string `json:"assetId,omitempty"`
	// DTO.KYT.KYT_REGISTER_WITHDRAWAL_REQUEST.MEMO
	Memo *string `json:"memo,omitempty"`
}

type _KYTRegisterWithdrawalRequest KYTRegisterWithdrawalRequest

// NewKYTRegisterWithdrawalRequest instantiates a new KYTRegisterWithdrawalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKYTRegisterWithdrawalRequest(network string, asset string, address string, assetAmount string, attemptTimestamp string) *KYTRegisterWithdrawalRequest {
	this := KYTRegisterWithdrawalRequest{}
	this.Network = network
	this.Asset = asset
	this.Address = address
	this.AssetAmount = assetAmount
	this.AttemptTimestamp = attemptTimestamp
	return &this
}

// NewKYTRegisterWithdrawalRequestWithDefaults instantiates a new KYTRegisterWithdrawalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKYTRegisterWithdrawalRequestWithDefaults() *KYTRegisterWithdrawalRequest {
	this := KYTRegisterWithdrawalRequest{}
	return &this
}

// GetNetwork returns the Network field value
func (o *KYTRegisterWithdrawalRequest) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *KYTRegisterWithdrawalRequest) SetNetwork(v string) {
	o.Network = v
}

// GetAsset returns the Asset field value
func (o *KYTRegisterWithdrawalRequest) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *KYTRegisterWithdrawalRequest) SetAsset(v string) {
	o.Asset = v
}

// GetAddress returns the Address field value
func (o *KYTRegisterWithdrawalRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *KYTRegisterWithdrawalRequest) SetAddress(v string) {
	o.Address = v
}

// GetAssetAmount returns the AssetAmount field value
func (o *KYTRegisterWithdrawalRequest) GetAssetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetAmount
}

// GetAssetAmountOk returns a tuple with the AssetAmount field value
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetAssetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetAmount, true
}

// SetAssetAmount sets field value
func (o *KYTRegisterWithdrawalRequest) SetAssetAmount(v string) {
	o.AssetAmount = v
}

// GetAttemptTimestamp returns the AttemptTimestamp field value
func (o *KYTRegisterWithdrawalRequest) GetAttemptTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttemptTimestamp
}

// GetAttemptTimestampOk returns a tuple with the AttemptTimestamp field value
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetAttemptTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptTimestamp, true
}

// SetAttemptTimestamp sets field value
func (o *KYTRegisterWithdrawalRequest) SetAttemptTimestamp(v string) {
	o.AttemptTimestamp = v
}

// GetAssetPrice returns the AssetPrice field value if set, zero value otherwise.
func (o *KYTRegisterWithdrawalRequest) GetAssetPrice() string {
	if o == nil || IsNil(o.AssetPrice) {
		var ret string
		return ret
	}
	return *o.AssetPrice
}

// GetAssetPriceOk returns a tuple with the AssetPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetAssetPriceOk() (*string, bool) {
	if o == nil || IsNil(o.AssetPrice) {
		return nil, false
	}
	return o.AssetPrice, true
}

// HasAssetPrice returns a boolean if a field has been set.
func (o *KYTRegisterWithdrawalRequest) HasAssetPrice() bool {
	if o != nil && !IsNil(o.AssetPrice) {
		return true
	}

	return false
}

// SetAssetPrice gets a reference to the given string and assigns it to the AssetPrice field.
func (o *KYTRegisterWithdrawalRequest) SetAssetPrice(v string) {
	o.AssetPrice = &v
}

// GetAssetDenomination returns the AssetDenomination field value if set, zero value otherwise.
func (o *KYTRegisterWithdrawalRequest) GetAssetDenomination() string {
	if o == nil || IsNil(o.AssetDenomination) {
		var ret string
		return ret
	}
	return *o.AssetDenomination
}

// GetAssetDenominationOk returns a tuple with the AssetDenomination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetAssetDenominationOk() (*string, bool) {
	if o == nil || IsNil(o.AssetDenomination) {
		return nil, false
	}
	return o.AssetDenomination, true
}

// HasAssetDenomination returns a boolean if a field has been set.
func (o *KYTRegisterWithdrawalRequest) HasAssetDenomination() bool {
	if o != nil && !IsNil(o.AssetDenomination) {
		return true
	}

	return false
}

// SetAssetDenomination gets a reference to the given string and assigns it to the AssetDenomination field.
func (o *KYTRegisterWithdrawalRequest) SetAssetDenomination(v string) {
	o.AssetDenomination = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *KYTRegisterWithdrawalRequest) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *KYTRegisterWithdrawalRequest) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *KYTRegisterWithdrawalRequest) SetAssetId(v string) {
	o.AssetId = &v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *KYTRegisterWithdrawalRequest) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KYTRegisterWithdrawalRequest) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *KYTRegisterWithdrawalRequest) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *KYTRegisterWithdrawalRequest) SetMemo(v string) {
	o.Memo = &v
}

func (o KYTRegisterWithdrawalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KYTRegisterWithdrawalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	toSerialize["asset"] = o.Asset
	toSerialize["address"] = o.Address
	toSerialize["assetAmount"] = o.AssetAmount
	toSerialize["attemptTimestamp"] = o.AttemptTimestamp
	if !IsNil(o.AssetPrice) {
		toSerialize["assetPrice"] = o.AssetPrice
	}
	if !IsNil(o.AssetDenomination) {
		toSerialize["assetDenomination"] = o.AssetDenomination
	}
	if !IsNil(o.AssetId) {
		toSerialize["assetId"] = o.AssetId
	}
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}
	return toSerialize, nil
}

func (o *KYTRegisterWithdrawalRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
		"asset",
		"address",
		"assetAmount",
		"attemptTimestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKYTRegisterWithdrawalRequest := _KYTRegisterWithdrawalRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKYTRegisterWithdrawalRequest)

	if err != nil {
		return err
	}

	*o = KYTRegisterWithdrawalRequest(varKYTRegisterWithdrawalRequest)

	return err
}

type NullableKYTRegisterWithdrawalRequest struct {
	value *KYTRegisterWithdrawalRequest
	isSet bool
}

func (v NullableKYTRegisterWithdrawalRequest) Get() *KYTRegisterWithdrawalRequest {
	return v.value
}

func (v *NullableKYTRegisterWithdrawalRequest) Set(val *KYTRegisterWithdrawalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKYTRegisterWithdrawalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKYTRegisterWithdrawalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKYTRegisterWithdrawalRequest(val *KYTRegisterWithdrawalRequest) *NullableKYTRegisterWithdrawalRequest {
	return &NullableKYTRegisterWithdrawalRequest{value: val, isSet: true}
}

func (v NullableKYTRegisterWithdrawalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKYTRegisterWithdrawalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

