/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QuoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteResponse{}

// QuoteResponse struct for QuoteResponse
type QuoteResponse struct {
	// DTO.DEX.QUOTE.AMOUNT_OUT
	AmountOut *string `json:"amountOut,omitempty"`
	// DTO.DEX.QUOTE.MIN_AMOUNT_OUT
	MinAmountOut *string `json:"minAmountOut,omitempty"`
	// DTO.DEX.QUOTE.CURRENT_PRICE
	CurrentPrice *string `json:"currentPrice,omitempty"`
	// DTO.DEX.QUOTE.EXECUTION_PRICE
	ExecutionPrice *string `json:"executionPrice,omitempty"`
	// DTO.DEX.QUOTE.PRICE_IMPACT
	PriceImpact *string `json:"priceImpact,omitempty"`
	// DTO.DEX.QUOTE.FEE
	Fee *string `json:"fee,omitempty"`
}

// NewQuoteResponse instantiates a new QuoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteResponse() *QuoteResponse {
	this := QuoteResponse{}
	return &this
}

// NewQuoteResponseWithDefaults instantiates a new QuoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteResponseWithDefaults() *QuoteResponse {
	this := QuoteResponse{}
	return &this
}

// GetAmountOut returns the AmountOut field value if set, zero value otherwise.
func (o *QuoteResponse) GetAmountOut() string {
	if o == nil || IsNil(o.AmountOut) {
		var ret string
		return ret
	}
	return *o.AmountOut
}

// GetAmountOutOk returns a tuple with the AmountOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteResponse) GetAmountOutOk() (*string, bool) {
	if o == nil || IsNil(o.AmountOut) {
		return nil, false
	}
	return o.AmountOut, true
}

// HasAmountOut returns a boolean if a field has been set.
func (o *QuoteResponse) HasAmountOut() bool {
	if o != nil && !IsNil(o.AmountOut) {
		return true
	}

	return false
}

// SetAmountOut gets a reference to the given string and assigns it to the AmountOut field.
func (o *QuoteResponse) SetAmountOut(v string) {
	o.AmountOut = &v
}

// GetMinAmountOut returns the MinAmountOut field value if set, zero value otherwise.
func (o *QuoteResponse) GetMinAmountOut() string {
	if o == nil || IsNil(o.MinAmountOut) {
		var ret string
		return ret
	}
	return *o.MinAmountOut
}

// GetMinAmountOutOk returns a tuple with the MinAmountOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteResponse) GetMinAmountOutOk() (*string, bool) {
	if o == nil || IsNil(o.MinAmountOut) {
		return nil, false
	}
	return o.MinAmountOut, true
}

// HasMinAmountOut returns a boolean if a field has been set.
func (o *QuoteResponse) HasMinAmountOut() bool {
	if o != nil && !IsNil(o.MinAmountOut) {
		return true
	}

	return false
}

// SetMinAmountOut gets a reference to the given string and assigns it to the MinAmountOut field.
func (o *QuoteResponse) SetMinAmountOut(v string) {
	o.MinAmountOut = &v
}

// GetCurrentPrice returns the CurrentPrice field value if set, zero value otherwise.
func (o *QuoteResponse) GetCurrentPrice() string {
	if o == nil || IsNil(o.CurrentPrice) {
		var ret string
		return ret
	}
	return *o.CurrentPrice
}

// GetCurrentPriceOk returns a tuple with the CurrentPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteResponse) GetCurrentPriceOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentPrice) {
		return nil, false
	}
	return o.CurrentPrice, true
}

// HasCurrentPrice returns a boolean if a field has been set.
func (o *QuoteResponse) HasCurrentPrice() bool {
	if o != nil && !IsNil(o.CurrentPrice) {
		return true
	}

	return false
}

// SetCurrentPrice gets a reference to the given string and assigns it to the CurrentPrice field.
func (o *QuoteResponse) SetCurrentPrice(v string) {
	o.CurrentPrice = &v
}

// GetExecutionPrice returns the ExecutionPrice field value if set, zero value otherwise.
func (o *QuoteResponse) GetExecutionPrice() string {
	if o == nil || IsNil(o.ExecutionPrice) {
		var ret string
		return ret
	}
	return *o.ExecutionPrice
}

// GetExecutionPriceOk returns a tuple with the ExecutionPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteResponse) GetExecutionPriceOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutionPrice) {
		return nil, false
	}
	return o.ExecutionPrice, true
}

// HasExecutionPrice returns a boolean if a field has been set.
func (o *QuoteResponse) HasExecutionPrice() bool {
	if o != nil && !IsNil(o.ExecutionPrice) {
		return true
	}

	return false
}

// SetExecutionPrice gets a reference to the given string and assigns it to the ExecutionPrice field.
func (o *QuoteResponse) SetExecutionPrice(v string) {
	o.ExecutionPrice = &v
}

// GetPriceImpact returns the PriceImpact field value if set, zero value otherwise.
func (o *QuoteResponse) GetPriceImpact() string {
	if o == nil || IsNil(o.PriceImpact) {
		var ret string
		return ret
	}
	return *o.PriceImpact
}

// GetPriceImpactOk returns a tuple with the PriceImpact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteResponse) GetPriceImpactOk() (*string, bool) {
	if o == nil || IsNil(o.PriceImpact) {
		return nil, false
	}
	return o.PriceImpact, true
}

// HasPriceImpact returns a boolean if a field has been set.
func (o *QuoteResponse) HasPriceImpact() bool {
	if o != nil && !IsNil(o.PriceImpact) {
		return true
	}

	return false
}

// SetPriceImpact gets a reference to the given string and assigns it to the PriceImpact field.
func (o *QuoteResponse) SetPriceImpact(v string) {
	o.PriceImpact = &v
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *QuoteResponse) GetFee() string {
	if o == nil || IsNil(o.Fee) {
		var ret string
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteResponse) GetFeeOk() (*string, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *QuoteResponse) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given string and assigns it to the Fee field.
func (o *QuoteResponse) SetFee(v string) {
	o.Fee = &v
}

func (o QuoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AmountOut) {
		toSerialize["amountOut"] = o.AmountOut
	}
	if !IsNil(o.MinAmountOut) {
		toSerialize["minAmountOut"] = o.MinAmountOut
	}
	if !IsNil(o.CurrentPrice) {
		toSerialize["currentPrice"] = o.CurrentPrice
	}
	if !IsNil(o.ExecutionPrice) {
		toSerialize["executionPrice"] = o.ExecutionPrice
	}
	if !IsNil(o.PriceImpact) {
		toSerialize["priceImpact"] = o.PriceImpact
	}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	return toSerialize, nil
}

type NullableQuoteResponse struct {
	value *QuoteResponse
	isSet bool
}

func (v NullableQuoteResponse) Get() *QuoteResponse {
	return v.value
}

func (v *NullableQuoteResponse) Set(val *QuoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteResponse(val *QuoteResponse) *NullableQuoteResponse {
	return &NullableQuoteResponse{value: val, isSet: true}
}

func (v NullableQuoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

