/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Token type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Token{}

// Token struct for Token
type Token struct {
	// DTO.TOKEN.METADATA.CHAIN
	Chain string `json:"chain"`
	// DTO.TOKEN.METADATA.DECIMALS
	Decimals int64 `json:"decimals"`
	// DTO.TOKEN.METADATA.NAME
	Name string `json:"name"`
	// DTO.TOKEN.METADATA.SYMBOL
	Symbol string `json:"symbol"`
	// DTO.TOKEN.METADATA.METADATA_ADDRESS
	MetadataAddress *string `json:"metadataAddress,omitempty"`
	// DTO.TOKEN.METADATA.ADDRESS
	Address string `json:"address"`
	// DTO.TOKEN.METADATA.TOKEN_CREATORS
	TokenCreators []TokenCreatorsDTO `json:"tokenCreators,omitempty"`
	// DTO.TOKEN.METADATA.IMAGE_URL
	ImageUrl *string `json:"imageUrl,omitempty"`
	// DTO.TOKEN.METADATA.URI
	Uri *string `json:"uri,omitempty"`
	// DTO.TOKEN.METADATA.EXTRA
	Extra *TokenExtraDTO `json:"extra,omitempty"`
	// DTO.TOKEN.METADATA.SOCIAL_MEDIAS
	SocialMedias *TokenSocialMediasDTO `json:"socialMedias,omitempty"`
	// DTO.TOKEN.METADATA.TOKEN_CREATED_AT
	TokenCreatedAt *int64 `json:"tokenCreatedAt,omitempty"`
	// DTO.TOKEN.METADATA.DESCRIPTION
	Description *string `json:"description,omitempty"`
	// DTO.TOKEN.METADATA.DEV_TOTAL_TOKENS
	DevTotalTokens *string `json:"devTotalTokens,omitempty"`
	// DTO.TOKEN.METADATA.DEV_LAST_TOKEN_CREATED_AT
	DevLastTokenCreatedAt *string `json:"devLastTokenCreatedAt,omitempty"`
	// DTO.TOKEN.MARKET_ID
	Market *string `json:"market,omitempty"`
	// DTO.TOKEN.EXTENSION
	Extension map[string]interface{} `json:"extension,omitempty"`
	// DTO.TOKEN.STATS
	Stats *TokenStat `json:"stats,omitempty"`
	// DTO.TOKEN.LIQUIDITY
	Liquidity []DexPoolDTO `json:"liquidity,omitempty"`
	// DTO.TOKEN.MARKET_CAP_INFO
	MarketData TokenMarketData `json:"marketData"`
}

type _Token Token

// NewToken instantiates a new Token object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToken(chain string, decimals int64, name string, symbol string, address string, marketData TokenMarketData) *Token {
	this := Token{}
	this.Chain = chain
	this.Decimals = decimals
	this.Name = name
	this.Symbol = symbol
	this.Address = address
	this.MarketData = marketData
	return &this
}

// NewTokenWithDefaults instantiates a new Token object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenWithDefaults() *Token {
	this := Token{}
	return &this
}

// GetChain returns the Chain field value
func (o *Token) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *Token) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *Token) SetChain(v string) {
	o.Chain = v
}

// GetDecimals returns the Decimals field value
func (o *Token) GetDecimals() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *Token) GetDecimalsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *Token) SetDecimals(v int64) {
	o.Decimals = v
}

// GetName returns the Name field value
func (o *Token) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Token) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Token) SetName(v string) {
	o.Name = v
}

// GetSymbol returns the Symbol field value
func (o *Token) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *Token) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *Token) SetSymbol(v string) {
	o.Symbol = v
}

// GetMetadataAddress returns the MetadataAddress field value if set, zero value otherwise.
func (o *Token) GetMetadataAddress() string {
	if o == nil || IsNil(o.MetadataAddress) {
		var ret string
		return ret
	}
	return *o.MetadataAddress
}

// GetMetadataAddressOk returns a tuple with the MetadataAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetMetadataAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MetadataAddress) {
		return nil, false
	}
	return o.MetadataAddress, true
}

// HasMetadataAddress returns a boolean if a field has been set.
func (o *Token) HasMetadataAddress() bool {
	if o != nil && !IsNil(o.MetadataAddress) {
		return true
	}

	return false
}

// SetMetadataAddress gets a reference to the given string and assigns it to the MetadataAddress field.
func (o *Token) SetMetadataAddress(v string) {
	o.MetadataAddress = &v
}

// GetAddress returns the Address field value
func (o *Token) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Token) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Token) SetAddress(v string) {
	o.Address = v
}

// GetTokenCreators returns the TokenCreators field value if set, zero value otherwise.
func (o *Token) GetTokenCreators() []TokenCreatorsDTO {
	if o == nil || IsNil(o.TokenCreators) {
		var ret []TokenCreatorsDTO
		return ret
	}
	return o.TokenCreators
}

// GetTokenCreatorsOk returns a tuple with the TokenCreators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetTokenCreatorsOk() ([]TokenCreatorsDTO, bool) {
	if o == nil || IsNil(o.TokenCreators) {
		return nil, false
	}
	return o.TokenCreators, true
}

// HasTokenCreators returns a boolean if a field has been set.
func (o *Token) HasTokenCreators() bool {
	if o != nil && !IsNil(o.TokenCreators) {
		return true
	}

	return false
}

// SetTokenCreators gets a reference to the given []TokenCreatorsDTO and assigns it to the TokenCreators field.
func (o *Token) SetTokenCreators(v []TokenCreatorsDTO) {
	o.TokenCreators = v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *Token) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *Token) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *Token) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *Token) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *Token) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *Token) SetUri(v string) {
	o.Uri = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *Token) GetExtra() TokenExtraDTO {
	if o == nil || IsNil(o.Extra) {
		var ret TokenExtraDTO
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetExtraOk() (*TokenExtraDTO, bool) {
	if o == nil || IsNil(o.Extra) {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *Token) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given TokenExtraDTO and assigns it to the Extra field.
func (o *Token) SetExtra(v TokenExtraDTO) {
	o.Extra = &v
}

// GetSocialMedias returns the SocialMedias field value if set, zero value otherwise.
func (o *Token) GetSocialMedias() TokenSocialMediasDTO {
	if o == nil || IsNil(o.SocialMedias) {
		var ret TokenSocialMediasDTO
		return ret
	}
	return *o.SocialMedias
}

// GetSocialMediasOk returns a tuple with the SocialMedias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetSocialMediasOk() (*TokenSocialMediasDTO, bool) {
	if o == nil || IsNil(o.SocialMedias) {
		return nil, false
	}
	return o.SocialMedias, true
}

// HasSocialMedias returns a boolean if a field has been set.
func (o *Token) HasSocialMedias() bool {
	if o != nil && !IsNil(o.SocialMedias) {
		return true
	}

	return false
}

// SetSocialMedias gets a reference to the given TokenSocialMediasDTO and assigns it to the SocialMedias field.
func (o *Token) SetSocialMedias(v TokenSocialMediasDTO) {
	o.SocialMedias = &v
}

// GetTokenCreatedAt returns the TokenCreatedAt field value if set, zero value otherwise.
func (o *Token) GetTokenCreatedAt() int64 {
	if o == nil || IsNil(o.TokenCreatedAt) {
		var ret int64
		return ret
	}
	return *o.TokenCreatedAt
}

// GetTokenCreatedAtOk returns a tuple with the TokenCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetTokenCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.TokenCreatedAt) {
		return nil, false
	}
	return o.TokenCreatedAt, true
}

// HasTokenCreatedAt returns a boolean if a field has been set.
func (o *Token) HasTokenCreatedAt() bool {
	if o != nil && !IsNil(o.TokenCreatedAt) {
		return true
	}

	return false
}

// SetTokenCreatedAt gets a reference to the given int64 and assigns it to the TokenCreatedAt field.
func (o *Token) SetTokenCreatedAt(v int64) {
	o.TokenCreatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Token) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Token) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Token) SetDescription(v string) {
	o.Description = &v
}

// GetDevTotalTokens returns the DevTotalTokens field value if set, zero value otherwise.
func (o *Token) GetDevTotalTokens() string {
	if o == nil || IsNil(o.DevTotalTokens) {
		var ret string
		return ret
	}
	return *o.DevTotalTokens
}

// GetDevTotalTokensOk returns a tuple with the DevTotalTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetDevTotalTokensOk() (*string, bool) {
	if o == nil || IsNil(o.DevTotalTokens) {
		return nil, false
	}
	return o.DevTotalTokens, true
}

// HasDevTotalTokens returns a boolean if a field has been set.
func (o *Token) HasDevTotalTokens() bool {
	if o != nil && !IsNil(o.DevTotalTokens) {
		return true
	}

	return false
}

// SetDevTotalTokens gets a reference to the given string and assigns it to the DevTotalTokens field.
func (o *Token) SetDevTotalTokens(v string) {
	o.DevTotalTokens = &v
}

// GetDevLastTokenCreatedAt returns the DevLastTokenCreatedAt field value if set, zero value otherwise.
func (o *Token) GetDevLastTokenCreatedAt() string {
	if o == nil || IsNil(o.DevLastTokenCreatedAt) {
		var ret string
		return ret
	}
	return *o.DevLastTokenCreatedAt
}

// GetDevLastTokenCreatedAtOk returns a tuple with the DevLastTokenCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetDevLastTokenCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.DevLastTokenCreatedAt) {
		return nil, false
	}
	return o.DevLastTokenCreatedAt, true
}

// HasDevLastTokenCreatedAt returns a boolean if a field has been set.
func (o *Token) HasDevLastTokenCreatedAt() bool {
	if o != nil && !IsNil(o.DevLastTokenCreatedAt) {
		return true
	}

	return false
}

// SetDevLastTokenCreatedAt gets a reference to the given string and assigns it to the DevLastTokenCreatedAt field.
func (o *Token) SetDevLastTokenCreatedAt(v string) {
	o.DevLastTokenCreatedAt = &v
}

// GetMarket returns the Market field value if set, zero value otherwise.
func (o *Token) GetMarket() string {
	if o == nil || IsNil(o.Market) {
		var ret string
		return ret
	}
	return *o.Market
}

// GetMarketOk returns a tuple with the Market field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetMarketOk() (*string, bool) {
	if o == nil || IsNil(o.Market) {
		return nil, false
	}
	return o.Market, true
}

// HasMarket returns a boolean if a field has been set.
func (o *Token) HasMarket() bool {
	if o != nil && !IsNil(o.Market) {
		return true
	}

	return false
}

// SetMarket gets a reference to the given string and assigns it to the Market field.
func (o *Token) SetMarket(v string) {
	o.Market = &v
}

// GetExtension returns the Extension field value if set, zero value otherwise.
func (o *Token) GetExtension() map[string]interface{} {
	if o == nil || IsNil(o.Extension) {
		var ret map[string]interface{}
		return ret
	}
	return o.Extension
}

// GetExtensionOk returns a tuple with the Extension field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetExtensionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Extension) {
		return map[string]interface{}{}, false
	}
	return o.Extension, true
}

// HasExtension returns a boolean if a field has been set.
func (o *Token) HasExtension() bool {
	if o != nil && !IsNil(o.Extension) {
		return true
	}

	return false
}

// SetExtension gets a reference to the given map[string]interface{} and assigns it to the Extension field.
func (o *Token) SetExtension(v map[string]interface{}) {
	o.Extension = v
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *Token) GetStats() TokenStat {
	if o == nil || IsNil(o.Stats) {
		var ret TokenStat
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetStatsOk() (*TokenStat, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *Token) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given TokenStat and assigns it to the Stats field.
func (o *Token) SetStats(v TokenStat) {
	o.Stats = &v
}

// GetLiquidity returns the Liquidity field value if set, zero value otherwise.
func (o *Token) GetLiquidity() []DexPoolDTO {
	if o == nil || IsNil(o.Liquidity) {
		var ret []DexPoolDTO
		return ret
	}
	return o.Liquidity
}

// GetLiquidityOk returns a tuple with the Liquidity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetLiquidityOk() ([]DexPoolDTO, bool) {
	if o == nil || IsNil(o.Liquidity) {
		return nil, false
	}
	return o.Liquidity, true
}

// HasLiquidity returns a boolean if a field has been set.
func (o *Token) HasLiquidity() bool {
	if o != nil && !IsNil(o.Liquidity) {
		return true
	}

	return false
}

// SetLiquidity gets a reference to the given []DexPoolDTO and assigns it to the Liquidity field.
func (o *Token) SetLiquidity(v []DexPoolDTO) {
	o.Liquidity = v
}

// GetMarketData returns the MarketData field value
func (o *Token) GetMarketData() TokenMarketData {
	if o == nil {
		var ret TokenMarketData
		return ret
	}

	return o.MarketData
}

// GetMarketDataOk returns a tuple with the MarketData field value
// and a boolean to check if the value has been set.
func (o *Token) GetMarketDataOk() (*TokenMarketData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarketData, true
}

// SetMarketData sets field value
func (o *Token) SetMarketData(v TokenMarketData) {
	o.MarketData = v
}

func (o Token) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Token) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["decimals"] = o.Decimals
	toSerialize["name"] = o.Name
	toSerialize["symbol"] = o.Symbol
	if !IsNil(o.MetadataAddress) {
		toSerialize["metadataAddress"] = o.MetadataAddress
	}
	toSerialize["address"] = o.Address
	if !IsNil(o.TokenCreators) {
		toSerialize["tokenCreators"] = o.TokenCreators
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["imageUrl"] = o.ImageUrl
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	if !IsNil(o.Extra) {
		toSerialize["extra"] = o.Extra
	}
	if !IsNil(o.SocialMedias) {
		toSerialize["socialMedias"] = o.SocialMedias
	}
	if !IsNil(o.TokenCreatedAt) {
		toSerialize["tokenCreatedAt"] = o.TokenCreatedAt
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DevTotalTokens) {
		toSerialize["devTotalTokens"] = o.DevTotalTokens
	}
	if !IsNil(o.DevLastTokenCreatedAt) {
		toSerialize["devLastTokenCreatedAt"] = o.DevLastTokenCreatedAt
	}
	if !IsNil(o.Market) {
		toSerialize["market"] = o.Market
	}
	if !IsNil(o.Extension) {
		toSerialize["extension"] = o.Extension
	}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	if !IsNil(o.Liquidity) {
		toSerialize["liquidity"] = o.Liquidity
	}
	toSerialize["marketData"] = o.MarketData
	return toSerialize, nil
}

func (o *Token) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain",
		"decimals",
		"name",
		"symbol",
		"address",
		"marketData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToken := _Token{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToken)

	if err != nil {
		return err
	}

	*o = Token(varToken)

	return err
}

type NullableToken struct {
	value *Token
	isSet bool
}

func (v NullableToken) Get() *Token {
	return v.value
}

func (v *NullableToken) Set(val *Token) {
	v.value = val
	v.isSet = true
}

func (v NullableToken) IsSet() bool {
	return v.isSet
}

func (v *NullableToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToken(val *Token) *NullableToken {
	return &NullableToken{value: val, isSet: true}
}

func (v NullableToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

