/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilterCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterCondition{}

// FilterCondition struct for FilterCondition
type FilterCondition struct {
	// DTO.TOKEN.FILTER.FIELD
	Field *string `json:"field,omitempty"`
	// DTO.TOKEN.FILTER.MIN
	Min *string `json:"min,omitempty"`
	// DTO.TOKEN.FILTER.MAX
	Max *string `json:"max,omitempty"`
}

// NewFilterCondition instantiates a new FilterCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterCondition() *FilterCondition {
	this := FilterCondition{}
	return &this
}

// NewFilterConditionWithDefaults instantiates a new FilterCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterConditionWithDefaults() *FilterCondition {
	this := FilterCondition{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *FilterCondition) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterCondition) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *FilterCondition) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *FilterCondition) SetField(v string) {
	o.Field = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *FilterCondition) GetMin() string {
	if o == nil || IsNil(o.Min) {
		var ret string
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterCondition) GetMinOk() (*string, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *FilterCondition) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given string and assigns it to the Min field.
func (o *FilterCondition) SetMin(v string) {
	o.Min = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *FilterCondition) GetMax() string {
	if o == nil || IsNil(o.Max) {
		var ret string
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterCondition) GetMaxOk() (*string, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *FilterCondition) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given string and assigns it to the Max field.
func (o *FilterCondition) SetMax(v string) {
	o.Max = &v
}

func (o FilterCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	return toSerialize, nil
}

type NullableFilterCondition struct {
	value *FilterCondition
	isSet bool
}

func (v NullableFilterCondition) Get() *FilterCondition {
	return v.value
}

func (v *NullableFilterCondition) Set(val *FilterCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterCondition(val *FilterCondition) *NullableFilterCondition {
	return &NullableFilterCondition{value: val, isSet: true}
}

func (v NullableFilterCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


