/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KytWithdrawalPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KytWithdrawalPage{}

// KytWithdrawalPage struct for KytWithdrawalPage
type KytWithdrawalPage struct {
	// DTO.KYT.STANDARD_PAGE.TOTAL
	Total float32 `json:"total"`
	// DTO.KYT.STANDARD_PAGE.PAGE
	Page float32 `json:"page"`
	// DTO.KYT.STANDARD_PAGE.PAGE_SIZE
	PageSize float32 `json:"pageSize"`
	// DTO.KYT.STANDARD_PAGE.TOTAL_PAGES
	TotalPages float32 `json:"totalPages"`
	// DTO.KYT.KYT_WITHDRAWAL_PAGE.DATA
	Data []KytWithdrawalDTO `json:"data"`
}

type _KytWithdrawalPage KytWithdrawalPage

// NewKytWithdrawalPage instantiates a new KytWithdrawalPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKytWithdrawalPage(total float32, page float32, pageSize float32, totalPages float32, data []KytWithdrawalDTO) *KytWithdrawalPage {
	this := KytWithdrawalPage{}
	this.Total = total
	this.Page = page
	this.PageSize = pageSize
	this.TotalPages = totalPages
	this.Data = data
	return &this
}

// NewKytWithdrawalPageWithDefaults instantiates a new KytWithdrawalPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKytWithdrawalPageWithDefaults() *KytWithdrawalPage {
	this := KytWithdrawalPage{}
	return &this
}

// GetTotal returns the Total field value
func (o *KytWithdrawalPage) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *KytWithdrawalPage) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *KytWithdrawalPage) SetTotal(v float32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *KytWithdrawalPage) GetPage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *KytWithdrawalPage) GetPageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *KytWithdrawalPage) SetPage(v float32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *KytWithdrawalPage) GetPageSize() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *KytWithdrawalPage) GetPageSizeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *KytWithdrawalPage) SetPageSize(v float32) {
	o.PageSize = v
}

// GetTotalPages returns the TotalPages field value
func (o *KytWithdrawalPage) GetTotalPages() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *KytWithdrawalPage) GetTotalPagesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *KytWithdrawalPage) SetTotalPages(v float32) {
	o.TotalPages = v
}

// GetData returns the Data field value
func (o *KytWithdrawalPage) GetData() []KytWithdrawalDTO {
	if o == nil {
		var ret []KytWithdrawalDTO
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *KytWithdrawalPage) GetDataOk() ([]KytWithdrawalDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *KytWithdrawalPage) SetData(v []KytWithdrawalDTO) {
	o.Data = v
}

func (o KytWithdrawalPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KytWithdrawalPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["pageSize"] = o.PageSize
	toSerialize["totalPages"] = o.TotalPages
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *KytWithdrawalPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"page",
		"pageSize",
		"totalPages",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKytWithdrawalPage := _KytWithdrawalPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKytWithdrawalPage)

	if err != nil {
		return err
	}

	*o = KytWithdrawalPage(varKytWithdrawalPage)

	return err
}

type NullableKytWithdrawalPage struct {
	value *KytWithdrawalPage
	isSet bool
}

func (v NullableKytWithdrawalPage) Get() *KytWithdrawalPage {
	return v.value
}

func (v *NullableKytWithdrawalPage) Set(val *KytWithdrawalPage) {
	v.value = val
	v.isSet = true
}

func (v NullableKytWithdrawalPage) IsSet() bool {
	return v.isSet
}

func (v *NullableKytWithdrawalPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKytWithdrawalPage(val *KytWithdrawalPage) *NullableKytWithdrawalPage {
	return &NullableKytWithdrawalPage{value: val, isSet: true}
}

func (v NullableKytWithdrawalPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKytWithdrawalPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


