/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworkIdentificationOrg type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkIdentificationOrg{}

// NetworkIdentificationOrg struct for NetworkIdentificationOrg
type NetworkIdentificationOrg struct {
	// DTO.KYT.NETWORK_IDENTIFICATION_ORG.NAME
	Name string `json:"name"`
}

type _NetworkIdentificationOrg NetworkIdentificationOrg

// NewNetworkIdentificationOrg instantiates a new NetworkIdentificationOrg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkIdentificationOrg(name string) *NetworkIdentificationOrg {
	this := NetworkIdentificationOrg{}
	this.Name = name
	return &this
}

// NewNetworkIdentificationOrgWithDefaults instantiates a new NetworkIdentificationOrg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkIdentificationOrgWithDefaults() *NetworkIdentificationOrg {
	this := NetworkIdentificationOrg{}
	return &this
}

// GetName returns the Name field value
func (o *NetworkIdentificationOrg) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NetworkIdentificationOrg) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NetworkIdentificationOrg) SetName(v string) {
	o.Name = v
}

func (o NetworkIdentificationOrg) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkIdentificationOrg) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *NetworkIdentificationOrg) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkIdentificationOrg := _NetworkIdentificationOrg{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkIdentificationOrg)

	if err != nil {
		return err
	}

	*o = NetworkIdentificationOrg(varNetworkIdentificationOrg)

	return err
}

type NullableNetworkIdentificationOrg struct {
	value *NetworkIdentificationOrg
	isSet bool
}

func (v NullableNetworkIdentificationOrg) Get() *NetworkIdentificationOrg {
	return v.value
}

func (v *NullableNetworkIdentificationOrg) Set(val *NetworkIdentificationOrg) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkIdentificationOrg) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkIdentificationOrg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkIdentificationOrg(val *NetworkIdentificationOrg) *NullableNetworkIdentificationOrg {
	return &NullableNetworkIdentificationOrg{value: val, isSet: true}
}

func (v NullableNetworkIdentificationOrg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkIdentificationOrg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

