/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GainersAndLosersPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GainersAndLosersPage{}

// GainersAndLosersPage struct for GainersAndLosersPage
type GainersAndLosersPage struct {
	// DTO.PAGE.HAS_NEXT
	HasNext *bool `json:"hasNext,omitempty"`
	// DTO.PAGE.HAS_PREV
	HasPrev *bool `json:"hasPrev,omitempty"`
	// DTO.PAGE.START_CURSOR
	StartCursor *string `json:"startCursor,omitempty"`
	// DTO.PAGE.END_CURSOR
	EndCursor *string `json:"endCursor,omitempty"`
	// DTO.PAGE.TOTAL
	Total *float32 `json:"total,omitempty"`
	// DTO.TRADE.GAINERS_LOSERS.PAGE.DATA
	Data []GainersAndLosersDTO `json:"data"`
}

type _GainersAndLosersPage GainersAndLosersPage

// NewGainersAndLosersPage instantiates a new GainersAndLosersPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGainersAndLosersPage(data []GainersAndLosersDTO) *GainersAndLosersPage {
	this := GainersAndLosersPage{}
	var hasNext bool = false
	this.HasNext = &hasNext
	var hasPrev bool = false
	this.HasPrev = &hasPrev
	this.Data = data
	return &this
}

// NewGainersAndLosersPageWithDefaults instantiates a new GainersAndLosersPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGainersAndLosersPageWithDefaults() *GainersAndLosersPage {
	this := GainersAndLosersPage{}
	var hasNext bool = false
	this.HasNext = &hasNext
	var hasPrev bool = false
	this.HasPrev = &hasPrev
	return &this
}

// GetHasNext returns the HasNext field value if set, zero value otherwise.
func (o *GainersAndLosersPage) GetHasNext() bool {
	if o == nil || IsNil(o.HasNext) {
		var ret bool
		return ret
	}
	return *o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GainersAndLosersPage) GetHasNextOk() (*bool, bool) {
	if o == nil || IsNil(o.HasNext) {
		return nil, false
	}
	return o.HasNext, true
}

// HasHasNext returns a boolean if a field has been set.
func (o *GainersAndLosersPage) HasHasNext() bool {
	if o != nil && !IsNil(o.HasNext) {
		return true
	}

	return false
}

// SetHasNext gets a reference to the given bool and assigns it to the HasNext field.
func (o *GainersAndLosersPage) SetHasNext(v bool) {
	o.HasNext = &v
}

// GetHasPrev returns the HasPrev field value if set, zero value otherwise.
func (o *GainersAndLosersPage) GetHasPrev() bool {
	if o == nil || IsNil(o.HasPrev) {
		var ret bool
		return ret
	}
	return *o.HasPrev
}

// GetHasPrevOk returns a tuple with the HasPrev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GainersAndLosersPage) GetHasPrevOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPrev) {
		return nil, false
	}
	return o.HasPrev, true
}

// HasHasPrev returns a boolean if a field has been set.
func (o *GainersAndLosersPage) HasHasPrev() bool {
	if o != nil && !IsNil(o.HasPrev) {
		return true
	}

	return false
}

// SetHasPrev gets a reference to the given bool and assigns it to the HasPrev field.
func (o *GainersAndLosersPage) SetHasPrev(v bool) {
	o.HasPrev = &v
}

// GetStartCursor returns the StartCursor field value if set, zero value otherwise.
func (o *GainersAndLosersPage) GetStartCursor() string {
	if o == nil || IsNil(o.StartCursor) {
		var ret string
		return ret
	}
	return *o.StartCursor
}

// GetStartCursorOk returns a tuple with the StartCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GainersAndLosersPage) GetStartCursorOk() (*string, bool) {
	if o == nil || IsNil(o.StartCursor) {
		return nil, false
	}
	return o.StartCursor, true
}

// HasStartCursor returns a boolean if a field has been set.
func (o *GainersAndLosersPage) HasStartCursor() bool {
	if o != nil && !IsNil(o.StartCursor) {
		return true
	}

	return false
}

// SetStartCursor gets a reference to the given string and assigns it to the StartCursor field.
func (o *GainersAndLosersPage) SetStartCursor(v string) {
	o.StartCursor = &v
}

// GetEndCursor returns the EndCursor field value if set, zero value otherwise.
func (o *GainersAndLosersPage) GetEndCursor() string {
	if o == nil || IsNil(o.EndCursor) {
		var ret string
		return ret
	}
	return *o.EndCursor
}

// GetEndCursorOk returns a tuple with the EndCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GainersAndLosersPage) GetEndCursorOk() (*string, bool) {
	if o == nil || IsNil(o.EndCursor) {
		return nil, false
	}
	return o.EndCursor, true
}

// HasEndCursor returns a boolean if a field has been set.
func (o *GainersAndLosersPage) HasEndCursor() bool {
	if o != nil && !IsNil(o.EndCursor) {
		return true
	}

	return false
}

// SetEndCursor gets a reference to the given string and assigns it to the EndCursor field.
func (o *GainersAndLosersPage) SetEndCursor(v string) {
	o.EndCursor = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GainersAndLosersPage) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GainersAndLosersPage) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GainersAndLosersPage) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *GainersAndLosersPage) SetTotal(v float32) {
	o.Total = &v
}

// GetData returns the Data field value
func (o *GainersAndLosersPage) GetData() []GainersAndLosersDTO {
	if o == nil {
		var ret []GainersAndLosersDTO
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GainersAndLosersPage) GetDataOk() ([]GainersAndLosersDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GainersAndLosersPage) SetData(v []GainersAndLosersDTO) {
	o.Data = v
}

func (o GainersAndLosersPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GainersAndLosersPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasNext) {
		toSerialize["hasNext"] = o.HasNext
	}
	if !IsNil(o.HasPrev) {
		toSerialize["hasPrev"] = o.HasPrev
	}
	if !IsNil(o.StartCursor) {
		toSerialize["startCursor"] = o.StartCursor
	}
	if !IsNil(o.EndCursor) {
		toSerialize["endCursor"] = o.EndCursor
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GainersAndLosersPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGainersAndLosersPage := _GainersAndLosersPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGainersAndLosersPage)

	if err != nil {
		return err
	}

	*o = GainersAndLosersPage(varGainersAndLosersPage)

	return err
}

type NullableGainersAndLosersPage struct {
	value *GainersAndLosersPage
	isSet bool
}

func (v NullableGainersAndLosersPage) Get() *GainersAndLosersPage {
	return v.value
}

func (v *NullableGainersAndLosersPage) Set(val *GainersAndLosersPage) {
	v.value = val
	v.isSet = true
}

func (v NullableGainersAndLosersPage) IsSet() bool {
	return v.isSet
}

func (v *NullableGainersAndLosersPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGainersAndLosersPage(val *GainersAndLosersPage) *NullableGainersAndLosersPage {
	return &NullableGainersAndLosersPage{value: val, isSet: true}
}

func (v NullableGainersAndLosersPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGainersAndLosersPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

