/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TopTradersPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopTradersPage{}

// TopTradersPage struct for TopTradersPage
type TopTradersPage struct {
	// DTO.PAGE.HAS_NEXT
	HasNext *bool `json:"hasNext,omitempty"`
	// DTO.PAGE.HAS_PREV
	HasPrev *bool `json:"hasPrev,omitempty"`
	// DTO.PAGE.START_CURSOR
	StartCursor *string `json:"startCursor,omitempty"`
	// DTO.PAGE.END_CURSOR
	EndCursor *string `json:"endCursor,omitempty"`
	// DTO.PAGE.TOTAL
	Total *float32 `json:"total,omitempty"`
	// DTO.TRADE.TOP_TRADERS.PAGE.DATA
	Data []TopTradersDTO `json:"data"`
}

type _TopTradersPage TopTradersPage

// NewTopTradersPage instantiates a new TopTradersPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopTradersPage(data []TopTradersDTO) *TopTradersPage {
	this := TopTradersPage{}
	var hasNext bool = false
	this.HasNext = &hasNext
	var hasPrev bool = false
	this.HasPrev = &hasPrev
	this.Data = data
	return &this
}

// NewTopTradersPageWithDefaults instantiates a new TopTradersPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopTradersPageWithDefaults() *TopTradersPage {
	this := TopTradersPage{}
	var hasNext bool = false
	this.HasNext = &hasNext
	var hasPrev bool = false
	this.HasPrev = &hasPrev
	return &this
}

// GetHasNext returns the HasNext field value if set, zero value otherwise.
func (o *TopTradersPage) GetHasNext() bool {
	if o == nil || IsNil(o.HasNext) {
		var ret bool
		return ret
	}
	return *o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopTradersPage) GetHasNextOk() (*bool, bool) {
	if o == nil || IsNil(o.HasNext) {
		return nil, false
	}
	return o.HasNext, true
}

// HasHasNext returns a boolean if a field has been set.
func (o *TopTradersPage) HasHasNext() bool {
	if o != nil && !IsNil(o.HasNext) {
		return true
	}

	return false
}

// SetHasNext gets a reference to the given bool and assigns it to the HasNext field.
func (o *TopTradersPage) SetHasNext(v bool) {
	o.HasNext = &v
}

// GetHasPrev returns the HasPrev field value if set, zero value otherwise.
func (o *TopTradersPage) GetHasPrev() bool {
	if o == nil || IsNil(o.HasPrev) {
		var ret bool
		return ret
	}
	return *o.HasPrev
}

// GetHasPrevOk returns a tuple with the HasPrev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopTradersPage) GetHasPrevOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPrev) {
		return nil, false
	}
	return o.HasPrev, true
}

// HasHasPrev returns a boolean if a field has been set.
func (o *TopTradersPage) HasHasPrev() bool {
	if o != nil && !IsNil(o.HasPrev) {
		return true
	}

	return false
}

// SetHasPrev gets a reference to the given bool and assigns it to the HasPrev field.
func (o *TopTradersPage) SetHasPrev(v bool) {
	o.HasPrev = &v
}

// GetStartCursor returns the StartCursor field value if set, zero value otherwise.
func (o *TopTradersPage) GetStartCursor() string {
	if o == nil || IsNil(o.StartCursor) {
		var ret string
		return ret
	}
	return *o.StartCursor
}

// GetStartCursorOk returns a tuple with the StartCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopTradersPage) GetStartCursorOk() (*string, bool) {
	if o == nil || IsNil(o.StartCursor) {
		return nil, false
	}
	return o.StartCursor, true
}

// HasStartCursor returns a boolean if a field has been set.
func (o *TopTradersPage) HasStartCursor() bool {
	if o != nil && !IsNil(o.StartCursor) {
		return true
	}

	return false
}

// SetStartCursor gets a reference to the given string and assigns it to the StartCursor field.
func (o *TopTradersPage) SetStartCursor(v string) {
	o.StartCursor = &v
}

// GetEndCursor returns the EndCursor field value if set, zero value otherwise.
func (o *TopTradersPage) GetEndCursor() string {
	if o == nil || IsNil(o.EndCursor) {
		var ret string
		return ret
	}
	return *o.EndCursor
}

// GetEndCursorOk returns a tuple with the EndCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopTradersPage) GetEndCursorOk() (*string, bool) {
	if o == nil || IsNil(o.EndCursor) {
		return nil, false
	}
	return o.EndCursor, true
}

// HasEndCursor returns a boolean if a field has been set.
func (o *TopTradersPage) HasEndCursor() bool {
	if o != nil && !IsNil(o.EndCursor) {
		return true
	}

	return false
}

// SetEndCursor gets a reference to the given string and assigns it to the EndCursor field.
func (o *TopTradersPage) SetEndCursor(v string) {
	o.EndCursor = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TopTradersPage) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopTradersPage) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TopTradersPage) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *TopTradersPage) SetTotal(v float32) {
	o.Total = &v
}

// GetData returns the Data field value
func (o *TopTradersPage) GetData() []TopTradersDTO {
	if o == nil {
		var ret []TopTradersDTO
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TopTradersPage) GetDataOk() ([]TopTradersDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TopTradersPage) SetData(v []TopTradersDTO) {
	o.Data = v
}

func (o TopTradersPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopTradersPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasNext) {
		toSerialize["hasNext"] = o.HasNext
	}
	if !IsNil(o.HasPrev) {
		toSerialize["hasPrev"] = o.HasPrev
	}
	if !IsNil(o.StartCursor) {
		toSerialize["startCursor"] = o.StartCursor
	}
	if !IsNil(o.EndCursor) {
		toSerialize["endCursor"] = o.EndCursor
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *TopTradersPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTopTradersPage := _TopTradersPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTopTradersPage)

	if err != nil {
		return err
	}

	*o = TopTradersPage(varTopTradersPage)

	return err
}

type NullableTopTradersPage struct {
	value *TopTradersPage
	isSet bool
}

func (v NullableTopTradersPage) Get() *TopTradersPage {
	return v.value
}

func (v *NullableTopTradersPage) Set(val *TopTradersPage) {
	v.value = val
	v.isSet = true
}

func (v NullableTopTradersPage) IsSet() bool {
	return v.isSet
}

func (v *NullableTopTradersPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopTradersPage(val *TopTradersPage) *NullableTopTradersPage {
	return &NullableTopTradersPage{value: val, isSet: true}
}

func (v NullableTopTradersPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopTradersPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


