/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OnChainActivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OnChainActivity{}

// OnChainActivity struct for OnChainActivity
type OnChainActivity struct {
	// DTO.KYT.ON_CHAIN_ACTIVITY.FIRST_TRANSACTION_AT
	FirstTransactionAt float32 `json:"first_transaction_at"`
}

type _OnChainActivity OnChainActivity

// NewOnChainActivity instantiates a new OnChainActivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnChainActivity(firstTransactionAt float32) *OnChainActivity {
	this := OnChainActivity{}
	this.FirstTransactionAt = firstTransactionAt
	return &this
}

// NewOnChainActivityWithDefaults instantiates a new OnChainActivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnChainActivityWithDefaults() *OnChainActivity {
	this := OnChainActivity{}
	return &this
}

// GetFirstTransactionAt returns the FirstTransactionAt field value
func (o *OnChainActivity) GetFirstTransactionAt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FirstTransactionAt
}

// GetFirstTransactionAtOk returns a tuple with the FirstTransactionAt field value
// and a boolean to check if the value has been set.
func (o *OnChainActivity) GetFirstTransactionAtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstTransactionAt, true
}

// SetFirstTransactionAt sets field value
func (o *OnChainActivity) SetFirstTransactionAt(v float32) {
	o.FirstTransactionAt = v
}

func (o OnChainActivity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OnChainActivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_transaction_at"] = o.FirstTransactionAt
	return toSerialize, nil
}

func (o *OnChainActivity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_transaction_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOnChainActivity := _OnChainActivity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOnChainActivity)

	if err != nil {
		return err
	}

	*o = OnChainActivity(varOnChainActivity)

	return err
}

type NullableOnChainActivity struct {
	value *OnChainActivity
	isSet bool
}

func (v NullableOnChainActivity) Get() *OnChainActivity {
	return v.value
}

func (v *NullableOnChainActivity) Set(val *OnChainActivity) {
	v.value = val
	v.isSet = true
}

func (v NullableOnChainActivity) IsSet() bool {
	return v.isSet
}

func (v *NullableOnChainActivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnChainActivity(val *OnChainActivity) *NullableOnChainActivity {
	return &NullableOnChainActivity{value: val, isSet: true}
}

func (v NullableOnChainActivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnChainActivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

