/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GainersAndLosersDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GainersAndLosersDTO{}

// GainersAndLosersDTO struct for GainersAndLosersDTO
type GainersAndLosersDTO struct {
	// GLOBAL.WALLETADDRESS.DESCRIPTION
	Address string `json:"address"`
	// DTO.TRADE.GAINERS_LOSERS.PNL
	Pnl float32 `json:"pnl"`
	// DTO.TRADE.GAINERS_LOSERS.TRADE_COUNT
	TradeCount float32 `json:"tradeCount"`
	// DTO.TRADE.GAINERS_LOSERS.VOLUME
	Volume float32 `json:"volume"`
}

type _GainersAndLosersDTO GainersAndLosersDTO

// NewGainersAndLosersDTO instantiates a new GainersAndLosersDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGainersAndLosersDTO(address string, pnl float32, tradeCount float32, volume float32) *GainersAndLosersDTO {
	this := GainersAndLosersDTO{}
	this.Address = address
	this.Pnl = pnl
	this.TradeCount = tradeCount
	this.Volume = volume
	return &this
}

// NewGainersAndLosersDTOWithDefaults instantiates a new GainersAndLosersDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGainersAndLosersDTOWithDefaults() *GainersAndLosersDTO {
	this := GainersAndLosersDTO{}
	return &this
}

// GetAddress returns the Address field value
func (o *GainersAndLosersDTO) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *GainersAndLosersDTO) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *GainersAndLosersDTO) SetAddress(v string) {
	o.Address = v
}

// GetPnl returns the Pnl field value
func (o *GainersAndLosersDTO) GetPnl() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Pnl
}

// GetPnlOk returns a tuple with the Pnl field value
// and a boolean to check if the value has been set.
func (o *GainersAndLosersDTO) GetPnlOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pnl, true
}

// SetPnl sets field value
func (o *GainersAndLosersDTO) SetPnl(v float32) {
	o.Pnl = v
}

// GetTradeCount returns the TradeCount field value
func (o *GainersAndLosersDTO) GetTradeCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TradeCount
}

// GetTradeCountOk returns a tuple with the TradeCount field value
// and a boolean to check if the value has been set.
func (o *GainersAndLosersDTO) GetTradeCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradeCount, true
}

// SetTradeCount sets field value
func (o *GainersAndLosersDTO) SetTradeCount(v float32) {
	o.TradeCount = v
}

// GetVolume returns the Volume field value
func (o *GainersAndLosersDTO) GetVolume() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *GainersAndLosersDTO) GetVolumeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *GainersAndLosersDTO) SetVolume(v float32) {
	o.Volume = v
}

func (o GainersAndLosersDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GainersAndLosersDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["pnl"] = o.Pnl
	toSerialize["tradeCount"] = o.TradeCount
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

func (o *GainersAndLosersDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"pnl",
		"tradeCount",
		"volume",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGainersAndLosersDTO := _GainersAndLosersDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGainersAndLosersDTO)

	if err != nil {
		return err
	}

	*o = GainersAndLosersDTO(varGainersAndLosersDTO)

	return err
}

type NullableGainersAndLosersDTO struct {
	value *GainersAndLosersDTO
	isSet bool
}

func (v NullableGainersAndLosersDTO) Get() *GainersAndLosersDTO {
	return v.value
}

func (v *NullableGainersAndLosersDTO) Set(val *GainersAndLosersDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableGainersAndLosersDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableGainersAndLosersDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGainersAndLosersDTO(val *GainersAndLosersDTO) *NullableGainersAndLosersDTO {
	return &NullableGainersAndLosersDTO{value: val, isSet: true}
}

func (v NullableGainersAndLosersDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGainersAndLosersDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

