/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransferDirectExposureResponseDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferDirectExposureResponseDTO{}

// TransferDirectExposureResponseDTO struct for TransferDirectExposureResponseDTO
type TransferDirectExposureResponseDTO struct {
	// DTO.KYT.TRANSFER_DIRECT_EXPOSURE_RESPONSE.DIRECT
	Direct DirectExposureDetail `json:"direct"`
}

type _TransferDirectExposureResponseDTO TransferDirectExposureResponseDTO

// NewTransferDirectExposureResponseDTO instantiates a new TransferDirectExposureResponseDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferDirectExposureResponseDTO(direct DirectExposureDetail) *TransferDirectExposureResponseDTO {
	this := TransferDirectExposureResponseDTO{}
	this.Direct = direct
	return &this
}

// NewTransferDirectExposureResponseDTOWithDefaults instantiates a new TransferDirectExposureResponseDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferDirectExposureResponseDTOWithDefaults() *TransferDirectExposureResponseDTO {
	this := TransferDirectExposureResponseDTO{}
	return &this
}

// GetDirect returns the Direct field value
func (o *TransferDirectExposureResponseDTO) GetDirect() DirectExposureDetail {
	if o == nil {
		var ret DirectExposureDetail
		return ret
	}

	return o.Direct
}

// GetDirectOk returns a tuple with the Direct field value
// and a boolean to check if the value has been set.
func (o *TransferDirectExposureResponseDTO) GetDirectOk() (*DirectExposureDetail, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direct, true
}

// SetDirect sets field value
func (o *TransferDirectExposureResponseDTO) SetDirect(v DirectExposureDetail) {
	o.Direct = v
}

func (o TransferDirectExposureResponseDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferDirectExposureResponseDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["direct"] = o.Direct
	return toSerialize, nil
}

func (o *TransferDirectExposureResponseDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"direct",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferDirectExposureResponseDTO := _TransferDirectExposureResponseDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferDirectExposureResponseDTO)

	if err != nil {
		return err
	}

	*o = TransferDirectExposureResponseDTO(varTransferDirectExposureResponseDTO)

	return err
}

type NullableTransferDirectExposureResponseDTO struct {
	value *TransferDirectExposureResponseDTO
	isSet bool
}

func (v NullableTransferDirectExposureResponseDTO) Get() *TransferDirectExposureResponseDTO {
	return v.value
}

func (v *NullableTransferDirectExposureResponseDTO) Set(val *TransferDirectExposureResponseDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferDirectExposureResponseDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferDirectExposureResponseDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferDirectExposureResponseDTO(val *TransferDirectExposureResponseDTO) *NullableTransferDirectExposureResponseDTO {
	return &NullableTransferDirectExposureResponseDTO{value: val, isSet: true}
}

func (v NullableTransferDirectExposureResponseDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferDirectExposureResponseDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

