/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressExposure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressExposure{}

// AddressExposure struct for AddressExposure
type AddressExposure struct {
	// DTO.KYT.ADDRESS_EXPOSURE.CATEGORY
	Category string `json:"category"`
	// DTO.KYT.ADDRESS_EXPOSURE.VALUE
	Value float32 `json:"value"`
	// DTO.KYT.ADDRESS_EXPOSURE.EXPOSURE_TYPE
	ExposureType string `json:"exposureType"`
	// DTO.KYT.ADDRESS_EXPOSURE.DIRECTION
	Direction string `json:"direction"`
}

type _AddressExposure AddressExposure

// NewAddressExposure instantiates a new AddressExposure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressExposure(category string, value float32, exposureType string, direction string) *AddressExposure {
	this := AddressExposure{}
	this.Category = category
	this.Value = value
	this.ExposureType = exposureType
	this.Direction = direction
	return &this
}

// NewAddressExposureWithDefaults instantiates a new AddressExposure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressExposureWithDefaults() *AddressExposure {
	this := AddressExposure{}
	return &this
}

// GetCategory returns the Category field value
func (o *AddressExposure) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *AddressExposure) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *AddressExposure) SetCategory(v string) {
	o.Category = v
}

// GetValue returns the Value field value
func (o *AddressExposure) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AddressExposure) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AddressExposure) SetValue(v float32) {
	o.Value = v
}

// GetExposureType returns the ExposureType field value
func (o *AddressExposure) GetExposureType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExposureType
}

// GetExposureTypeOk returns a tuple with the ExposureType field value
// and a boolean to check if the value has been set.
func (o *AddressExposure) GetExposureTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExposureType, true
}

// SetExposureType sets field value
func (o *AddressExposure) SetExposureType(v string) {
	o.ExposureType = v
}

// GetDirection returns the Direction field value
func (o *AddressExposure) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *AddressExposure) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *AddressExposure) SetDirection(v string) {
	o.Direction = v
}

func (o AddressExposure) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressExposure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category"] = o.Category
	toSerialize["value"] = o.Value
	toSerialize["exposureType"] = o.ExposureType
	toSerialize["direction"] = o.Direction
	return toSerialize, nil
}

func (o *AddressExposure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"category",
		"value",
		"exposureType",
		"direction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressExposure := _AddressExposure{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressExposure)

	if err != nil {
		return err
	}

	*o = AddressExposure(varAddressExposure)

	return err
}

type NullableAddressExposure struct {
	value *AddressExposure
	isSet bool
}

func (v NullableAddressExposure) Get() *AddressExposure {
	return v.value
}

func (v *NullableAddressExposure) Set(val *AddressExposure) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressExposure) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressExposure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressExposure(val *AddressExposure) *NullableAddressExposure {
	return &NullableAddressExposure{value: val, isSet: true}
}

func (v NullableAddressExposure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressExposure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


