/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the KytAddressDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KytAddressDTO{}

// KytAddressDTO struct for KytAddressDTO
type KytAddressDTO struct {
	// DTO.KYT.KYT_ADDRESS.ID
	Id float32 `json:"id"`
	// DTO.KYT.KYT_ADDRESS.ORG_ID
	OrgId string `json:"orgId"`
	// DTO.KYT.KYT_ADDRESS.ADDRESS
	Address string `json:"address"`
	// DTO.KYT.KYT_ADDRESS.CREATED_AT
	CreatedAt time.Time `json:"createdAt"`
	// DTO.KYT.KYT_ADDRESS.UPDATED_AT
	UpdatedAt time.Time `json:"updatedAt"`
}

type _KytAddressDTO KytAddressDTO

// NewKytAddressDTO instantiates a new KytAddressDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKytAddressDTO(id float32, orgId string, address string, createdAt time.Time, updatedAt time.Time) *KytAddressDTO {
	this := KytAddressDTO{}
	this.Id = id
	this.OrgId = orgId
	this.Address = address
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewKytAddressDTOWithDefaults instantiates a new KytAddressDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKytAddressDTOWithDefaults() *KytAddressDTO {
	this := KytAddressDTO{}
	return &this
}

// GetId returns the Id field value
func (o *KytAddressDTO) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KytAddressDTO) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KytAddressDTO) SetId(v float32) {
	o.Id = v
}

// GetOrgId returns the OrgId field value
func (o *KytAddressDTO) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *KytAddressDTO) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *KytAddressDTO) SetOrgId(v string) {
	o.OrgId = v
}

// GetAddress returns the Address field value
func (o *KytAddressDTO) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *KytAddressDTO) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *KytAddressDTO) SetAddress(v string) {
	o.Address = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *KytAddressDTO) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *KytAddressDTO) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *KytAddressDTO) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *KytAddressDTO) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *KytAddressDTO) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *KytAddressDTO) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o KytAddressDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KytAddressDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["orgId"] = o.OrgId
	toSerialize["address"] = o.Address
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *KytAddressDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"orgId",
		"address",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKytAddressDTO := _KytAddressDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKytAddressDTO)

	if err != nil {
		return err
	}

	*o = KytAddressDTO(varKytAddressDTO)

	return err
}

type NullableKytAddressDTO struct {
	value *KytAddressDTO
	isSet bool
}

func (v NullableKytAddressDTO) Get() *KytAddressDTO {
	return v.value
}

func (v *NullableKytAddressDTO) Set(val *KytAddressDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableKytAddressDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableKytAddressDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKytAddressDTO(val *KytAddressDTO) *NullableKytAddressDTO {
	return &NullableKytAddressDTO{value: val, isSet: true}
}

func (v NullableKytAddressDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKytAddressDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


