/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MoonshotSubmitCreateTokenInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoonshotSubmitCreateTokenInput{}

// MoonshotSubmitCreateTokenInput struct for MoonshotSubmitCreateTokenInput
type MoonshotSubmitCreateTokenInput struct {
	// Signed transaction in Base64 format for Moonshot token creation
	SignedTx string `json:"signedTx"`
	// Additional data required for Moonshot token creation transaction submission
	Extra map[string]interface{} `json:"extra,omitempty"`
}

type _MoonshotSubmitCreateTokenInput MoonshotSubmitCreateTokenInput

// NewMoonshotSubmitCreateTokenInput instantiates a new MoonshotSubmitCreateTokenInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoonshotSubmitCreateTokenInput(signedTx string) *MoonshotSubmitCreateTokenInput {
	this := MoonshotSubmitCreateTokenInput{}
	this.SignedTx = signedTx
	return &this
}

// NewMoonshotSubmitCreateTokenInputWithDefaults instantiates a new MoonshotSubmitCreateTokenInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoonshotSubmitCreateTokenInputWithDefaults() *MoonshotSubmitCreateTokenInput {
	this := MoonshotSubmitCreateTokenInput{}
	return &this
}

// GetSignedTx returns the SignedTx field value
func (o *MoonshotSubmitCreateTokenInput) GetSignedTx() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignedTx
}

// GetSignedTxOk returns a tuple with the SignedTx field value
// and a boolean to check if the value has been set.
func (o *MoonshotSubmitCreateTokenInput) GetSignedTxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignedTx, true
}

// SetSignedTx sets field value
func (o *MoonshotSubmitCreateTokenInput) SetSignedTx(v string) {
	o.SignedTx = v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *MoonshotSubmitCreateTokenInput) GetExtra() map[string]interface{} {
	if o == nil || IsNil(o.Extra) {
		var ret map[string]interface{}
		return ret
	}
	return o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoonshotSubmitCreateTokenInput) GetExtraOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Extra) {
		return map[string]interface{}{}, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *MoonshotSubmitCreateTokenInput) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given map[string]interface{} and assigns it to the Extra field.
func (o *MoonshotSubmitCreateTokenInput) SetExtra(v map[string]interface{}) {
	o.Extra = v
}

func (o MoonshotSubmitCreateTokenInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoonshotSubmitCreateTokenInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signedTx"] = o.SignedTx
	if !IsNil(o.Extra) {
		toSerialize["extra"] = o.Extra
	}
	return toSerialize, nil
}

func (o *MoonshotSubmitCreateTokenInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signedTx",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMoonshotSubmitCreateTokenInput := _MoonshotSubmitCreateTokenInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMoonshotSubmitCreateTokenInput)

	if err != nil {
		return err
	}

	*o = MoonshotSubmitCreateTokenInput(varMoonshotSubmitCreateTokenInput)

	return err
}

type NullableMoonshotSubmitCreateTokenInput struct {
	value *MoonshotSubmitCreateTokenInput
	isSet bool
}

func (v NullableMoonshotSubmitCreateTokenInput) Get() *MoonshotSubmitCreateTokenInput {
	return v.value
}

func (v *NullableMoonshotSubmitCreateTokenInput) Set(val *MoonshotSubmitCreateTokenInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMoonshotSubmitCreateTokenInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMoonshotSubmitCreateTokenInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoonshotSubmitCreateTokenInput(val *MoonshotSubmitCreateTokenInput) *NullableMoonshotSubmitCreateTokenInput {
	return &NullableMoonshotSubmitCreateTokenInput{value: val, isSet: true}
}

func (v NullableMoonshotSubmitCreateTokenInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoonshotSubmitCreateTokenInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

