/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WithdrawalBaseResponseDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithdrawalBaseResponseDTO{}

// WithdrawalBaseResponseDTO struct for WithdrawalBaseResponseDTO
type WithdrawalBaseResponseDTO struct {
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.ASSET
	Asset string `json:"asset"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.ASSET_ID
	AssetId string `json:"assetId"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.NETWORK
	Network string `json:"network"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.ADDRESS
	Address string `json:"address"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.MEMO
	Memo string `json:"memo"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.ATTEMPT_IDENTIFIER
	AttemptIdentifier string `json:"attemptIdentifier"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.ASSET_AMOUNT
	AssetAmount float32 `json:"assetAmount"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.EXTERNAL_ID
	ExternalId string `json:"externalId"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.USD_AMOUNT
	UsdAmount float32 `json:"usdAmount"`
	// DTO.KYT.WITHDRAWAL_BASE_RESPONSE.UPDATED_AT
	UpdatedAt string `json:"updatedAt"`
}

type _WithdrawalBaseResponseDTO WithdrawalBaseResponseDTO

// NewWithdrawalBaseResponseDTO instantiates a new WithdrawalBaseResponseDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithdrawalBaseResponseDTO(asset string, assetId string, network string, address string, memo string, attemptIdentifier string, assetAmount float32, externalId string, usdAmount float32, updatedAt string) *WithdrawalBaseResponseDTO {
	this := WithdrawalBaseResponseDTO{}
	this.Asset = asset
	this.AssetId = assetId
	this.Network = network
	this.Address = address
	this.Memo = memo
	this.AttemptIdentifier = attemptIdentifier
	this.AssetAmount = assetAmount
	this.ExternalId = externalId
	this.UsdAmount = usdAmount
	this.UpdatedAt = updatedAt
	return &this
}

// NewWithdrawalBaseResponseDTOWithDefaults instantiates a new WithdrawalBaseResponseDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithdrawalBaseResponseDTOWithDefaults() *WithdrawalBaseResponseDTO {
	this := WithdrawalBaseResponseDTO{}
	return &this
}

// GetAsset returns the Asset field value
func (o *WithdrawalBaseResponseDTO) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *WithdrawalBaseResponseDTO) SetAsset(v string) {
	o.Asset = v
}

// GetAssetId returns the AssetId field value
func (o *WithdrawalBaseResponseDTO) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *WithdrawalBaseResponseDTO) SetAssetId(v string) {
	o.AssetId = v
}

// GetNetwork returns the Network field value
func (o *WithdrawalBaseResponseDTO) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *WithdrawalBaseResponseDTO) SetNetwork(v string) {
	o.Network = v
}

// GetAddress returns the Address field value
func (o *WithdrawalBaseResponseDTO) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *WithdrawalBaseResponseDTO) SetAddress(v string) {
	o.Address = v
}

// GetMemo returns the Memo field value
func (o *WithdrawalBaseResponseDTO) GetMemo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Memo
}

// GetMemoOk returns a tuple with the Memo field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetMemoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memo, true
}

// SetMemo sets field value
func (o *WithdrawalBaseResponseDTO) SetMemo(v string) {
	o.Memo = v
}

// GetAttemptIdentifier returns the AttemptIdentifier field value
func (o *WithdrawalBaseResponseDTO) GetAttemptIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttemptIdentifier
}

// GetAttemptIdentifierOk returns a tuple with the AttemptIdentifier field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetAttemptIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptIdentifier, true
}

// SetAttemptIdentifier sets field value
func (o *WithdrawalBaseResponseDTO) SetAttemptIdentifier(v string) {
	o.AttemptIdentifier = v
}

// GetAssetAmount returns the AssetAmount field value
func (o *WithdrawalBaseResponseDTO) GetAssetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AssetAmount
}

// GetAssetAmountOk returns a tuple with the AssetAmount field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetAssetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetAmount, true
}

// SetAssetAmount sets field value
func (o *WithdrawalBaseResponseDTO) SetAssetAmount(v float32) {
	o.AssetAmount = v
}

// GetExternalId returns the ExternalId field value
func (o *WithdrawalBaseResponseDTO) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *WithdrawalBaseResponseDTO) SetExternalId(v string) {
	o.ExternalId = v
}

// GetUsdAmount returns the UsdAmount field value
func (o *WithdrawalBaseResponseDTO) GetUsdAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UsdAmount
}

// GetUsdAmountOk returns a tuple with the UsdAmount field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetUsdAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsdAmount, true
}

// SetUsdAmount sets field value
func (o *WithdrawalBaseResponseDTO) SetUsdAmount(v float32) {
	o.UsdAmount = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WithdrawalBaseResponseDTO) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WithdrawalBaseResponseDTO) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WithdrawalBaseResponseDTO) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o WithdrawalBaseResponseDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithdrawalBaseResponseDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset"] = o.Asset
	toSerialize["assetId"] = o.AssetId
	toSerialize["network"] = o.Network
	toSerialize["address"] = o.Address
	toSerialize["memo"] = o.Memo
	toSerialize["attemptIdentifier"] = o.AttemptIdentifier
	toSerialize["assetAmount"] = o.AssetAmount
	toSerialize["externalId"] = o.ExternalId
	toSerialize["usdAmount"] = o.UsdAmount
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *WithdrawalBaseResponseDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset",
		"assetId",
		"network",
		"address",
		"memo",
		"attemptIdentifier",
		"assetAmount",
		"externalId",
		"usdAmount",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWithdrawalBaseResponseDTO := _WithdrawalBaseResponseDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWithdrawalBaseResponseDTO)

	if err != nil {
		return err
	}

	*o = WithdrawalBaseResponseDTO(varWithdrawalBaseResponseDTO)

	return err
}

type NullableWithdrawalBaseResponseDTO struct {
	value *WithdrawalBaseResponseDTO
	isSet bool
}

func (v NullableWithdrawalBaseResponseDTO) Get() *WithdrawalBaseResponseDTO {
	return v.value
}

func (v *NullableWithdrawalBaseResponseDTO) Set(val *WithdrawalBaseResponseDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableWithdrawalBaseResponseDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableWithdrawalBaseResponseDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithdrawalBaseResponseDTO(val *WithdrawalBaseResponseDTO) *NullableWithdrawalBaseResponseDTO {
	return &NullableWithdrawalBaseResponseDTO{value: val, isSet: true}
}

func (v NullableWithdrawalBaseResponseDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithdrawalBaseResponseDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

