/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// Resolution the model 'Resolution'
type Resolution string

// List of Resolution
const (
	RESOLUTION__1S Resolution = "1s"
	RESOLUTION__15S Resolution = "15s"
	RESOLUTION__30S Resolution = "30s"
	RESOLUTION__1M Resolution = "1m"
	RESOLUTION__5M Resolution = "5m"
	RESOLUTION__15M Resolution = "15m"
	RESOLUTION__1H Resolution = "1h"
	RESOLUTION__4H Resolution = "4h"
	RESOLUTION__12H Resolution = "12h"
	RESOLUTION__1D Resolution = "1d"
)

// All allowed values of Resolution enum
var AllowedResolutionEnumValues = []Resolution{
	"1s",
	"15s",
	"30s",
	"1m",
	"5m",
	"15m",
	"1h",
	"4h",
	"12h",
	"1d",
}

func (v *Resolution) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Resolution(value)
	for _, existing := range AllowedResolutionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Resolution", value)
}

// NewResolutionFromValue returns a pointer to a valid Resolution
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResolutionFromValue(v string) (*Resolution, error) {
	ev := Resolution(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Resolution: valid values are %v", v, AllowedResolutionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Resolution) IsValid() bool {
	for _, existing := range AllowedResolutionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Resolution value
func (v Resolution) Ptr() *Resolution {
	return &v
}

type NullableResolution struct {
	value *Resolution
	isSet bool
}

func (v NullableResolution) Get() *Resolution {
	return v.value
}

func (v *NullableResolution) Set(val *Resolution) {
	v.value = val
	v.isSet = true
}

func (v NullableResolution) IsSet() bool {
	return v.isSet
}

func (v *NullableResolution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolution(val *Resolution) *NullableResolution {
	return &NullableResolution{value: val, isSet: true}
}

func (v NullableResolution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

