/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendTxResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendTxResponse{}

// SendTxResponse struct for SendTxResponse
type SendTxResponse struct {
	// DTO.TRANSACTION.SEND.SIGNATURE
	Signature string `json:"signature"`
	// DTO.TRANSACTION.SEND.ELAPSED_TIME
	ElapsedTime int64 `json:"elapsedTime"`
	// DTO.TRANSACTION.SEND.JOB_ID
	JobId string `json:"jobId"`
}

type _SendTxResponse SendTxResponse

// NewSendTxResponse instantiates a new SendTxResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendTxResponse(signature string, elapsedTime int64, jobId string) *SendTxResponse {
	this := SendTxResponse{}
	this.Signature = signature
	this.ElapsedTime = elapsedTime
	this.JobId = jobId
	return &this
}

// NewSendTxResponseWithDefaults instantiates a new SendTxResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendTxResponseWithDefaults() *SendTxResponse {
	this := SendTxResponse{}
	return &this
}

// GetSignature returns the Signature field value
func (o *SendTxResponse) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *SendTxResponse) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *SendTxResponse) SetSignature(v string) {
	o.Signature = v
}

// GetElapsedTime returns the ElapsedTime field value
func (o *SendTxResponse) GetElapsedTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ElapsedTime
}

// GetElapsedTimeOk returns a tuple with the ElapsedTime field value
// and a boolean to check if the value has been set.
func (o *SendTxResponse) GetElapsedTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ElapsedTime, true
}

// SetElapsedTime sets field value
func (o *SendTxResponse) SetElapsedTime(v int64) {
	o.ElapsedTime = v
}

// GetJobId returns the JobId field value
func (o *SendTxResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *SendTxResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *SendTxResponse) SetJobId(v string) {
	o.JobId = v
}

func (o SendTxResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendTxResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signature"] = o.Signature
	toSerialize["elapsedTime"] = o.ElapsedTime
	toSerialize["jobId"] = o.JobId
	return toSerialize, nil
}

func (o *SendTxResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signature",
		"elapsedTime",
		"jobId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendTxResponse := _SendTxResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendTxResponse)

	if err != nil {
		return err
	}

	*o = SendTxResponse(varSendTxResponse)

	return err
}

type NullableSendTxResponse struct {
	value *SendTxResponse
	isSet bool
}

func (v NullableSendTxResponse) Get() *SendTxResponse {
	return v.value
}

func (v *NullableSendTxResponse) Set(val *SendTxResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendTxResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendTxResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendTxResponse(val *SendTxResponse) *NullableSendTxResponse {
	return &NullableSendTxResponse{value: val, isSet: true}
}

func (v NullableSendTxResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendTxResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

