/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterAddressRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterAddressRequest{}

// RegisterAddressRequest struct for RegisterAddressRequest
type RegisterAddressRequest struct {
	// DTO.KYT.REGISTER_ADDRESS_REQUEST.ADDRESS
	Address string `json:"address"`
}

type _RegisterAddressRequest RegisterAddressRequest

// NewRegisterAddressRequest instantiates a new RegisterAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterAddressRequest(address string) *RegisterAddressRequest {
	this := RegisterAddressRequest{}
	this.Address = address
	return &this
}

// NewRegisterAddressRequestWithDefaults instantiates a new RegisterAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterAddressRequestWithDefaults() *RegisterAddressRequest {
	this := RegisterAddressRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *RegisterAddressRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *RegisterAddressRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *RegisterAddressRequest) SetAddress(v string) {
	o.Address = v
}

func (o RegisterAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterAddressRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *RegisterAddressRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterAddressRequest := _RegisterAddressRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterAddressRequest)

	if err != nil {
		return err
	}

	*o = RegisterAddressRequest(varRegisterAddressRequest)

	return err
}

type NullableRegisterAddressRequest struct {
	value *RegisterAddressRequest
	isSet bool
}

func (v NullableRegisterAddressRequest) Get() *RegisterAddressRequest {
	return v.value
}

func (v *NullableRegisterAddressRequest) Set(val *RegisterAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterAddressRequest(val *RegisterAddressRequest) *NullableRegisterAddressRequest {
	return &NullableRegisterAddressRequest{value: val, isSet: true}
}

func (v NullableRegisterAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


