/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TokenTrader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenTrader{}

// TokenTrader struct for TokenTrader
type TokenTrader struct {
	// DTO.TOKEN_TRADER.ADDRESS
	Address string `json:"address"`
	// DTO.TOKEN_TRADER.TRANSACTION_SIGNATURE
	TransactionSignature *string `json:"transactionSignature,omitempty"`
	// DTO.TOKEN_TRADER.BLOCK_HASH
	BlockHash *string `json:"blockHash,omitempty"`
	// DTO.TOKEN_TRADER.BLOCK_HEIGHT
	BlockHeight *float32 `json:"blockHeight,omitempty"`
	// DTO.TOKEN_TRADER.BLOCK_SLOT
	BlockSlot *float32 `json:"blockSlot,omitempty"`
	// DTO.TOKEN_TRADER.BLOCK_TIMESTAMP
	BlockTimestamp *time.Time `json:"blockTimestamp,omitempty"`
	// DTO.TOKEN_TRADER.ONCHAIN_CREATED_AT
	OnchainCreatedAt map[string]interface{} `json:"onchainCreatedAt,omitempty"`
	// DTO.TOKEN_TRADER.TRADE_COUNT
	TradeCount *float32 `json:"tradeCount,omitempty"`
	// DTO.TOKEN_TRADER.TRADE_AMOUNT_IN_NATIVE
	TradeAmountInNative *float32 `json:"tradeAmountInNative,omitempty"`
	// DTO.TOKEN_TRADER.TRADE_AMOUNT_IN_USD
	TradeAmountInUsd *float32 `json:"tradeAmountInUsd,omitempty"`
	// DTO.TOKEN_TRADER.PERCENTILE_RANK_TRADE_COUNT
	PercentileRankTradeCount *float32 `json:"percentileRankTradeCount,omitempty"`
	// DTO.TOKEN_TRADER.PERCENTILE_RANK_TRADE_AMOUNT_IN_USD
	PercentileRankTradeAmountInUsd *float32 `json:"percentileRankTradeAmountInUsd,omitempty"`
	// DTO.TOKEN_TRADER.RANK_TRADE_AMOUNT_IN_USD
	RankTradeAmountInUsd *float32 `json:"rankTradeAmountInUsd,omitempty"`
}

type _TokenTrader TokenTrader

// NewTokenTrader instantiates a new TokenTrader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenTrader(address string) *TokenTrader {
	this := TokenTrader{}
	this.Address = address
	return &this
}

// NewTokenTraderWithDefaults instantiates a new TokenTrader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenTraderWithDefaults() *TokenTrader {
	this := TokenTrader{}
	return &this
}

// GetAddress returns the Address field value
func (o *TokenTrader) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *TokenTrader) SetAddress(v string) {
	o.Address = v
}

// GetTransactionSignature returns the TransactionSignature field value if set, zero value otherwise.
func (o *TokenTrader) GetTransactionSignature() string {
	if o == nil || IsNil(o.TransactionSignature) {
		var ret string
		return ret
	}
	return *o.TransactionSignature
}

// GetTransactionSignatureOk returns a tuple with the TransactionSignature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetTransactionSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionSignature) {
		return nil, false
	}
	return o.TransactionSignature, true
}

// HasTransactionSignature returns a boolean if a field has been set.
func (o *TokenTrader) HasTransactionSignature() bool {
	if o != nil && !IsNil(o.TransactionSignature) {
		return true
	}

	return false
}

// SetTransactionSignature gets a reference to the given string and assigns it to the TransactionSignature field.
func (o *TokenTrader) SetTransactionSignature(v string) {
	o.TransactionSignature = &v
}

// GetBlockHash returns the BlockHash field value if set, zero value otherwise.
func (o *TokenTrader) GetBlockHash() string {
	if o == nil || IsNil(o.BlockHash) {
		var ret string
		return ret
	}
	return *o.BlockHash
}

// GetBlockHashOk returns a tuple with the BlockHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetBlockHashOk() (*string, bool) {
	if o == nil || IsNil(o.BlockHash) {
		return nil, false
	}
	return o.BlockHash, true
}

// HasBlockHash returns a boolean if a field has been set.
func (o *TokenTrader) HasBlockHash() bool {
	if o != nil && !IsNil(o.BlockHash) {
		return true
	}

	return false
}

// SetBlockHash gets a reference to the given string and assigns it to the BlockHash field.
func (o *TokenTrader) SetBlockHash(v string) {
	o.BlockHash = &v
}

// GetBlockHeight returns the BlockHeight field value if set, zero value otherwise.
func (o *TokenTrader) GetBlockHeight() float32 {
	if o == nil || IsNil(o.BlockHeight) {
		var ret float32
		return ret
	}
	return *o.BlockHeight
}

// GetBlockHeightOk returns a tuple with the BlockHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetBlockHeightOk() (*float32, bool) {
	if o == nil || IsNil(o.BlockHeight) {
		return nil, false
	}
	return o.BlockHeight, true
}

// HasBlockHeight returns a boolean if a field has been set.
func (o *TokenTrader) HasBlockHeight() bool {
	if o != nil && !IsNil(o.BlockHeight) {
		return true
	}

	return false
}

// SetBlockHeight gets a reference to the given float32 and assigns it to the BlockHeight field.
func (o *TokenTrader) SetBlockHeight(v float32) {
	o.BlockHeight = &v
}

// GetBlockSlot returns the BlockSlot field value if set, zero value otherwise.
func (o *TokenTrader) GetBlockSlot() float32 {
	if o == nil || IsNil(o.BlockSlot) {
		var ret float32
		return ret
	}
	return *o.BlockSlot
}

// GetBlockSlotOk returns a tuple with the BlockSlot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetBlockSlotOk() (*float32, bool) {
	if o == nil || IsNil(o.BlockSlot) {
		return nil, false
	}
	return o.BlockSlot, true
}

// HasBlockSlot returns a boolean if a field has been set.
func (o *TokenTrader) HasBlockSlot() bool {
	if o != nil && !IsNil(o.BlockSlot) {
		return true
	}

	return false
}

// SetBlockSlot gets a reference to the given float32 and assigns it to the BlockSlot field.
func (o *TokenTrader) SetBlockSlot(v float32) {
	o.BlockSlot = &v
}

// GetBlockTimestamp returns the BlockTimestamp field value if set, zero value otherwise.
func (o *TokenTrader) GetBlockTimestamp() time.Time {
	if o == nil || IsNil(o.BlockTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.BlockTimestamp
}

// GetBlockTimestampOk returns a tuple with the BlockTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetBlockTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.BlockTimestamp) {
		return nil, false
	}
	return o.BlockTimestamp, true
}

// HasBlockTimestamp returns a boolean if a field has been set.
func (o *TokenTrader) HasBlockTimestamp() bool {
	if o != nil && !IsNil(o.BlockTimestamp) {
		return true
	}

	return false
}

// SetBlockTimestamp gets a reference to the given time.Time and assigns it to the BlockTimestamp field.
func (o *TokenTrader) SetBlockTimestamp(v time.Time) {
	o.BlockTimestamp = &v
}

// GetOnchainCreatedAt returns the OnchainCreatedAt field value if set, zero value otherwise.
func (o *TokenTrader) GetOnchainCreatedAt() map[string]interface{} {
	if o == nil || IsNil(o.OnchainCreatedAt) {
		var ret map[string]interface{}
		return ret
	}
	return o.OnchainCreatedAt
}

// GetOnchainCreatedAtOk returns a tuple with the OnchainCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetOnchainCreatedAtOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OnchainCreatedAt) {
		return map[string]interface{}{}, false
	}
	return o.OnchainCreatedAt, true
}

// HasOnchainCreatedAt returns a boolean if a field has been set.
func (o *TokenTrader) HasOnchainCreatedAt() bool {
	if o != nil && !IsNil(o.OnchainCreatedAt) {
		return true
	}

	return false
}

// SetOnchainCreatedAt gets a reference to the given map[string]interface{} and assigns it to the OnchainCreatedAt field.
func (o *TokenTrader) SetOnchainCreatedAt(v map[string]interface{}) {
	o.OnchainCreatedAt = v
}

// GetTradeCount returns the TradeCount field value if set, zero value otherwise.
func (o *TokenTrader) GetTradeCount() float32 {
	if o == nil || IsNil(o.TradeCount) {
		var ret float32
		return ret
	}
	return *o.TradeCount
}

// GetTradeCountOk returns a tuple with the TradeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetTradeCountOk() (*float32, bool) {
	if o == nil || IsNil(o.TradeCount) {
		return nil, false
	}
	return o.TradeCount, true
}

// HasTradeCount returns a boolean if a field has been set.
func (o *TokenTrader) HasTradeCount() bool {
	if o != nil && !IsNil(o.TradeCount) {
		return true
	}

	return false
}

// SetTradeCount gets a reference to the given float32 and assigns it to the TradeCount field.
func (o *TokenTrader) SetTradeCount(v float32) {
	o.TradeCount = &v
}

// GetTradeAmountInNative returns the TradeAmountInNative field value if set, zero value otherwise.
func (o *TokenTrader) GetTradeAmountInNative() float32 {
	if o == nil || IsNil(o.TradeAmountInNative) {
		var ret float32
		return ret
	}
	return *o.TradeAmountInNative
}

// GetTradeAmountInNativeOk returns a tuple with the TradeAmountInNative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetTradeAmountInNativeOk() (*float32, bool) {
	if o == nil || IsNil(o.TradeAmountInNative) {
		return nil, false
	}
	return o.TradeAmountInNative, true
}

// HasTradeAmountInNative returns a boolean if a field has been set.
func (o *TokenTrader) HasTradeAmountInNative() bool {
	if o != nil && !IsNil(o.TradeAmountInNative) {
		return true
	}

	return false
}

// SetTradeAmountInNative gets a reference to the given float32 and assigns it to the TradeAmountInNative field.
func (o *TokenTrader) SetTradeAmountInNative(v float32) {
	o.TradeAmountInNative = &v
}

// GetTradeAmountInUsd returns the TradeAmountInUsd field value if set, zero value otherwise.
func (o *TokenTrader) GetTradeAmountInUsd() float32 {
	if o == nil || IsNil(o.TradeAmountInUsd) {
		var ret float32
		return ret
	}
	return *o.TradeAmountInUsd
}

// GetTradeAmountInUsdOk returns a tuple with the TradeAmountInUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetTradeAmountInUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.TradeAmountInUsd) {
		return nil, false
	}
	return o.TradeAmountInUsd, true
}

// HasTradeAmountInUsd returns a boolean if a field has been set.
func (o *TokenTrader) HasTradeAmountInUsd() bool {
	if o != nil && !IsNil(o.TradeAmountInUsd) {
		return true
	}

	return false
}

// SetTradeAmountInUsd gets a reference to the given float32 and assigns it to the TradeAmountInUsd field.
func (o *TokenTrader) SetTradeAmountInUsd(v float32) {
	o.TradeAmountInUsd = &v
}

// GetPercentileRankTradeCount returns the PercentileRankTradeCount field value if set, zero value otherwise.
func (o *TokenTrader) GetPercentileRankTradeCount() float32 {
	if o == nil || IsNil(o.PercentileRankTradeCount) {
		var ret float32
		return ret
	}
	return *o.PercentileRankTradeCount
}

// GetPercentileRankTradeCountOk returns a tuple with the PercentileRankTradeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetPercentileRankTradeCountOk() (*float32, bool) {
	if o == nil || IsNil(o.PercentileRankTradeCount) {
		return nil, false
	}
	return o.PercentileRankTradeCount, true
}

// HasPercentileRankTradeCount returns a boolean if a field has been set.
func (o *TokenTrader) HasPercentileRankTradeCount() bool {
	if o != nil && !IsNil(o.PercentileRankTradeCount) {
		return true
	}

	return false
}

// SetPercentileRankTradeCount gets a reference to the given float32 and assigns it to the PercentileRankTradeCount field.
func (o *TokenTrader) SetPercentileRankTradeCount(v float32) {
	o.PercentileRankTradeCount = &v
}

// GetPercentileRankTradeAmountInUsd returns the PercentileRankTradeAmountInUsd field value if set, zero value otherwise.
func (o *TokenTrader) GetPercentileRankTradeAmountInUsd() float32 {
	if o == nil || IsNil(o.PercentileRankTradeAmountInUsd) {
		var ret float32
		return ret
	}
	return *o.PercentileRankTradeAmountInUsd
}

// GetPercentileRankTradeAmountInUsdOk returns a tuple with the PercentileRankTradeAmountInUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetPercentileRankTradeAmountInUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.PercentileRankTradeAmountInUsd) {
		return nil, false
	}
	return o.PercentileRankTradeAmountInUsd, true
}

// HasPercentileRankTradeAmountInUsd returns a boolean if a field has been set.
func (o *TokenTrader) HasPercentileRankTradeAmountInUsd() bool {
	if o != nil && !IsNil(o.PercentileRankTradeAmountInUsd) {
		return true
	}

	return false
}

// SetPercentileRankTradeAmountInUsd gets a reference to the given float32 and assigns it to the PercentileRankTradeAmountInUsd field.
func (o *TokenTrader) SetPercentileRankTradeAmountInUsd(v float32) {
	o.PercentileRankTradeAmountInUsd = &v
}

// GetRankTradeAmountInUsd returns the RankTradeAmountInUsd field value if set, zero value otherwise.
func (o *TokenTrader) GetRankTradeAmountInUsd() float32 {
	if o == nil || IsNil(o.RankTradeAmountInUsd) {
		var ret float32
		return ret
	}
	return *o.RankTradeAmountInUsd
}

// GetRankTradeAmountInUsdOk returns a tuple with the RankTradeAmountInUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrader) GetRankTradeAmountInUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.RankTradeAmountInUsd) {
		return nil, false
	}
	return o.RankTradeAmountInUsd, true
}

// HasRankTradeAmountInUsd returns a boolean if a field has been set.
func (o *TokenTrader) HasRankTradeAmountInUsd() bool {
	if o != nil && !IsNil(o.RankTradeAmountInUsd) {
		return true
	}

	return false
}

// SetRankTradeAmountInUsd gets a reference to the given float32 and assigns it to the RankTradeAmountInUsd field.
func (o *TokenTrader) SetRankTradeAmountInUsd(v float32) {
	o.RankTradeAmountInUsd = &v
}

func (o TokenTrader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenTrader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if !IsNil(o.TransactionSignature) {
		toSerialize["transactionSignature"] = o.TransactionSignature
	}
	if !IsNil(o.BlockHash) {
		toSerialize["blockHash"] = o.BlockHash
	}
	if !IsNil(o.BlockHeight) {
		toSerialize["blockHeight"] = o.BlockHeight
	}
	if !IsNil(o.BlockSlot) {
		toSerialize["blockSlot"] = o.BlockSlot
	}
	if !IsNil(o.BlockTimestamp) {
		toSerialize["blockTimestamp"] = o.BlockTimestamp
	}
	if !IsNil(o.OnchainCreatedAt) {
		toSerialize["onchainCreatedAt"] = o.OnchainCreatedAt
	}
	if !IsNil(o.TradeCount) {
		toSerialize["tradeCount"] = o.TradeCount
	}
	if !IsNil(o.TradeAmountInNative) {
		toSerialize["tradeAmountInNative"] = o.TradeAmountInNative
	}
	if !IsNil(o.TradeAmountInUsd) {
		toSerialize["tradeAmountInUsd"] = o.TradeAmountInUsd
	}
	if !IsNil(o.PercentileRankTradeCount) {
		toSerialize["percentileRankTradeCount"] = o.PercentileRankTradeCount
	}
	if !IsNil(o.PercentileRankTradeAmountInUsd) {
		toSerialize["percentileRankTradeAmountInUsd"] = o.PercentileRankTradeAmountInUsd
	}
	if !IsNil(o.RankTradeAmountInUsd) {
		toSerialize["rankTradeAmountInUsd"] = o.RankTradeAmountInUsd
	}
	return toSerialize, nil
}

func (o *TokenTrader) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenTrader := _TokenTrader{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenTrader)

	if err != nil {
		return err
	}

	*o = TokenTrader(varTokenTrader)

	return err
}

type NullableTokenTrader struct {
	value *TokenTrader
	isSet bool
}

func (v NullableTokenTrader) Get() *TokenTrader {
	return v.value
}

func (v *NullableTokenTrader) Set(val *TokenTrader) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTrader) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTrader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTrader(val *TokenTrader) *NullableTokenTrader {
	return &NullableTokenTrader{value: val, isSet: true}
}

func (v NullableTokenTrader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTrader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

