/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RedPacketReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedPacketReply{}

// RedPacketReply struct for RedPacketReply
type RedPacketReply struct {
	// Base64 encoded transaction
	TxSerialize string `json:"txSerialize"`
}

type _RedPacketReply RedPacketReply

// NewRedPacketReply instantiates a new RedPacketReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedPacketReply(txSerialize string) *RedPacketReply {
	this := RedPacketReply{}
	this.TxSerialize = txSerialize
	return &this
}

// NewRedPacketReplyWithDefaults instantiates a new RedPacketReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedPacketReplyWithDefaults() *RedPacketReply {
	this := RedPacketReply{}
	return &this
}

// GetTxSerialize returns the TxSerialize field value
func (o *RedPacketReply) GetTxSerialize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxSerialize
}

// GetTxSerializeOk returns a tuple with the TxSerialize field value
// and a boolean to check if the value has been set.
func (o *RedPacketReply) GetTxSerializeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxSerialize, true
}

// SetTxSerialize sets field value
func (o *RedPacketReply) SetTxSerialize(v string) {
	o.TxSerialize = v
}

func (o RedPacketReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedPacketReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["txSerialize"] = o.TxSerialize
	return toSerialize, nil
}

func (o *RedPacketReply) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"txSerialize",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRedPacketReply := _RedPacketReply{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRedPacketReply)

	if err != nil {
		return err
	}

	*o = RedPacketReply(varRedPacketReply)

	return err
}

type NullableRedPacketReply struct {
	value *RedPacketReply
	isSet bool
}

func (v NullableRedPacketReply) Get() *RedPacketReply {
	return v.value
}

func (v *NullableRedPacketReply) Set(val *RedPacketReply) {
	v.value = val
	v.isSet = true
}

func (v NullableRedPacketReply) IsSet() bool {
	return v.isSet
}

func (v *NullableRedPacketReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedPacketReply(val *RedPacketReply) *NullableRedPacketReply {
	return &NullableRedPacketReply{value: val, isSet: true}
}

func (v NullableRedPacketReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedPacketReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

