/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRedPacketReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRedPacketReply{}

// CreateRedPacketReply struct for CreateRedPacketReply
type CreateRedPacketReply struct {
	// DTO.RED_PACKET.SERIALIZED_TX
	TxSerialize string `json:"txSerialize"`
	// DTO.RED_PACKET.SHARE_ID
	ShareId string `json:"shareId"`
}

type _CreateRedPacketReply CreateRedPacketReply

// NewCreateRedPacketReply instantiates a new CreateRedPacketReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRedPacketReply(txSerialize string, shareId string) *CreateRedPacketReply {
	this := CreateRedPacketReply{}
	this.TxSerialize = txSerialize
	this.ShareId = shareId
	return &this
}

// NewCreateRedPacketReplyWithDefaults instantiates a new CreateRedPacketReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRedPacketReplyWithDefaults() *CreateRedPacketReply {
	this := CreateRedPacketReply{}
	return &this
}

// GetTxSerialize returns the TxSerialize field value
func (o *CreateRedPacketReply) GetTxSerialize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxSerialize
}

// GetTxSerializeOk returns a tuple with the TxSerialize field value
// and a boolean to check if the value has been set.
func (o *CreateRedPacketReply) GetTxSerializeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxSerialize, true
}

// SetTxSerialize sets field value
func (o *CreateRedPacketReply) SetTxSerialize(v string) {
	o.TxSerialize = v
}

// GetShareId returns the ShareId field value
func (o *CreateRedPacketReply) GetShareId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShareId
}

// GetShareIdOk returns a tuple with the ShareId field value
// and a boolean to check if the value has been set.
func (o *CreateRedPacketReply) GetShareIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShareId, true
}

// SetShareId sets field value
func (o *CreateRedPacketReply) SetShareId(v string) {
	o.ShareId = v
}

func (o CreateRedPacketReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRedPacketReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["txSerialize"] = o.TxSerialize
	toSerialize["shareId"] = o.ShareId
	return toSerialize, nil
}

func (o *CreateRedPacketReply) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"txSerialize",
		"shareId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRedPacketReply := _CreateRedPacketReply{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRedPacketReply)

	if err != nil {
		return err
	}

	*o = CreateRedPacketReply(varCreateRedPacketReply)

	return err
}

type NullableCreateRedPacketReply struct {
	value *CreateRedPacketReply
	isSet bool
}

func (v NullableCreateRedPacketReply) Get() *CreateRedPacketReply {
	return v.value
}

func (v *NullableCreateRedPacketReply) Set(val *CreateRedPacketReply) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRedPacketReply) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRedPacketReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRedPacketReply(val *CreateRedPacketReply) *NullableCreateRedPacketReply {
	return &NullableCreateRedPacketReply{value: val, isSet: true}
}

func (v NullableCreateRedPacketReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRedPacketReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

