/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SwapRouteInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwapRouteInput{}

// SwapRouteInput struct for SwapRouteInput
type SwapRouteInput struct {
	// DEX identifier for the trade
	Dex string `json:"dex"`
	// Public key of the wallet initiating the transaction
	UserAddress string `json:"userAddress"`
	// Priority fee in SOL to increase transaction processing speed
	PriorityFee *string `json:"priorityFee,omitempty"`
	// Amount to swap. Use \"auto\" for full balance or percentage like \"50%\"
	Amount string `json:"amount"`
	// Swap direction mode
	SwapMode string `json:"swapMode"`
	// Slippage tolerance percentage
	Slippage int64 `json:"slippage"`
	// Input Mint, the base token address
	InputMint *string `json:"inputMint,omitempty"`
	// Ouput Mint, the quote token address
	OutputMint *string `json:"outputMint,omitempty"`
	// Recipient wallet address for the swap
	RecipientAddress *string `json:"recipientAddress,omitempty"`
	// Permit data for the swap
	Permit *string `json:"permit,omitempty"`
	// Swap deadline timestamp
	Deadline *int64 `json:"deadline,omitempty"`
	// Tip fee in SOL to increase transaction processing speed
	TipFee *string `json:"tipFee,omitempty"`
	// Whether to enable anti-MEV protection
	IsAntiMev *bool `json:"isAntiMev,omitempty"`
}

type _SwapRouteInput SwapRouteInput

// NewSwapRouteInput instantiates a new SwapRouteInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwapRouteInput(dex string, userAddress string, amount string, swapMode string, slippage int64) *SwapRouteInput {
	this := SwapRouteInput{}
	this.Dex = dex
	this.UserAddress = userAddress
	this.Amount = amount
	this.SwapMode = swapMode
	this.Slippage = slippage
	var isAntiMev bool = false
	this.IsAntiMev = &isAntiMev
	return &this
}

// NewSwapRouteInputWithDefaults instantiates a new SwapRouteInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwapRouteInputWithDefaults() *SwapRouteInput {
	this := SwapRouteInput{}
	var slippage int64 = 5
	this.Slippage = slippage
	var isAntiMev bool = false
	this.IsAntiMev = &isAntiMev
	return &this
}

// GetDex returns the Dex field value
func (o *SwapRouteInput) GetDex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dex
}

// GetDexOk returns a tuple with the Dex field value
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetDexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dex, true
}

// SetDex sets field value
func (o *SwapRouteInput) SetDex(v string) {
	o.Dex = v
}

// GetUserAddress returns the UserAddress field value
func (o *SwapRouteInput) GetUserAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAddress
}

// GetUserAddressOk returns a tuple with the UserAddress field value
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetUserAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserAddress, true
}

// SetUserAddress sets field value
func (o *SwapRouteInput) SetUserAddress(v string) {
	o.UserAddress = v
}

// GetPriorityFee returns the PriorityFee field value if set, zero value otherwise.
func (o *SwapRouteInput) GetPriorityFee() string {
	if o == nil || IsNil(o.PriorityFee) {
		var ret string
		return ret
	}
	return *o.PriorityFee
}

// GetPriorityFeeOk returns a tuple with the PriorityFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetPriorityFeeOk() (*string, bool) {
	if o == nil || IsNil(o.PriorityFee) {
		return nil, false
	}
	return o.PriorityFee, true
}

// HasPriorityFee returns a boolean if a field has been set.
func (o *SwapRouteInput) HasPriorityFee() bool {
	if o != nil && !IsNil(o.PriorityFee) {
		return true
	}

	return false
}

// SetPriorityFee gets a reference to the given string and assigns it to the PriorityFee field.
func (o *SwapRouteInput) SetPriorityFee(v string) {
	o.PriorityFee = &v
}

// GetAmount returns the Amount field value
func (o *SwapRouteInput) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *SwapRouteInput) SetAmount(v string) {
	o.Amount = v
}

// GetSwapMode returns the SwapMode field value
func (o *SwapRouteInput) GetSwapMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwapMode
}

// GetSwapModeOk returns a tuple with the SwapMode field value
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetSwapModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapMode, true
}

// SetSwapMode sets field value
func (o *SwapRouteInput) SetSwapMode(v string) {
	o.SwapMode = v
}

// GetSlippage returns the Slippage field value
func (o *SwapRouteInput) GetSlippage() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Slippage
}

// GetSlippageOk returns a tuple with the Slippage field value
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetSlippageOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slippage, true
}

// SetSlippage sets field value
func (o *SwapRouteInput) SetSlippage(v int64) {
	o.Slippage = v
}

// GetInputMint returns the InputMint field value if set, zero value otherwise.
func (o *SwapRouteInput) GetInputMint() string {
	if o == nil || IsNil(o.InputMint) {
		var ret string
		return ret
	}
	return *o.InputMint
}

// GetInputMintOk returns a tuple with the InputMint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetInputMintOk() (*string, bool) {
	if o == nil || IsNil(o.InputMint) {
		return nil, false
	}
	return o.InputMint, true
}

// HasInputMint returns a boolean if a field has been set.
func (o *SwapRouteInput) HasInputMint() bool {
	if o != nil && !IsNil(o.InputMint) {
		return true
	}

	return false
}

// SetInputMint gets a reference to the given string and assigns it to the InputMint field.
func (o *SwapRouteInput) SetInputMint(v string) {
	o.InputMint = &v
}

// GetOutputMint returns the OutputMint field value if set, zero value otherwise.
func (o *SwapRouteInput) GetOutputMint() string {
	if o == nil || IsNil(o.OutputMint) {
		var ret string
		return ret
	}
	return *o.OutputMint
}

// GetOutputMintOk returns a tuple with the OutputMint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetOutputMintOk() (*string, bool) {
	if o == nil || IsNil(o.OutputMint) {
		return nil, false
	}
	return o.OutputMint, true
}

// HasOutputMint returns a boolean if a field has been set.
func (o *SwapRouteInput) HasOutputMint() bool {
	if o != nil && !IsNil(o.OutputMint) {
		return true
	}

	return false
}

// SetOutputMint gets a reference to the given string and assigns it to the OutputMint field.
func (o *SwapRouteInput) SetOutputMint(v string) {
	o.OutputMint = &v
}

// GetRecipientAddress returns the RecipientAddress field value if set, zero value otherwise.
func (o *SwapRouteInput) GetRecipientAddress() string {
	if o == nil || IsNil(o.RecipientAddress) {
		var ret string
		return ret
	}
	return *o.RecipientAddress
}

// GetRecipientAddressOk returns a tuple with the RecipientAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetRecipientAddressOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientAddress) {
		return nil, false
	}
	return o.RecipientAddress, true
}

// HasRecipientAddress returns a boolean if a field has been set.
func (o *SwapRouteInput) HasRecipientAddress() bool {
	if o != nil && !IsNil(o.RecipientAddress) {
		return true
	}

	return false
}

// SetRecipientAddress gets a reference to the given string and assigns it to the RecipientAddress field.
func (o *SwapRouteInput) SetRecipientAddress(v string) {
	o.RecipientAddress = &v
}

// GetPermit returns the Permit field value if set, zero value otherwise.
func (o *SwapRouteInput) GetPermit() string {
	if o == nil || IsNil(o.Permit) {
		var ret string
		return ret
	}
	return *o.Permit
}

// GetPermitOk returns a tuple with the Permit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetPermitOk() (*string, bool) {
	if o == nil || IsNil(o.Permit) {
		return nil, false
	}
	return o.Permit, true
}

// HasPermit returns a boolean if a field has been set.
func (o *SwapRouteInput) HasPermit() bool {
	if o != nil && !IsNil(o.Permit) {
		return true
	}

	return false
}

// SetPermit gets a reference to the given string and assigns it to the Permit field.
func (o *SwapRouteInput) SetPermit(v string) {
	o.Permit = &v
}

// GetDeadline returns the Deadline field value if set, zero value otherwise.
func (o *SwapRouteInput) GetDeadline() int64 {
	if o == nil || IsNil(o.Deadline) {
		var ret int64
		return ret
	}
	return *o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetDeadlineOk() (*int64, bool) {
	if o == nil || IsNil(o.Deadline) {
		return nil, false
	}
	return o.Deadline, true
}

// HasDeadline returns a boolean if a field has been set.
func (o *SwapRouteInput) HasDeadline() bool {
	if o != nil && !IsNil(o.Deadline) {
		return true
	}

	return false
}

// SetDeadline gets a reference to the given int64 and assigns it to the Deadline field.
func (o *SwapRouteInput) SetDeadline(v int64) {
	o.Deadline = &v
}

// GetTipFee returns the TipFee field value if set, zero value otherwise.
func (o *SwapRouteInput) GetTipFee() string {
	if o == nil || IsNil(o.TipFee) {
		var ret string
		return ret
	}
	return *o.TipFee
}

// GetTipFeeOk returns a tuple with the TipFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetTipFeeOk() (*string, bool) {
	if o == nil || IsNil(o.TipFee) {
		return nil, false
	}
	return o.TipFee, true
}

// HasTipFee returns a boolean if a field has been set.
func (o *SwapRouteInput) HasTipFee() bool {
	if o != nil && !IsNil(o.TipFee) {
		return true
	}

	return false
}

// SetTipFee gets a reference to the given string and assigns it to the TipFee field.
func (o *SwapRouteInput) SetTipFee(v string) {
	o.TipFee = &v
}

// GetIsAntiMev returns the IsAntiMev field value if set, zero value otherwise.
func (o *SwapRouteInput) GetIsAntiMev() bool {
	if o == nil || IsNil(o.IsAntiMev) {
		var ret bool
		return ret
	}
	return *o.IsAntiMev
}

// GetIsAntiMevOk returns a tuple with the IsAntiMev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRouteInput) GetIsAntiMevOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAntiMev) {
		return nil, false
	}
	return o.IsAntiMev, true
}

// HasIsAntiMev returns a boolean if a field has been set.
func (o *SwapRouteInput) HasIsAntiMev() bool {
	if o != nil && !IsNil(o.IsAntiMev) {
		return true
	}

	return false
}

// SetIsAntiMev gets a reference to the given bool and assigns it to the IsAntiMev field.
func (o *SwapRouteInput) SetIsAntiMev(v bool) {
	o.IsAntiMev = &v
}

func (o SwapRouteInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwapRouteInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dex"] = o.Dex
	toSerialize["userAddress"] = o.UserAddress
	if !IsNil(o.PriorityFee) {
		toSerialize["priorityFee"] = o.PriorityFee
	}
	toSerialize["amount"] = o.Amount
	toSerialize["swapMode"] = o.SwapMode
	toSerialize["slippage"] = o.Slippage
	if !IsNil(o.InputMint) {
		toSerialize["inputMint"] = o.InputMint
	}
	if !IsNil(o.OutputMint) {
		toSerialize["outputMint"] = o.OutputMint
	}
	if !IsNil(o.RecipientAddress) {
		toSerialize["recipientAddress"] = o.RecipientAddress
	}
	if !IsNil(o.Permit) {
		toSerialize["permit"] = o.Permit
	}
	if !IsNil(o.Deadline) {
		toSerialize["deadline"] = o.Deadline
	}
	if !IsNil(o.TipFee) {
		toSerialize["tipFee"] = o.TipFee
	}
	if !IsNil(o.IsAntiMev) {
		toSerialize["isAntiMev"] = o.IsAntiMev
	}
	return toSerialize, nil
}

func (o *SwapRouteInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dex",
		"userAddress",
		"amount",
		"swapMode",
		"slippage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSwapRouteInput := _SwapRouteInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSwapRouteInput)

	if err != nil {
		return err
	}

	*o = SwapRouteInput(varSwapRouteInput)

	return err
}

type NullableSwapRouteInput struct {
	value *SwapRouteInput
	isSet bool
}

func (v NullableSwapRouteInput) Get() *SwapRouteInput {
	return v.value
}

func (v *NullableSwapRouteInput) Set(val *SwapRouteInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSwapRouteInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSwapRouteInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwapRouteInput(val *SwapRouteInput) *NullableSwapRouteInput {
	return &NullableSwapRouteInput{value: val, isSet: true}
}

func (v NullableSwapRouteInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwapRouteInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

