/*
Dex Aggregator API

Dex Aggregator API ⚡️

API version: 1.0
Contact: ai@sx.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RedPacketClaimsPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedPacketClaimsPage{}

// RedPacketClaimsPage struct for RedPacketClaimsPage
type RedPacketClaimsPage struct {
	// DTO.PAGE.TOTAL
	Total float32 `json:"total"`
	// DTO.PAGE.HAS_NEXT
	HasNextPage bool `json:"hasNextPage"`
	// DTO.PAGE.START_CURSOR
	StartCursor string `json:"startCursor"`
	// DTO.PAGE.END_CURSOR
	EndCursor string `json:"endCursor"`
	// Array of claim records
	Records []RedPacketClaimDTO `json:"records"`
}

type _RedPacketClaimsPage RedPacketClaimsPage

// NewRedPacketClaimsPage instantiates a new RedPacketClaimsPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedPacketClaimsPage(total float32, hasNextPage bool, startCursor string, endCursor string, records []RedPacketClaimDTO) *RedPacketClaimsPage {
	this := RedPacketClaimsPage{}
	this.Total = total
	this.HasNextPage = hasNextPage
	this.StartCursor = startCursor
	this.EndCursor = endCursor
	this.Records = records
	return &this
}

// NewRedPacketClaimsPageWithDefaults instantiates a new RedPacketClaimsPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedPacketClaimsPageWithDefaults() *RedPacketClaimsPage {
	this := RedPacketClaimsPage{}
	return &this
}

// GetTotal returns the Total field value
func (o *RedPacketClaimsPage) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *RedPacketClaimsPage) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *RedPacketClaimsPage) SetTotal(v float32) {
	o.Total = v
}

// GetHasNextPage returns the HasNextPage field value
func (o *RedPacketClaimsPage) GetHasNextPage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNextPage
}

// GetHasNextPageOk returns a tuple with the HasNextPage field value
// and a boolean to check if the value has been set.
func (o *RedPacketClaimsPage) GetHasNextPageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNextPage, true
}

// SetHasNextPage sets field value
func (o *RedPacketClaimsPage) SetHasNextPage(v bool) {
	o.HasNextPage = v
}

// GetStartCursor returns the StartCursor field value
func (o *RedPacketClaimsPage) GetStartCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartCursor
}

// GetStartCursorOk returns a tuple with the StartCursor field value
// and a boolean to check if the value has been set.
func (o *RedPacketClaimsPage) GetStartCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartCursor, true
}

// SetStartCursor sets field value
func (o *RedPacketClaimsPage) SetStartCursor(v string) {
	o.StartCursor = v
}

// GetEndCursor returns the EndCursor field value
func (o *RedPacketClaimsPage) GetEndCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndCursor
}

// GetEndCursorOk returns a tuple with the EndCursor field value
// and a boolean to check if the value has been set.
func (o *RedPacketClaimsPage) GetEndCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndCursor, true
}

// SetEndCursor sets field value
func (o *RedPacketClaimsPage) SetEndCursor(v string) {
	o.EndCursor = v
}

// GetRecords returns the Records field value
func (o *RedPacketClaimsPage) GetRecords() []RedPacketClaimDTO {
	if o == nil {
		var ret []RedPacketClaimDTO
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *RedPacketClaimsPage) GetRecordsOk() ([]RedPacketClaimDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *RedPacketClaimsPage) SetRecords(v []RedPacketClaimDTO) {
	o.Records = v
}

func (o RedPacketClaimsPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedPacketClaimsPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["hasNextPage"] = o.HasNextPage
	toSerialize["startCursor"] = o.StartCursor
	toSerialize["endCursor"] = o.EndCursor
	toSerialize["records"] = o.Records
	return toSerialize, nil
}

func (o *RedPacketClaimsPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"hasNextPage",
		"startCursor",
		"endCursor",
		"records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRedPacketClaimsPage := _RedPacketClaimsPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRedPacketClaimsPage)

	if err != nil {
		return err
	}

	*o = RedPacketClaimsPage(varRedPacketClaimsPage)

	return err
}

type NullableRedPacketClaimsPage struct {
	value *RedPacketClaimsPage
	isSet bool
}

func (v NullableRedPacketClaimsPage) Get() *RedPacketClaimsPage {
	return v.value
}

func (v *NullableRedPacketClaimsPage) Set(val *RedPacketClaimsPage) {
	v.value = val
	v.isSet = true
}

func (v NullableRedPacketClaimsPage) IsSet() bool {
	return v.isSet
}

func (v *NullableRedPacketClaimsPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedPacketClaimsPage(val *RedPacketClaimsPage) *NullableRedPacketClaimsPage {
	return &NullableRedPacketClaimsPage{value: val, isSet: true}
}

func (v NullableRedPacketClaimsPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedPacketClaimsPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

