// Package defi_pumpfun provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package defi_pumpfun

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for PumpCreateTokenInputDex.
const (
	Pumpfun PumpCreateTokenInputDex = "pumpfun"
)

// Defines values for PumpCreateTokenInputMigrationDex.
const (
	METEORA PumpCreateTokenInputMigrationDex = "METEORA"
	RAYDIUM PumpCreateTokenInputMigrationDex = "RAYDIUM"
)

// PumpCreateTokenInput defines model for PumpCreateTokenInput.
type PumpCreateTokenInput struct {
	// Description DTO.DEX.PUMPFUN.MINT.DESCRIPTION
	Description string `json:"description"`

	// Dex DTO.DEX.IDENTIFIER
	Dex PumpCreateTokenInputDex `json:"dex"`

	// Image DTO.DEX.PUMPFUN.MINT.IMAGE
	Image string `json:"image"`

	// MigrationDex DTO.DEX.PUMPFUN.MINT.MIGRATION_DEX
	MigrationDex PumpCreateTokenInputMigrationDex `json:"migrationDex"`

	// MintAddress DTO.DEX.PUMPFUN.MINT.MINT_ADDRESS
	MintAddress string `json:"mintAddress"`

	// Name DTO.DEX.PUMPFUN.MINT.NAME
	Name string `json:"name"`

	// PriorityFee DTO.DEX.BASE.PRIORITY_FEE
	PriorityFee *string `json:"priorityFee,omitempty"`

	// Symbol DTO.DEX.PUMPFUN.MINT.SYMBOL
	Symbol string `json:"symbol"`

	// Telegram DTO.DEX.PUMPFUN.MINT.TELEGRAM
	Telegram *string `json:"telegram,omitempty"`

	// Twitter DTO.DEX.PUMPFUN.MINT.TWITTER
	Twitter *string `json:"twitter,omitempty"`

	// UserAddress DTO.DEX.WALLET
	UserAddress string `json:"userAddress"`

	// Website DTO.DEX.PUMPFUN.MINT.WEBSITE
	Website *string `json:"website,omitempty"`
}

// PumpCreateTokenInputDex DTO.DEX.IDENTIFIER
type PumpCreateTokenInputDex string

// PumpCreateTokenInputMigrationDex DTO.DEX.PUMPFUN.MINT.MIGRATION_DEX
type PumpCreateTokenInputMigrationDex string

// PumpCreateTokenReply defines model for PumpCreateTokenReply.
type PumpCreateTokenReply struct {
	// Extra DTO.DEX.PUMPFUN.MINT.EXTRA
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// SerializedTx DTO.DEX.PUMPFUN.MINT.SERIALIZED_TX
	SerializedTx string `json:"serializedTx"`
}

// PumpfunCreateTokenJSONRequestBody defines body for PumpfunCreateToken for application/json ContentType.
type PumpfunCreateTokenJSONRequestBody = PumpCreateTokenInput

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PumpfunCreateTokenWithBody request with any body
	PumpfunCreateTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PumpfunCreateToken(ctx context.Context, body PumpfunCreateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PumpfunCreateTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPumpfunCreateTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PumpfunCreateToken(ctx context.Context, body PumpfunCreateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPumpfunCreateTokenRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPumpfunCreateTokenRequest calls the generic PumpfunCreateToken builder with application/json body
func NewPumpfunCreateTokenRequest(server string, body PumpfunCreateTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPumpfunCreateTokenRequestWithBody(server, "application/json", bodyReader)
}

// NewPumpfunCreateTokenRequestWithBody generates requests for PumpfunCreateToken with any type of body
func NewPumpfunCreateTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/sol/pumpfun/create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PumpfunCreateTokenWithBodyWithResponse request with any body
	PumpfunCreateTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PumpfunCreateTokenResponse, error)

	PumpfunCreateTokenWithResponse(ctx context.Context, body PumpfunCreateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*PumpfunCreateTokenResponse, error)
}

type PumpfunCreateTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PumpCreateTokenReply
}

// Status returns HTTPResponse.Status
func (r PumpfunCreateTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PumpfunCreateTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PumpfunCreateTokenWithBodyWithResponse request with arbitrary body returning *PumpfunCreateTokenResponse
func (c *ClientWithResponses) PumpfunCreateTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PumpfunCreateTokenResponse, error) {
	rsp, err := c.PumpfunCreateTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePumpfunCreateTokenResponse(rsp)
}

func (c *ClientWithResponses) PumpfunCreateTokenWithResponse(ctx context.Context, body PumpfunCreateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*PumpfunCreateTokenResponse, error) {
	rsp, err := c.PumpfunCreateToken(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePumpfunCreateTokenResponse(rsp)
}

// ParsePumpfunCreateTokenResponse parses an HTTP response from a PumpfunCreateTokenWithResponse call
func ParsePumpfunCreateTokenResponse(rsp *http.Response) (*PumpfunCreateTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PumpfunCreateTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PumpCreateTokenReply
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
