
// Package dex provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package dex

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	"go.yaml.in/yaml/v3"
	"io"
	"os"
	"mime"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	"github.com/oapi-codegen/nullable"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"github.com/getkin/kin-openapi/openapi3"
)

const (
BearerScopes bearerContextKey = "bearer.Scopes"

)




// Defines values for ChainSymbol.
const (

  Bsc ChainSymbol = "bsc"
  Eth ChainSymbol = "eth"
  Sol ChainSymbol = "sol"
)

// Valid indicates whether the value is a known member of the ChainSymbol enum.
func (e ChainSymbol) Valid() bool {
    switch e {
    case Bsc:
        return true
    case Eth:
        return true
    case Sol:
        return true
    default:
        return false
    }
}


// Defines values for CreateTokenInputDex.
const (

  CreateTokenInputDexCandy CreateTokenInputDex = "candy"
  CreateTokenInputDexLaunchpad CreateTokenInputDex = "launchpad"
  CreateTokenInputDexMoonshot CreateTokenInputDex = "moonshot"
  CreateTokenInputDexPumpfun CreateTokenInputDex = "pumpfun"
  CreateTokenInputDexRaydium CreateTokenInputDex = "raydium"
)

// Valid indicates whether the value is a known member of the CreateTokenInputDex enum.
func (e CreateTokenInputDex) Valid() bool {
    switch e {
    case CreateTokenInputDexCandy:
        return true
    case CreateTokenInputDexLaunchpad:
        return true
    case CreateTokenInputDexMoonshot:
        return true
    case CreateTokenInputDexPumpfun:
        return true
    case CreateTokenInputDexRaydium:
        return true
    default:
        return false
    }
}


// Defines values for DexProtocolFamily.
const (

  DexProtocolFamilyAldrin DexProtocolFamily = "Aldrin"
  DexProtocolFamilyAldrinAmm DexProtocolFamily = "AldrinAmm"
  DexProtocolFamilyBonkFun DexProtocolFamily = "BonkFun"
  DexProtocolFamilyBoopFun DexProtocolFamily = "BoopFun"
  DexProtocolFamilyCremaFinance DexProtocolFamily = "CremaFinance"
  DexProtocolFamilyCropper DexProtocolFamily = "Cropper"
  DexProtocolFamilyCykura DexProtocolFamily = "Cykura"
  DexProtocolFamilyDradex DexProtocolFamily = "Dradex"
  DexProtocolFamilyFluxbeam DexProtocolFamily = "Fluxbeam"
  DexProtocolFamilyGooseFx DexProtocolFamily = "GooseFx"
  DexProtocolFamilyIntro DexProtocolFamily = "Intro"
  DexProtocolFamilyInvariant DexProtocolFamily = "Invariant"
  DexProtocolFamilyJupiter DexProtocolFamily = "Jupiter"
  DexProtocolFamilyLifinity DexProtocolFamily = "Lifinity"
  DexProtocolFamilyMagicEden DexProtocolFamily = "MagicEden"
  DexProtocolFamilyMetaplex DexProtocolFamily = "Metaplex"
  DexProtocolFamilyMeteora DexProtocolFamily = "Meteora"
  DexProtocolFamilyMoonshot DexProtocolFamily = "Moonshot"
  DexProtocolFamilyOasisProgram DexProtocolFamily = "OasisProgram"
  DexProtocolFamilyObric DexProtocolFamily = "Obric"
  DexProtocolFamilyOpenBook DexProtocolFamily = "OpenBook"
  DexProtocolFamilyOrca DexProtocolFamily = "Orca"
  DexProtocolFamilyOrcaWhirpool DexProtocolFamily = "OrcaWhirpool"
  DexProtocolFamilyPancakeClmm DexProtocolFamily = "PancakeClmm"
  DexProtocolFamilyPenguin DexProtocolFamily = "Penguin"
  DexProtocolFamilyPhoenix DexProtocolFamily = "Phoenix"
  DexProtocolFamilyPumpfun DexProtocolFamily = "Pumpfun"
  DexProtocolFamilyPumpswap DexProtocolFamily = "Pumpswap"
  DexProtocolFamilyRaydium DexProtocolFamily = "Raydium"
  DexProtocolFamilySaber DexProtocolFamily = "Saber"
  DexProtocolFamilySaros DexProtocolFamily = "Saros"
  DexProtocolFamilySencha DexProtocolFamily = "Sencha"
  DexProtocolFamilySentre DexProtocolFamily = "Sentre"
  DexProtocolFamilySerum DexProtocolFamily = "Serum"
  DexProtocolFamilySolFi DexProtocolFamily = "SolFi"
  DexProtocolFamilySolana DexProtocolFamily = "Solana"
  DexProtocolFamilyStabble DexProtocolFamily = "Stabble"
  DexProtocolFamilyStepFinance DexProtocolFamily = "StepFinance"
  DexProtocolFamilyStepN DexProtocolFamily = "StepN"
  DexProtocolFamilySymmetry DexProtocolFamily = "Symmetry"
  DexProtocolFamilyTensor DexProtocolFamily = "Tensor"
  DexProtocolFamilyUnknown DexProtocolFamily = "Unknown"
  DexProtocolFamilyZeroFi DexProtocolFamily = "ZeroFi"
)

// Valid indicates whether the value is a known member of the DexProtocolFamily enum.
func (e DexProtocolFamily) Valid() bool {
    switch e {
    case DexProtocolFamilyAldrin:
        return true
    case DexProtocolFamilyAldrinAmm:
        return true
    case DexProtocolFamilyBonkFun:
        return true
    case DexProtocolFamilyBoopFun:
        return true
    case DexProtocolFamilyCremaFinance:
        return true
    case DexProtocolFamilyCropper:
        return true
    case DexProtocolFamilyCykura:
        return true
    case DexProtocolFamilyDradex:
        return true
    case DexProtocolFamilyFluxbeam:
        return true
    case DexProtocolFamilyGooseFx:
        return true
    case DexProtocolFamilyIntro:
        return true
    case DexProtocolFamilyInvariant:
        return true
    case DexProtocolFamilyJupiter:
        return true
    case DexProtocolFamilyLifinity:
        return true
    case DexProtocolFamilyMagicEden:
        return true
    case DexProtocolFamilyMetaplex:
        return true
    case DexProtocolFamilyMeteora:
        return true
    case DexProtocolFamilyMoonshot:
        return true
    case DexProtocolFamilyOasisProgram:
        return true
    case DexProtocolFamilyObric:
        return true
    case DexProtocolFamilyOpenBook:
        return true
    case DexProtocolFamilyOrca:
        return true
    case DexProtocolFamilyOrcaWhirpool:
        return true
    case DexProtocolFamilyPancakeClmm:
        return true
    case DexProtocolFamilyPenguin:
        return true
    case DexProtocolFamilyPhoenix:
        return true
    case DexProtocolFamilyPumpfun:
        return true
    case DexProtocolFamilyPumpswap:
        return true
    case DexProtocolFamilyRaydium:
        return true
    case DexProtocolFamilySaber:
        return true
    case DexProtocolFamilySaros:
        return true
    case DexProtocolFamilySencha:
        return true
    case DexProtocolFamilySentre:
        return true
    case DexProtocolFamilySerum:
        return true
    case DexProtocolFamilySolFi:
        return true
    case DexProtocolFamilySolana:
        return true
    case DexProtocolFamilyStabble:
        return true
    case DexProtocolFamilyStepFinance:
        return true
    case DexProtocolFamilyStepN:
        return true
    case DexProtocolFamilySymmetry:
        return true
    case DexProtocolFamilyTensor:
        return true
    case DexProtocolFamilyUnknown:
        return true
    case DexProtocolFamilyZeroFi:
        return true
    default:
        return false
    }
}


// Defines values for PageDirection.
const (

  Next PageDirection = "next"
  Prev PageDirection = "prev"
)

// Valid indicates whether the value is a known member of the PageDirection enum.
func (e PageDirection) Valid() bool {
    switch e {
    case Next:
        return true
    case Prev:
        return true
    default:
        return false
    }
}


// Defines values for SwapInputDex.
const (

  SwapInputDexCandy SwapInputDex = "candy"
  SwapInputDexJupiter SwapInputDex = "jupiter"
  SwapInputDexKyberswap SwapInputDex = "kyberswap"
  SwapInputDexLaunchpad SwapInputDex = "launchpad"
  SwapInputDexMoonshot SwapInputDex = "moonshot"
  SwapInputDexPumpfun SwapInputDex = "pumpfun"
  SwapInputDexRaydium SwapInputDex = "raydium"
)

// Valid indicates whether the value is a known member of the SwapInputDex enum.
func (e SwapInputDex) Valid() bool {
    switch e {
    case SwapInputDexCandy:
        return true
    case SwapInputDexJupiter:
        return true
    case SwapInputDexKyberswap:
        return true
    case SwapInputDexLaunchpad:
        return true
    case SwapInputDexMoonshot:
        return true
    case SwapInputDexPumpfun:
        return true
    case SwapInputDexRaydium:
        return true
    default:
        return false
    }
}


// Defines values for SwapInputSwapMode.
const (

  SwapInputSwapModeExactIn SwapInputSwapMode = "ExactIn"
  SwapInputSwapModeExactOut SwapInputSwapMode = "ExactOut"
)

// Valid indicates whether the value is a known member of the SwapInputSwapMode enum.
func (e SwapInputSwapMode) Valid() bool {
    switch e {
    case SwapInputSwapModeExactIn:
        return true
    case SwapInputSwapModeExactOut:
        return true
    default:
        return false
    }
}


// Defines values for SwapRouteInputDex.
const (

  SwapRouteInputDexCandy SwapRouteInputDex = "candy"
  SwapRouteInputDexJupiter SwapRouteInputDex = "jupiter"
  SwapRouteInputDexKyberswap SwapRouteInputDex = "kyberswap"
  SwapRouteInputDexLaunchpad SwapRouteInputDex = "launchpad"
  SwapRouteInputDexMoonshot SwapRouteInputDex = "moonshot"
  SwapRouteInputDexPumpfun SwapRouteInputDex = "pumpfun"
  SwapRouteInputDexRaydium SwapRouteInputDex = "raydium"
)

// Valid indicates whether the value is a known member of the SwapRouteInputDex enum.
func (e SwapRouteInputDex) Valid() bool {
    switch e {
    case SwapRouteInputDexCandy:
        return true
    case SwapRouteInputDexJupiter:
        return true
    case SwapRouteInputDexKyberswap:
        return true
    case SwapRouteInputDexLaunchpad:
        return true
    case SwapRouteInputDexMoonshot:
        return true
    case SwapRouteInputDexPumpfun:
        return true
    case SwapRouteInputDexRaydium:
        return true
    default:
        return false
    }
}


// Defines values for SwapRouteInputSwapMode.
const (

  SwapRouteInputSwapModeExactIn SwapRouteInputSwapMode = "ExactIn"
  SwapRouteInputSwapModeExactOut SwapRouteInputSwapMode = "ExactOut"
)

// Valid indicates whether the value is a known member of the SwapRouteInputSwapMode enum.
func (e SwapRouteInputSwapMode) Valid() bool {
    switch e {
    case SwapRouteInputSwapModeExactIn:
        return true
    case SwapRouteInputSwapModeExactOut:
        return true
    default:
        return false
    }
}


// Defines values for QuoteParamsDex.
const (

  Pumpfun QuoteParamsDex = "pumpfun"
  Raydium QuoteParamsDex = "raydium"
)

// Valid indicates whether the value is a known member of the QuoteParamsDex enum.
func (e QuoteParamsDex) Valid() bool {
    switch e {
    case Pumpfun:
        return true
    case Raydium:
        return true
    default:
        return false
    }
}



// ChainSymbol Supported blockchain chains
type ChainSymbol  string

// CreateTokenInput defines model for CreateTokenInput.
type CreateTokenInput  struct {
// Dex DEX identifier for the trade
    Dex CreateTokenInputDex`json:"dex"`

// Extra Additional metadata about the created token
    Extra *map[string]interface{}`json:"extra,omitempty"`

// Image Token image URL (Base64 or HTTPS)
    Image *string`json:"image,omitempty"`

// Name Name of the token to be created
    Name string`json:"name"`

// PriorityFee Priority fee in SOL to increase transaction processing speed
    PriorityFee *string`json:"priorityFee,omitempty"`

// Symbol Token symbol/ticker
    Symbol string`json:"symbol"`

// Uri URI for token metadata (usually points to image or JSON)
    Uri *string`json:"uri,omitempty"`

// UserAddress Public key of the wallet initiating the transaction
    UserAddress string`json:"userAddress"`
}

// CreateTokenInputDex DEX identifier for the trade
type CreateTokenInputDex  string

// CreateTokenReply defines model for CreateTokenReply.
type CreateTokenReply  struct {
// MintAddress Token mint address that requires signature for the transaction
    MintAddress string`json:"mintAddress"`

// SerializedTx Base64 encoded transaction for token creation
    SerializedTx string`json:"serializedTx"`
}

// DexProtocolFamily DEX protocol family identifier
type DexProtocolFamily  string

// DexQuoteResponse defines model for DexQuoteResponse.
type DexQuoteResponse  struct {
// AmountOut Output amount
    AmountOut *string`json:"amountOut,omitempty"`

// CurrentPrice Current price
    CurrentPrice *string`json:"currentPrice,omitempty"`

// ExecutionPrice Execution price
    ExecutionPrice *string`json:"executionPrice,omitempty"`

// Fee Trading fee
    Fee *string`json:"fee,omitempty"`

// MinAmountOut Minimum output amount
    MinAmountOut *string`json:"minAmountOut,omitempty"`

// PriceImpact Price impact
    PriceImpact *string`json:"priceImpact,omitempty"`
}

// PageDirection Pagination direction
type PageDirection  string

// PageResponseDex Generic pagination response
type PageResponseDex  struct {
// Data Page data
    Data []struct {
// Chain Chain identifier
    Chain string`json:"chain"`

// Image DEX image URL
    Image *string`json:"image,omitempty"`

// ProgramAddress DEX program address
    ProgramAddress *string`json:"programAddress,omitempty"`

// ProtocolFamily DEX protocol family identifier
    ProtocolFamily *DexProtocolFamily`json:"protocolFamily,omitempty"`
}`json:"data"`

// EndCursor Cursor for the end of current page
    EndCursor *string`json:"endCursor,omitempty"`

// HasNext Whether there is a next page
    HasNext *bool`json:"hasNext,omitempty"`

// HasPrev Whether there is a previous page
    HasPrev *bool`json:"hasPrev,omitempty"`

// StartCursor Cursor for the start of current page
    StartCursor *string`json:"startCursor,omitempty"`
}

// SwapInput defines model for SwapInput.
type SwapInput  struct {
// Amount Amount to swap. Use "auto" for full balance or percentage like "50%"
    Amount string`json:"amount"`

// Dex DEX identifier for the trade
    Dex SwapInputDex`json:"dex"`

// InputMint Input token mint address
    InputMint *string`json:"inputMint,omitempty"`

// OutputMint Output token mint address
    OutputMint *string`json:"outputMint,omitempty"`

// PoolAddress DEX pool address
    PoolAddress *string`json:"poolAddress,omitempty"`

// PriorityFee Priority fee in SOL to increase transaction processing speed
    PriorityFee *string`json:"priorityFee,omitempty"`

// Slippage Slippage tolerance percentage
    Slippage int64`json:"slippage"`

// SwapMode Swap direction mode
    SwapMode SwapInputSwapMode`json:"swapMode"`

// UserAddress Public key of the wallet initiating the transaction
    UserAddress string`json:"userAddress"`
}

// SwapInputDex DEX identifier for the trade
type SwapInputDex  string

// SwapInputSwapMode Swap direction mode
type SwapInputSwapMode  string

// SwapReply defines model for SwapReply.
type SwapReply  struct {
// ElapsedTime Time taken to process the request in milliseconds
    ElapsedTime int64`json:"elapsedTime"`

// SerializedTx Base64 encoded transaction
    SerializedTx string`json:"serializedTx"`
}

// SwapRouteInput defines model for SwapRouteInput.
type SwapRouteInput  struct {
// Amount Amount to swap. Use "auto" for full balance or percentage like "50%"
    Amount string`json:"amount"`

// Deadline Swap deadline timestamp
    Deadline *int64`json:"deadline,omitempty"`

// Dex DEX identifier for the trade
    Dex SwapRouteInputDex`json:"dex"`

// GasLimit Gas limit for the transaction
    GasLimit *string`json:"gasLimit,omitempty"`

// GasPrice Gas price in wei (legacy transactions)
    GasPrice *string`json:"gasPrice,omitempty"`

// InputMint Input token mint address
    InputMint *string`json:"inputMint,omitempty"`

// IsAntiMev Whether to enable anti-MEV protection
    IsAntiMev *bool`json:"isAntiMev,omitempty"`

// MaxFeePerGas Maximum fee per gas unit (EIP-1559) in wei
    MaxFeePerGas *string`json:"maxFeePerGas,omitempty"`

// MaxPriorityFeePerGas Maximum priority fee per gas unit (EIP-1559) in wei
    MaxPriorityFeePerGas *string`json:"maxPriorityFeePerGas,omitempty"`

// OutputMint Output token mint address
    OutputMint *string`json:"outputMint,omitempty"`

// Permit Permit data for the swap
    Permit *string`json:"permit,omitempty"`

// PriorityFee Priority fee in SOL to increase transaction processing speed
    PriorityFee *string`json:"priorityFee,omitempty"`

// RecipientAddress Recipient wallet address for the swap
    RecipientAddress *string`json:"recipientAddress,omitempty"`

// Slippage Slippage tolerance percentage
    Slippage int64`json:"slippage"`

// SwapMode Swap direction mode
    SwapMode SwapRouteInputSwapMode`json:"swapMode"`

// TipFee Tip fee in SOL to increase transaction processing speed
    TipFee *string`json:"tipFee,omitempty"`

// UserAddress Public key of the wallet initiating the transaction
    UserAddress string`json:"userAddress"`
}

// SwapRouteInputDex DEX identifier for the trade
type SwapRouteInputDex  string

// SwapRouteInputSwapMode Swap direction mode
type SwapRouteInputSwapMode  string

// SwapRouteResponse defines model for SwapRouteResponse.
type SwapRouteResponse  struct {
// Args Original swap request parameters
    Args SwapRouteInput`json:"args"`

// ElapsedTime Time taken to process the request in milliseconds
    ElapsedTime int64`json:"elapsedTime"`

// LastValidBlockHeight Last valid block height for the swap transaction
    LastValidBlockHeight *int64`json:"lastValidBlockHeight,omitempty"`

// RecentBlockhash Recent blockhash for the swap transaction
    RecentBlockhash *string`json:"recentBlockhash,omitempty"`

// RouteInfo Detailed routing information
    RouteInfo map[string]interface{}`json:"routeInfo"`

// SerializedTx Base64 encoded transaction
    SerializedTx string`json:"serializedTx"`
}

// apiKeyAuthContextKey is the context key for api_key_auth security scheme
type apiKeyAuthContextKey  string

// bearerContextKey is the context key for bearer security scheme
type bearerContextKey  string

// bearerAuthContextKey is the context key for bearer_auth security scheme
type bearerAuthContextKey  string



// ListDexParams defines parameters for ListDex.
type ListDexParams  struct {
// Cursor DTO.PAGE.CURSOR.DESCRIPTION
    Cursor *string`form:"cursor,omitempty" json:"cursor,omitempty"`

// Limit DTO.PAGE.LIMIT
    Limit *int64`form:"limit,omitempty" json:"limit,omitempty"`

// Direction DTO.PAGE.DIRECTION
    Direction *struct {
union json.RawMessage
}`form:"direction,omitempty" json:"direction,omitempty"`

// Chains DTO.DEX.LIST.CHAINS
    Chains *[]string`form:"chains,omitempty" json:"chains,omitempty"`

// DexProgram DTO.DEX.LIST.DEX_PROGRAM
    DexProgram *string`form:"dexProgram,omitempty" json:"dexProgram,omitempty"`
}





// QuoteParams defines parameters for Quote.
type QuoteParams  struct {
// Dex DEX protocol type
    Dex QuoteParamsDex`form:"dex" json:"dex"`

// Amount Trading amount
    Amount string`form:"amount" json:"amount"`

// InputMint Input token address
    InputMint string`form:"inputMint" json:"inputMint"`

// OutputMint Output token address
    OutputMint string`form:"outputMint" json:"outputMint"`

// ExactIn Exact input mode
    ExactIn bool`form:"exactIn" json:"exactIn"`

// Slippage Slippage tolerance
    Slippage int64`form:"slippage" json:"slippage"`
}

// QuoteParamsDex defines parameters for Quote.
type QuoteParamsDex  string












// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenInput








// RouteJSONRequestBody defines body for Route for application/json ContentType.
type RouteJSONRequestBody = SwapRouteInput






// SwapJSONRequestBody defines body for Swap for application/json ContentType.
type SwapJSONRequestBody = SwapInput




// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
    // create a client with sane default values
    client := Client{
        Server: server,
    }
    // mutate client and add all optional params
    for _, o := range opts {
        if err := o(&client); err != nil {
            return nil, err
        }
    }
    // ensure the server URL always has a trailing slash
    if !strings.HasSuffix(client.Server, "/") {
        client.Server += "/"
    }
    // create httpClient, if not already present
    if client.Client == nil {
        client.Client = &http.Client{}
    }
    return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
// ListDex request
    ListDex(ctx context.Context, params *ListDexParams, reqEditors... RequestEditorFn) (*http.Response, error)

// CreateTokenWithBody request with any body
    CreateTokenWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*http.Response, error)

    CreateToken(ctx context.Context, chain ChainSymbol, body CreateTokenJSONRequestBody, reqEditors... RequestEditorFn) (*http.Response, error)
    
// Quote request
    Quote(ctx context.Context, chain ChainSymbol, params *QuoteParams, reqEditors... RequestEditorFn) (*http.Response, error)

// RouteWithBody request with any body
    RouteWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*http.Response, error)

    Route(ctx context.Context, chain ChainSymbol, body RouteJSONRequestBody, reqEditors... RequestEditorFn) (*http.Response, error)
    
// SwapWithBody request with any body
    SwapWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*http.Response, error)

    Swap(ctx context.Context, chain ChainSymbol, body SwapJSONRequestBody, reqEditors... RequestEditorFn) (*http.Response, error)
    

}



func (c *Client) ListDex(ctx context.Context, params *ListDexParams, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewListDexRequest(c.Server, params)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) CreateTokenWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewCreateTokenRequestWithBody(c.Server, chain, contentType, body)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) CreateToken(ctx context.Context, chain ChainSymbol, body CreateTokenJSONRequestBody, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewCreateTokenRequest(c.Server, chain, body)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) Quote(ctx context.Context, chain ChainSymbol, params *QuoteParams, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewQuoteRequest(c.Server, chain, params)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) RouteWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewRouteRequestWithBody(c.Server, chain, contentType, body)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) Route(ctx context.Context, chain ChainSymbol, body RouteJSONRequestBody, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewRouteRequest(c.Server, chain, body)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) SwapWithBody(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewSwapRequestWithBody(c.Server, chain, contentType, body)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}


func (c *Client) Swap(ctx context.Context, chain ChainSymbol, body SwapJSONRequestBody, reqEditors... RequestEditorFn) (*http.Response, error) {
    req, err := NewSwapRequest(c.Server, chain, body)
    if err != nil {
        return nil, err
    }
    req = req.WithContext(ctx)
    if err := c.applyEditors(ctx, req, reqEditors); err != nil {
        return nil, err
    }
    return c.Client.Do(req)
}








// NewListDexRequest generates requests for ListDex
func NewListDexRequest(server string, params *ListDexParams) (*http.Request, error) {
    var err error

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/dex")
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    if params != nil {
        // queryValues collects non-styled parameters (passthrough, JSON)
        // that are safe to round-trip through url.Values.Encode().
        queryValues := queryURL.Query()
        // rawQueryFragments collects pre-encoded query fragments from
        // styled parameters, preserving literal commas as delimiters
        // per the OpenAPI spec (e.g. "color=blue,black,brown").
        var rawQueryFragments []string
            
             if params.Cursor != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Limit != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Direction != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "direction", *params.Direction, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.Chains != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "chains", *params.Chains, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
             if params.DexProgram != nil { 
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dexProgram", *params.DexProgram, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            }
        
        if encoded := queryValues.Encode(); encoded != "" {
            rawQueryFragments = append(rawQueryFragments, encoded)
        }
        queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
    }

    req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
    if err != nil {
        return nil, err
    }

    



    return req, nil
}



// NewCreateTokenRequest calls the generic CreateToken builder with application/json body
func NewCreateTokenRequest(server string, chain ChainSymbol, body CreateTokenJSONRequestBody) (*http.Request, error) {
    var bodyReader io.Reader
    buf, err := json.Marshal(body)
        if err != nil {
            return nil, err
        }
        bodyReader = bytes.NewReader(buf)
    return NewCreateTokenRequestWithBody(server, chain, "application/json", bodyReader)
}


// NewCreateTokenRequestWithBody generates requests for CreateToken with any type of body
func NewCreateTokenRequestWithBody(server string, chain ChainSymbol, contentType string, body io.Reader) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/dex/%s/create", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
    if err != nil {
        return nil, err
    }

    req.Header.Add("Content-Type", contentType)



    return req, nil
}




// NewQuoteRequest generates requests for Quote
func NewQuoteRequest(server string, chain ChainSymbol, params *QuoteParams) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/dex/%s/quote", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    if params != nil {
        // queryValues collects non-styled parameters (passthrough, JSON)
        // that are safe to round-trip through url.Values.Encode().
        queryValues := queryURL.Query()
        // rawQueryFragments collects pre-encoded query fragments from
        // styled parameters, preserving literal commas as delimiters
        // per the OpenAPI spec (e.g. "color=blue,black,brown").
        var rawQueryFragments []string
            
            
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dex", params.Dex, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            
        
            
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "amount", params.Amount, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            
        
            
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "inputMint", params.InputMint, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            
        
            
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "outputMint", params.OutputMint, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            
        
            
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "exactIn", params.ExactIn, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            
        
            
            
            
            
            if queryFrag, err := runtime.StyleParamWithOptions("form", true, "slippage", params.Slippage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
                return nil, err
            } else {
                for _, qp := range strings.Split(queryFrag, "&") {
                    rawQueryFragments = append(rawQueryFragments, qp)
                }
            }
            
            
        
        if encoded := queryValues.Encode(); encoded != "" {
            rawQueryFragments = append(rawQueryFragments, encoded)
        }
        queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
    }

    req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
    if err != nil {
        return nil, err
    }

    



    return req, nil
}



// NewRouteRequest calls the generic Route builder with application/json body
func NewRouteRequest(server string, chain ChainSymbol, body RouteJSONRequestBody) (*http.Request, error) {
    var bodyReader io.Reader
    buf, err := json.Marshal(body)
        if err != nil {
            return nil, err
        }
        bodyReader = bytes.NewReader(buf)
    return NewRouteRequestWithBody(server, chain, "application/json", bodyReader)
}


// NewRouteRequestWithBody generates requests for Route with any type of body
func NewRouteRequestWithBody(server string, chain ChainSymbol, contentType string, body io.Reader) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/dex/%s/route", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
    if err != nil {
        return nil, err
    }

    req.Header.Add("Content-Type", contentType)



    return req, nil
}



// NewSwapRequest calls the generic Swap builder with application/json body
func NewSwapRequest(server string, chain ChainSymbol, body SwapJSONRequestBody) (*http.Request, error) {
    var bodyReader io.Reader
    buf, err := json.Marshal(body)
        if err != nil {
            return nil, err
        }
        bodyReader = bytes.NewReader(buf)
    return NewSwapRequestWithBody(server, chain, "application/json", bodyReader)
}


// NewSwapRequestWithBody generates requests for Swap with any type of body
func NewSwapRequestWithBody(server string, chain ChainSymbol, contentType string, body io.Reader) (*http.Request, error) {
    var err error

    var pathParam0 string
    
    
    
    pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chain", chain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
    if err != nil {
        return nil, err
    }
    

    serverURL, err := url.Parse(server)
    if err != nil {
        return nil, err
    }

    operationPath := fmt.Sprintf("/v2/dex/%s/swap", pathParam0)
    if operationPath[0] == '/' {
        operationPath = "." + operationPath
    }

    queryURL, err := serverURL.Parse(operationPath)
    if err != nil {
        return nil, err
    }


    req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
    if err != nil {
        return nil, err
    }

    req.Header.Add("Content-Type", contentType)



    return req, nil
}



func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
    for _, r := range c.RequestEditors {
        if err := r(ctx, req); err != nil {
            return err
        }
    }
    for _, r := range additionalEditors {
        if err := r(ctx, req); err != nil {
            return err
        }
    }
    return nil
}
// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
    ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
    client, err := NewClient(server, opts...)
    if err != nil {
        return nil, err
    }
    return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
// ListDexWithResponse request
    ListDexWithResponse(ctx context.Context, params *ListDexParams, reqEditors... RequestEditorFn) (*ListDexResponse, error)

// CreateTokenWithBodyWithResponse request with any body
    CreateTokenWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*CreateTokenResponse, error)

    CreateTokenWithResponse(ctx context.Context, chain ChainSymbol, body CreateTokenJSONRequestBody, reqEditors... RequestEditorFn) (*CreateTokenResponse, error)
    
// QuoteWithResponse request
    QuoteWithResponse(ctx context.Context, chain ChainSymbol, params *QuoteParams, reqEditors... RequestEditorFn) (*QuoteResponse, error)

// RouteWithBodyWithResponse request with any body
    RouteWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*RouteResponse, error)

    RouteWithResponse(ctx context.Context, chain ChainSymbol, body RouteJSONRequestBody, reqEditors... RequestEditorFn) (*RouteResponse, error)
    
// SwapWithBodyWithResponse request with any body
    SwapWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*SwapResponse, error)

    SwapWithResponse(ctx context.Context, chain ChainSymbol, body SwapJSONRequestBody, reqEditors... RequestEditorFn) (*SwapResponse, error)
    

}



type ListDexResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *PageResponseDex
}

// Status returns HTTPResponse.Status
func (r ListDexResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDexResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDexResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}




type CreateTokenResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *CreateTokenReply
}

// Status returns HTTPResponse.Status
func (r CreateTokenResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTokenResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateTokenResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}




type QuoteResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *DexQuoteResponse
}

// Status returns HTTPResponse.Status
func (r QuoteResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QuoteResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r QuoteResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}




type RouteResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *SwapRouteResponse
}

// Status returns HTTPResponse.Status
func (r RouteResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RouteResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RouteResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}




type SwapResponse struct {
    Body         []byte
	HTTPResponse *http.Response
    JSON200 *SwapReply
}

// Status returns HTTPResponse.Status
func (r SwapResponse) Status() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Status
    }
    return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SwapResponse) StatusCode() int {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.StatusCode
    }
    return 0
}




// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SwapResponse) ContentType() string {
    if r.HTTPResponse != nil {
        return r.HTTPResponse.Header.Get("Content-Type")
    }
    return ""
}








// ListDexWithResponse request returning *ListDexResponse
func (c *ClientWithResponses) ListDexWithResponse(ctx context.Context, params *ListDexParams, reqEditors... RequestEditorFn) (*ListDexResponse, error){
    rsp, err := c.ListDex(ctx, params, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseListDexResponse(rsp)
}






// CreateTokenWithBodyWithResponse request with arbitrary body returning *CreateTokenResponse
func (c *ClientWithResponses) CreateTokenWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*CreateTokenResponse, error){
    rsp, err := c.CreateTokenWithBody(ctx, chain, contentType, body, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseCreateTokenResponse(rsp)
}


func (c *ClientWithResponses) CreateTokenWithResponse(ctx context.Context, chain ChainSymbol, body CreateTokenJSONRequestBody, reqEditors... RequestEditorFn) (*CreateTokenResponse, error) {
    rsp, err := c.CreateToken(ctx, chain, body, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseCreateTokenResponse(rsp)
}






// QuoteWithResponse request returning *QuoteResponse
func (c *ClientWithResponses) QuoteWithResponse(ctx context.Context, chain ChainSymbol, params *QuoteParams, reqEditors... RequestEditorFn) (*QuoteResponse, error){
    rsp, err := c.Quote(ctx, chain, params, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseQuoteResponse(rsp)
}






// RouteWithBodyWithResponse request with arbitrary body returning *RouteResponse
func (c *ClientWithResponses) RouteWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*RouteResponse, error){
    rsp, err := c.RouteWithBody(ctx, chain, contentType, body, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseRouteResponse(rsp)
}


func (c *ClientWithResponses) RouteWithResponse(ctx context.Context, chain ChainSymbol, body RouteJSONRequestBody, reqEditors... RequestEditorFn) (*RouteResponse, error) {
    rsp, err := c.Route(ctx, chain, body, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseRouteResponse(rsp)
}






// SwapWithBodyWithResponse request with arbitrary body returning *SwapResponse
func (c *ClientWithResponses) SwapWithBodyWithResponse(ctx context.Context, chain ChainSymbol, contentType string, body io.Reader, reqEditors... RequestEditorFn) (*SwapResponse, error){
    rsp, err := c.SwapWithBody(ctx, chain, contentType, body, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseSwapResponse(rsp)
}


func (c *ClientWithResponses) SwapWithResponse(ctx context.Context, chain ChainSymbol, body SwapJSONRequestBody, reqEditors... RequestEditorFn) (*SwapResponse, error) {
    rsp, err := c.Swap(ctx, chain, body, reqEditors...)
    if err != nil {
        return nil, err
    }
    return ParseSwapResponse(rsp)
}








// ParseListDexResponse parses an HTTP response from a ListDexWithResponse call
func ParseListDexResponse(rsp *http.Response) (*ListDexResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &ListDexResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest PageResponseDex
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}


// ParseCreateTokenResponse parses an HTTP response from a CreateTokenWithResponse call
func ParseCreateTokenResponse(rsp *http.Response) (*CreateTokenResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &CreateTokenResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest CreateTokenReply
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}


// ParseQuoteResponse parses an HTTP response from a QuoteWithResponse call
func ParseQuoteResponse(rsp *http.Response) (*QuoteResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &QuoteResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest DexQuoteResponse
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}


// ParseRouteResponse parses an HTTP response from a RouteWithResponse call
func ParseRouteResponse(rsp *http.Response) (*RouteResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &RouteResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest SwapRouteResponse
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}


// ParseSwapResponse parses an HTTP response from a SwapWithResponse call
func ParseSwapResponse(rsp *http.Response) (*SwapResponse, error) {
    bodyBytes, err := io.ReadAll(rsp.Body)
    defer func() { _ = rsp.Body.Close() }()
    if err != nil {
        return nil, err
    }

    response := &SwapResponse{
Body: bodyBytes,
HTTPResponse: rsp,
}

    switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
var dest SwapReply
if err := json.Unmarshal(bodyBytes, &dest); err != nil { 
 return nil, err 
}
response.JSON200 = &dest

}


    return response, nil
}

