// Package dexpool provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dexpool

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for ChainSymbol.
const (
	Bsc ChainSymbol = "bsc"
	Eth ChainSymbol = "eth"
	Sol ChainSymbol = "sol"
)

// Defines values for DexPoolDTOLiquidityModel.
const (
	DexPoolDTOLiquidityModelN0 DexPoolDTOLiquidityModel = 0
	DexPoolDTOLiquidityModelN1 DexPoolDTOLiquidityModel = 1
	DexPoolDTOLiquidityModelN2 DexPoolDTOLiquidityModel = 2
	DexPoolDTOLiquidityModelN3 DexPoolDTOLiquidityModel = 3
	DexPoolDTOLiquidityModelN4 DexPoolDTOLiquidityModel = 4
)

// Defines values for DexPoolDTOType.
const (
	DexPoolDTOTypeN0 DexPoolDTOType = 0
	DexPoolDTOTypeN1 DexPoolDTOType = 1
	DexPoolDTOTypeN2 DexPoolDTOType = 2
	DexPoolDTOTypeN3 DexPoolDTOType = 3
	DexPoolDTOTypeN4 DexPoolDTOType = 4
)

// Defines values for DexPoolDTOVersion.
const (
	N0 DexPoolDTOVersion = 0
	N1 DexPoolDTOVersion = 1
	N2 DexPoolDTOVersion = 2
	N3 DexPoolDTOVersion = 3
)

// Defines values for GetDexpoolSnapshotsParamsDirection.
const (
	Next GetDexpoolSnapshotsParamsDirection = "next"
	Prev GetDexpoolSnapshotsParamsDirection = "prev"
)

// ChainSymbol defines model for ChainSymbol.
type ChainSymbol string

// DexPoolDTO defines model for DexPoolDTO.
type DexPoolDTO struct {
	// Chain DTO.DEX.CHAIN
	Chain string `json:"chain"`

	// CreatedBlockTimestamp DTO.DEXPOOL.CREATED_BLOCK_TIMESTAMP
	CreatedBlockTimestamp *string `json:"createdBlockTimestamp,omitempty"`

	// FeeRate DTO.DEXPOOL.FEE_RATE
	FeeRate *string `json:"feeRate,omitempty"`

	// Image DTO.DEX.IMAGE
	Image *string `json:"image,omitempty"`

	// LiquidityModel DTO.DEXPOOL.LIQUIDITY_MODEL
	LiquidityModel *DexPoolDTOLiquidityModel `json:"liquidityModel,omitempty"`

	// PoolAddress DTO.DEXPOOL.POOL_ADDRESS
	PoolAddress string `json:"poolAddress"`

	// ProgramAddress DTO.DEX.PROGRAM_ADDRESS
	ProgramAddress *string `json:"programAddress,omitempty"`

	// ProtocolFamily DTO.DEX.PROTOCOL_FAMILY
	ProtocolFamily *string `json:"protocolFamily,omitempty"`

	// ProtocolName DTO.DEXPOOL.PROTOCOL_NAME
	ProtocolName *string `json:"protocolName,omitempty"`

	// TickSpacing DTO.DEXPOOL.TICK_SPACING
	TickSpacing *int64 `json:"tickSpacing,omitempty"`

	// TokenAAddress DTO.DEXPOOL.TOKEN_A
	TokenAAddress string `json:"tokenAAddress"`

	// TokenALiquidity DTO.DEXPOOL.TOKEN_A_LIQUIDITY
	TokenALiquidity *DexPoolTokenLiquidity `json:"tokenALiquidity,omitempty"`

	// TokenBAddress DTO.DEXPOOL.TOKEN_B
	TokenBAddress string `json:"tokenBAddress"`

	// TokenBLiquidity DTO.DEXPOOL.TOKEN_B_LIQUIDITY
	TokenBLiquidity *DexPoolTokenLiquidity `json:"tokenBLiquidity,omitempty"`

	// TokenCount DTO.DEXPOOL.TOKEN_COUNT
	TokenCount *int64 `json:"tokenCount,omitempty"`

	// TvlInSol DTO.DEXPOOL.TVL_SOL
	TvlInSol *string `json:"tvlInSol,omitempty"`

	// TvlInUsd DTO.DEXPOOL.TVL_USD
	TvlInUsd *string `json:"tvlInUsd,omitempty"`

	// Type DTO.DEXPOOL.TYPE
	Type *DexPoolDTOType `json:"type,omitempty"`

	// Version DTO.DEXPOOL.VERSION
	Version *DexPoolDTOVersion `json:"version,omitempty"`
}

// DexPoolDTOLiquidityModel DTO.DEXPOOL.LIQUIDITY_MODEL
type DexPoolDTOLiquidityModel float32

// DexPoolDTOType DTO.DEXPOOL.TYPE
type DexPoolDTOType float32

// DexPoolDTOVersion DTO.DEXPOOL.VERSION
type DexPoolDTOVersion float32

// DexPoolSnapshotDTO defines model for DexPoolSnapshotDTO.
type DexPoolSnapshotDTO struct {
	// BlockHeight DTO.DEXPOOL.SNAPSHOT.BLOCK_HEIGHT
	BlockHeight int64 `json:"blockHeight"`

	// BlockSlot DTO.DEXPOOL.SNAPSHOT.BLOCK_SLOT
	BlockSlot *int64 `json:"blockSlot,omitempty"`

	// BlockTimestamp DTO.DEXPOOL.SNAPSHOT.BLOCK_TIMESTAMP
	BlockTimestamp int64 `json:"blockTimestamp"`

	// PoolAddress DTO.DEXPOOL.POOL_ADDRESS
	PoolAddress string `json:"poolAddress"`

	// SnapshotTime DTO.DEXPOOL.SNAPSHOT.SNAPSHOT_TIME
	SnapshotTime int64 `json:"snapshotTime"`

	// TokenA DTO.DEXPOOL.SNAPSHOT.TOKEN_A
	TokenA DexPoolTokenSnapshotDTO `json:"tokenA"`

	// TokenB DTO.DEXPOOL.SNAPSHOT.TOKEN_B
	TokenB DexPoolTokenSnapshotDTO `json:"tokenB"`

	// TvlInNative DTO.DEXPOOL.TVL_SOL
	TvlInNative string `json:"tvlInNative"`

	// TvlInUsd DTO.DEXPOOL.TVL_USD
	TvlInUsd string `json:"tvlInUsd"`
}

// DexPoolSnapshotPage defines model for DexPoolSnapshotPage.
type DexPoolSnapshotPage struct {
	// Data DTO.PAGE.DATA
	Data []DexPoolSnapshotDTO `json:"data"`

	// EndCursor DTO.PAGE.END_CURSOR
	EndCursor *string `json:"endCursor,omitempty"`

	// HasNext DTO.PAGE.HAS_NEXT
	HasNext bool `json:"hasNext"`

	// HasPrev DTO.PAGE.HAS_PREV
	HasPrev bool `json:"hasPrev"`

	// StartCursor DTO.PAGE.START_CURSOR
	StartCursor *string `json:"startCursor,omitempty"`
}

// DexPoolTokenLiquidity defines model for DexPoolTokenLiquidity.
type DexPoolTokenLiquidity struct {
	// AmountInNative DTO.DEXPOOL.AMOUNT_IN_NATIVE
	AmountInNative string `json:"amountInNative"`

	// AmountInUsd DTO.DEXPOOL.AMOUNT_IN_USD
	AmountInUsd string `json:"amountInUsd"`

	// Decimals DTO.DEXPOOL.TOKEN_DECIMALS
	Decimals int64 `json:"decimals"`

	// PriceNative DTO.DEXPOOL.PRICE_NATIVE
	PriceNative string `json:"priceNative"`

	// PriceUsd DTO.DEXPOOL.PRICE_USD
	PriceUsd string `json:"priceUsd"`

	// TokenAddress DTO.DEXPOOL.TOKEN_ADDRESS
	TokenAddress string `json:"tokenAddress"`

	// VaultAmount DTO.DEXPOOL.VAULT_AMOUNT
	VaultAmount string `json:"vaultAmount"`
}

// DexPoolTokenSnapshotDTO defines model for DexPoolTokenSnapshotDTO.
type DexPoolTokenSnapshotDTO struct {
	// AmountInNative DTO.DEXPOOL.AMOUNT_IN_NATIVE
	AmountInNative string `json:"amountInNative"`

	// AmountInUsd DTO.DEXPOOL.AMOUNT_IN_USD
	AmountInUsd string `json:"amountInUsd"`

	// Decimals DTO.DEXPOOL.TOKEN_DECIMALS
	Decimals int64 `json:"decimals"`

	// PriceNative DTO.DEXPOOL.PRICE_NATIVE
	PriceNative string `json:"priceNative"`

	// PriceUsd DTO.DEXPOOL.PRICE_USD
	PriceUsd string `json:"priceUsd"`

	// TokenAddress DTO.DEXPOOL.TOKEN_ADDRESS
	TokenAddress string `json:"tokenAddress"`

	// VaultAmount DTO.DEXPOOL.VAULT_AMOUNT
	VaultAmount string `json:"vaultAmount"`
}

// GetDexpoolSnapshotsParams defines parameters for GetDexpoolSnapshots.
type GetDexpoolSnapshotsParams struct {
	// Cursor DTO.PAGE.CURSOR.DESCRIPTION
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit DTO.PAGE.LIMIT
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Direction DTO.PAGE.DIRECTION
	Direction *GetDexpoolSnapshotsParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`

	// Time DTO.DEXPOOL.SNAPSHOT.TIME
	Time *int64 `form:"time,omitempty" json:"time,omitempty"`
}

// GetDexpoolSnapshotsParamsDirection defines parameters for GetDexpoolSnapshots.
type GetDexpoolSnapshotsParamsDirection string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetDexpool request
	GetDexpool(ctx context.Context, chain ChainSymbol, poolAddress string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDexpoolSnapshots request
	GetDexpoolSnapshots(ctx context.Context, chain ChainSymbol, poolAddress string, params *GetDexpoolSnapshotsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetDexpool(ctx context.Context, chain ChainSymbol, poolAddress string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDexpoolRequest(c.Server, chain, poolAddress)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDexpoolSnapshots(ctx context.Context, chain ChainSymbol, poolAddress string, params *GetDexpoolSnapshotsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDexpoolSnapshotsRequest(c.Server, chain, poolAddress, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetDexpoolRequest generates requests for GetDexpool
func NewGetDexpoolRequest(server string, chain ChainSymbol, poolAddress string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chain", runtime.ParamLocationPath, chain)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "poolAddress", runtime.ParamLocationPath, poolAddress)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dexpools/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDexpoolSnapshotsRequest generates requests for GetDexpoolSnapshots
func NewGetDexpoolSnapshotsRequest(server string, chain ChainSymbol, poolAddress string, params *GetDexpoolSnapshotsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chain", runtime.ParamLocationPath, chain)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "poolAddress", runtime.ParamLocationPath, poolAddress)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dexpools/%s/%s/snapshots", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Time != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "time", runtime.ParamLocationQuery, *params.Time); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetDexpoolWithResponse request
	GetDexpoolWithResponse(ctx context.Context, chain ChainSymbol, poolAddress string, reqEditors ...RequestEditorFn) (*GetDexpoolResponse, error)

	// GetDexpoolSnapshotsWithResponse request
	GetDexpoolSnapshotsWithResponse(ctx context.Context, chain ChainSymbol, poolAddress string, params *GetDexpoolSnapshotsParams, reqEditors ...RequestEditorFn) (*GetDexpoolSnapshotsResponse, error)
}

type GetDexpoolResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DexPoolDTO
}

// Status returns HTTPResponse.Status
func (r GetDexpoolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDexpoolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDexpoolSnapshotsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DexPoolSnapshotPage
}

// Status returns HTTPResponse.Status
func (r GetDexpoolSnapshotsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDexpoolSnapshotsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetDexpoolWithResponse request returning *GetDexpoolResponse
func (c *ClientWithResponses) GetDexpoolWithResponse(ctx context.Context, chain ChainSymbol, poolAddress string, reqEditors ...RequestEditorFn) (*GetDexpoolResponse, error) {
	rsp, err := c.GetDexpool(ctx, chain, poolAddress, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDexpoolResponse(rsp)
}

// GetDexpoolSnapshotsWithResponse request returning *GetDexpoolSnapshotsResponse
func (c *ClientWithResponses) GetDexpoolSnapshotsWithResponse(ctx context.Context, chain ChainSymbol, poolAddress string, params *GetDexpoolSnapshotsParams, reqEditors ...RequestEditorFn) (*GetDexpoolSnapshotsResponse, error) {
	rsp, err := c.GetDexpoolSnapshots(ctx, chain, poolAddress, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDexpoolSnapshotsResponse(rsp)
}

// ParseGetDexpoolResponse parses an HTTP response from a GetDexpoolWithResponse call
func ParseGetDexpoolResponse(rsp *http.Response) (*GetDexpoolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDexpoolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DexPoolDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetDexpoolSnapshotsResponse parses an HTTP response from a GetDexpoolSnapshotsWithResponse call
func ParseGetDexpoolSnapshotsResponse(rsp *http.Response) (*GetDexpoolSnapshotsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDexpoolSnapshotsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DexPoolSnapshotPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
