// Package bridgeaggregator provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package bridgeaggregator

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerScopes bearerContextKey = "bearer.Scopes"
)

// Defines values for ExecutionCrossChainInputSwapMode.
const (
	ExecutionCrossChainInputSwapModeExactIn  ExecutionCrossChainInputSwapMode = "ExactIn"
	ExecutionCrossChainInputSwapModeExactOut ExecutionCrossChainInputSwapMode = "ExactOut"
)

// Valid indicates whether the value is a known member of the ExecutionCrossChainInputSwapMode enum.
func (e ExecutionCrossChainInputSwapMode) Valid() bool {
	switch e {
	case ExecutionCrossChainInputSwapModeExactIn:
		return true
	case ExecutionCrossChainInputSwapModeExactOut:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionDescriptorKind.
const (
	CrossChain ExecutionDescriptorKind = "crossChain"
	Gasless    ExecutionDescriptorKind = "gasless"
	Swap       ExecutionDescriptorKind = "swap"
)

// Valid indicates whether the value is a known member of the ExecutionDescriptorKind enum.
func (e ExecutionDescriptorKind) Valid() bool {
	switch e {
	case CrossChain:
		return true
	case Gasless:
		return true
	case Swap:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionDescriptorVersion.
const (
	N1 ExecutionDescriptorVersion = 1
)

// Valid indicates whether the value is a known member of the ExecutionDescriptorVersion enum.
func (e ExecutionDescriptorVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionEconomicsMode.
const (
	ExecutionEconomicsModeExactIn  ExecutionEconomicsMode = "ExactIn"
	ExecutionEconomicsModeExactOut ExecutionEconomicsMode = "ExactOut"
)

// Valid indicates whether the value is a known member of the ExecutionEconomicsMode enum.
func (e ExecutionEconomicsMode) Valid() bool {
	switch e {
	case ExecutionEconomicsModeExactIn:
		return true
	case ExecutionEconomicsModeExactOut:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionEconomicsProvider.
const (
	Zerox ExecutionEconomicsProvider = "zerox"
)

// Valid indicates whether the value is a known member of the ExecutionEconomicsProvider enum.
func (e ExecutionEconomicsProvider) Valid() bool {
	switch e {
	case Zerox:
		return true
	default:
		return false
	}
}

// ExecutionBuildResponse defines model for ExecutionBuildResponse.
type ExecutionBuildResponse struct {
	Execution ExecutionDescriptor `json:"execution"`

	// PlatformFeePolicy Server platform fee policy (kind/rate/recipient/token), separate from quotedFees and actual settlement.
	PlatformFeePolicy map[string]interface{} `json:"platformFeePolicy"`
	RouteInfo         ExecutionEconomics     `json:"routeInfo"`

	// SerializedTx Present only for swap/crossChain; omitted for gasless.
	SerializedTx *string `json:"serializedTx,omitempty"`
}

// ExecutionCrossChainInput defines model for ExecutionCrossChainInput.
type ExecutionCrossChainInput struct {
	// Amount Exact token base units; never a JSON number.
	Amount string `json:"amount"`

	// Chain Configured slug, alias or eip155:<exact decimal ID>.
	Chain            string  `json:"chain"`
	DestinationChain string  `json:"destinationChain"`
	InputMint        string  `json:"inputMint"`
	OutputMint       string  `json:"outputMint"`
	RecipientAddress *string `json:"recipientAddress,omitempty"`

	// SlippageBps Explicit basis points. Legacy slippage percentages are not converted.
	SlippageBps int                              `json:"slippageBps"`
	SwapMode    ExecutionCrossChainInputSwapMode `json:"swapMode"`
	UserAddress string                           `json:"userAddress"`
}

// ExecutionCrossChainInputSwapMode defines model for ExecutionCrossChainInput.SwapMode.
type ExecutionCrossChainInputSwapMode string

// ExecutionDescriptor defines model for ExecutionDescriptor.
type ExecutionDescriptor struct {
	ChainId            string  `json:"chainId"`
	DestinationChainId *string `json:"destinationChainId,omitempty"`

	// ExpiresAt Quote expiry in Unix milliseconds.
	ExpiresAt int `json:"expiresAt"`

	// Kind Operation kind, distinct from transaction/gasless signature input kind.
	Kind        ExecutionDescriptorKind    `json:"kind"`
	QuoteId     openapi_types.UUID         `json:"quoteId"`
	SigningData *ExecutionSigningData      `json:"signingData,omitempty"`
	Version     ExecutionDescriptorVersion `json:"version"`
}

// ExecutionDescriptorKind Operation kind, distinct from transaction/gasless signature input kind.
type ExecutionDescriptorKind string

// ExecutionDescriptorVersion defines model for ExecutionDescriptor.Version.
type ExecutionDescriptorVersion float32

// ExecutionEconomics defines model for ExecutionEconomics.
type ExecutionEconomics struct {
	BuyAmount              string                     `json:"buyAmount"`
	BuyToken               string                     `json:"buyToken"`
	EstimatedNetSellAmount *string                    `json:"estimatedNetSellAmount,omitempty"`
	MaxSellAmount          *string                    `json:"maxSellAmount,omitempty"`
	MinBuyAmount           *string                    `json:"minBuyAmount,omitempty"`
	Mode                   ExecutionEconomicsMode     `json:"mode"`
	Provider               ExecutionEconomicsProvider `json:"provider"`
	QuoteId                openapi_types.UUID         `json:"quoteId"`

	// QuotedFees Provider quoted fee breakdown, not settled actual amounts.
	QuotedFees map[string]interface{} `json:"quotedFees"`
	SellAmount *string                `json:"sellAmount,omitempty"`
	SellToken  string                 `json:"sellToken"`
}

// ExecutionEconomicsMode defines model for ExecutionEconomics.Mode.
type ExecutionEconomicsMode string

// ExecutionEconomicsProvider defines model for ExecutionEconomics.Provider.
type ExecutionEconomicsProvider string

// ExecutionSelectorBuildInput defines model for ExecutionSelectorBuildInput.
type ExecutionSelectorBuildInput struct {
	Chain   string             `json:"chain"`
	QuoteId openapi_types.UUID `json:"quoteId"`
}

// ExecutionSigningData defines model for ExecutionSigningData.
type ExecutionSigningData struct {
	Approval *ExecutionTypedPayload `json:"approval,omitempty"`
	Trade    ExecutionTypedPayload  `json:"trade"`
}

// ExecutionTransactionQuoteResponse defines model for ExecutionTransactionQuoteResponse.
type ExecutionTransactionQuoteResponse struct {
	Execution ExecutionDescriptor `json:"execution"`

	// PlatformFeePolicy Server platform fee policy (kind/rate/recipient/token), separate from quotedFees and actual settlement.
	PlatformFeePolicy map[string]interface{} `json:"platformFeePolicy"`
	RouteInfo         ExecutionEconomics     `json:"routeInfo"`

	// SerializedTx Unsigned EVM transaction in base64.
	SerializedTx string `json:"serializedTx"`
}

// ExecutionTypedData defines model for ExecutionTypedData.
type ExecutionTypedData struct {
	// Domain Complete provider EIP-712 domain. Numeric chainId stays numeric on the signed wire.
	Domain map[string]interface{} `json:"domain"`

	// Message Complete signed message; exact uint values remain strings.
	Message     map[string]interface{}           `json:"message"`
	PrimaryType string                           `json:"primaryType"`
	Types       map[string][]ExecutionTypedField `json:"types"`
}

// ExecutionTypedField defines model for ExecutionTypedField.
type ExecutionTypedField struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// ExecutionTypedPayload defines model for ExecutionTypedPayload.
type ExecutionTypedPayload struct {
	Eip712 ExecutionTypedData `json:"eip712"`
	Hash   string             `json:"hash"`
	Type   string             `json:"type"`
}

// apiKeyAuthContextKey is the context key for api_key_auth security scheme
type apiKeyAuthContextKey string

// bearerContextKey is the context key for bearer security scheme
type bearerContextKey string

// bearerAuthContextKey is the context key for bearer_auth security scheme
type bearerAuthContextKey string

// ExecutionBridgeQuoteJSONRequestBody defines body for ExecutionBridgeQuote for application/json ContentType.
type ExecutionBridgeQuoteJSONRequestBody = ExecutionSelectorBuildInput

// ExecutionBridgeRouteJSONRequestBody defines body for ExecutionBridgeRoute for application/json ContentType.
type ExecutionBridgeRouteJSONRequestBody = ExecutionCrossChainInput

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ExecutionBridgeQuoteWithBody request with any body
	ExecutionBridgeQuoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecutionBridgeQuote(ctx context.Context, body ExecutionBridgeQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExecutionBridgeRouteWithBody request with any body
	ExecutionBridgeRouteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecutionBridgeRoute(ctx context.Context, body ExecutionBridgeRouteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ExecutionBridgeQuoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecutionBridgeQuoteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecutionBridgeQuote(ctx context.Context, body ExecutionBridgeQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecutionBridgeQuoteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecutionBridgeRouteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecutionBridgeRouteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecutionBridgeRoute(ctx context.Context, body ExecutionBridgeRouteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecutionBridgeRouteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewExecutionBridgeQuoteRequest calls the generic ExecutionBridgeQuote builder with application/json body
func NewExecutionBridgeQuoteRequest(server string, body ExecutionBridgeQuoteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecutionBridgeQuoteRequestWithBody(server, "application/json", bodyReader)
}

// NewExecutionBridgeQuoteRequestWithBody generates requests for ExecutionBridgeQuote with any type of body
func NewExecutionBridgeQuoteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/bridge/aggregator/quote/zerox")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewExecutionBridgeRouteRequest calls the generic ExecutionBridgeRoute builder with application/json body
func NewExecutionBridgeRouteRequest(server string, body ExecutionBridgeRouteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecutionBridgeRouteRequestWithBody(server, "application/json", bodyReader)
}

// NewExecutionBridgeRouteRequestWithBody generates requests for ExecutionBridgeRoute with any type of body
func NewExecutionBridgeRouteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/bridge/aggregator/route/zerox")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ExecutionBridgeQuoteWithBodyWithResponse request with any body
	ExecutionBridgeQuoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecutionBridgeQuoteResponse, error)

	ExecutionBridgeQuoteWithResponse(ctx context.Context, body ExecutionBridgeQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecutionBridgeQuoteResponse, error)

	// ExecutionBridgeRouteWithBodyWithResponse request with any body
	ExecutionBridgeRouteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecutionBridgeRouteResponse, error)

	ExecutionBridgeRouteWithResponse(ctx context.Context, body ExecutionBridgeRouteJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecutionBridgeRouteResponse, error)
}

type ExecutionBridgeQuoteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ExecutionBuildResponse
}

// Status returns HTTPResponse.Status
func (r ExecutionBridgeQuoteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecutionBridgeQuoteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExecutionBridgeQuoteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ExecutionBridgeRouteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ExecutionTransactionQuoteResponse
}

// Status returns HTTPResponse.Status
func (r ExecutionBridgeRouteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecutionBridgeRouteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExecutionBridgeRouteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ExecutionBridgeQuoteWithBodyWithResponse request with arbitrary body returning *ExecutionBridgeQuoteResponse
func (c *ClientWithResponses) ExecutionBridgeQuoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecutionBridgeQuoteResponse, error) {
	rsp, err := c.ExecutionBridgeQuoteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecutionBridgeQuoteResponse(rsp)
}

func (c *ClientWithResponses) ExecutionBridgeQuoteWithResponse(ctx context.Context, body ExecutionBridgeQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecutionBridgeQuoteResponse, error) {
	rsp, err := c.ExecutionBridgeQuote(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecutionBridgeQuoteResponse(rsp)
}

// ExecutionBridgeRouteWithBodyWithResponse request with arbitrary body returning *ExecutionBridgeRouteResponse
func (c *ClientWithResponses) ExecutionBridgeRouteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecutionBridgeRouteResponse, error) {
	rsp, err := c.ExecutionBridgeRouteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecutionBridgeRouteResponse(rsp)
}

func (c *ClientWithResponses) ExecutionBridgeRouteWithResponse(ctx context.Context, body ExecutionBridgeRouteJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecutionBridgeRouteResponse, error) {
	rsp, err := c.ExecutionBridgeRoute(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecutionBridgeRouteResponse(rsp)
}

// ParseExecutionBridgeQuoteResponse parses an HTTP response from a ExecutionBridgeQuoteWithResponse call
func ParseExecutionBridgeQuoteResponse(rsp *http.Response) (*ExecutionBridgeQuoteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecutionBridgeQuoteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ExecutionBuildResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseExecutionBridgeRouteResponse parses an HTTP response from a ExecutionBridgeRouteWithResponse call
func ParseExecutionBridgeRouteResponse(rsp *http.Response) (*ExecutionBridgeRouteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecutionBridgeRouteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ExecutionTransactionQuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}
